mlpack: mlpack::data::LoadCSV Class Reference
mlpack::data::LoadCSV Class Reference
Load the csv file.This class use boost::spirit to implement the parser, please refer to following link http://theboostcpplibraries.com/boost.spirit for quick review.
Classes
struct ElemParser
Public Member Functions
LoadCSV (std::string file, bool fatal=false)
size_t ColSize ()
template<typename T , typename MapPolicy >
void GetMatrixSize (size_t &rows, size_t &cols, DatasetMapper< MapPolicy > &info)
Peek at the file to determine the number of rows and columns in the matrix, assuming a non-transposed matrix.
template<typename T , typename MapPolicy >
void GetTransposeMatrixSize (size_t &rows, size_t &cols, DatasetMapper< MapPolicy > &info)
template<typename T , typename PolicyType >
void Load (arma::Mat< T > &inout, DatasetMapper< PolicyType > &infoSet, bool transpose=true)
size_t RowSize ()
Private Types
using iter_type = boost::iterator_range< std::string::iterator >
Private Member Functions
bool CanOpen ()
boost::spirit::qi::rule< std::string::iterator, iter_type(), boost::spirit::ascii::space_type > CreateCharRule () const
template<typename T >
boost::spirit::qi::rule< std::string::iterator, T(), boost::spirit::ascii::space_type > CreateNumRule () const
template<typename T , typename PolicyType >
void NonTranposeParse (arma::Mat< T > &inout, DatasetMapper< PolicyType > &infoSet)
template<typename T , typename PolicyType >
void TranposeParse (arma::Mat< T > &inout, DatasetMapper< PolicyType > &infoSet)
template<typename T , typename PolicyType >
bool TranposeParseImpl (arma::Mat< T > &inout, DatasetMapper< PolicyType > &infoSet)
Private Attributes
std::string extension
bool fatalIfOpenFail
std::string fileName
std::ifstream inFile
Detailed Description
Load the csv file.This class use boost::spirit to implement the parser, please refer to following link http://theboostcpplibraries.com/boost.spirit for quick review.
Definition at line 36 of file load_csv.hpp.
Member Typedef Documentation
iter_type
using mlpack::data::LoadCSV::iter_type = boost::iterator_range<std::string::iterator> private
Definition at line 186 of file load_csv.hpp.
Constructor & Destructor Documentation
LoadCSV()
mlpack::data::LoadCSV::LoadCSV (std::string file, bool fatal = false) explicit
Member Function Documentation
CanOpen()
bool mlpack::data::LoadCSV::CanOpen () private
Referenced by Load(), and mlpack::data::LoadCSV::ElemParser::Parser().
ColSize()
size_t mlpack::data::LoadCSV::ColSize ()
Referenced by Load().
CreateCharRule()
boost::spirit::qi::rule<std::string::iterator, iter_type(), boost::spirit::ascii::space_type> mlpack::data::LoadCSV::CreateCharRule () const private
Referenced by CreateNumRule(), GetMatrixSize(), GetTransposeMatrixSize(), NonTranposeParse(), and TranposeParseImpl().
CreateNumRule()
template<typename T > boost::spirit::qi::rule<std::string::iterator, T(), boost::spirit::ascii::space_type> mlpack::data::LoadCSV::CreateNumRule () const inline private
Definition at line 318 of file load_csv.hpp.
References CreateCharRule(), and extension.
GetMatrixSize()
template<typename T , typename MapPolicy > void mlpack::data::LoadCSV::GetMatrixSize (size_t & rows, size_t & cols, DatasetMapper< MapPolicy > & info) inline
Peek at the file to determine the number of rows and columns in the matrix, assuming a non-transposed matrix.
This will also take a first pass over the data for DatasetMapper, if MapPolicy::NeedsFirstPass is true. The info object will be re-initialized with the correct dimensionality.
Parameters
rows Variable to be filled with the number of rows.
cols Variable to be filled with the number of columns.
info DatasetMapper object to use for first pass.
Definition at line 73 of file load_csv.hpp.
References CreateCharRule(), and inFile.
GetTransposeMatrixSize()
template<typename T , typename MapPolicy > void mlpack::data::LoadCSV::GetTransposeMatrixSize (size_t & rows, size_t & cols, DatasetMapper< MapPolicy > & info) inline
Definition at line 133 of file load_csv.hpp.
References CreateCharRule(), and inFile.
Load()
template<typename T , typename PolicyType > void mlpack::data::LoadCSV::Load (arma::Mat< T > & inout, DatasetMapper< PolicyType > & infoSet, bool transpose = true) inline
Definition at line 42 of file load_csv.hpp.
References CanOpen(), ColSize(), NonTranposeParse(), RowSize(), and TranposeParse().
NonTranposeParse()
template<typename T , typename PolicyType > void mlpack::data::LoadCSV::NonTranposeParse (arma::Mat< T > & inout, DatasetMapper< PolicyType > & infoSet) inline private
Definition at line 212 of file load_csv.hpp.
References CreateCharRule(), and inFile.
Referenced by Load().
RowSize()
size_t mlpack::data::LoadCSV::RowSize ()
Referenced by Load().
TranposeParse()
template<typename T , typename PolicyType > void mlpack::data::LoadCSV::TranposeParse (arma::Mat< T > & inout, DatasetMapper< PolicyType > & infoSet) inline private
Definition at line 260 of file load_csv.hpp.
References TranposeParseImpl().
Referenced by Load().
TranposeParseImpl()
template<typename T , typename PolicyType > bool mlpack::data::LoadCSV::TranposeParseImpl (arma::Mat< T > & inout, DatasetMapper< PolicyType > & infoSet) inline private
Definition at line 272 of file load_csv.hpp.
References CreateCharRule(), and inFile.
Referenced by TranposeParse().
Member Data Documentation
extension
std::string mlpack::data::LoadCSV::extension private
Definition at line 351 of file load_csv.hpp.
Referenced by CreateNumRule().
fatalIfOpenFail
bool mlpack::data::LoadCSV::fatalIfOpenFail private
Definition at line 352 of file load_csv.hpp.
fileName
std::string mlpack::data::LoadCSV::fileName private
Definition at line 353 of file load_csv.hpp.
inFile
std::ifstream mlpack::data::LoadCSV::inFile private
Definition at line 354 of file load_csv.hpp.
Referenced by GetMatrixSize(), GetTransposeMatrixSize(), NonTranposeParse(), and TranposeParseImpl().
The documentation for this class was generated from the following file:
src/mlpack/core/data/load_csv.hpp