mlpack: mlpack::tree::XTreeAuxiliaryInformation< TreeType > Class Template Reference
mlpack::tree::XTreeAuxiliaryInformation< TreeType > Class Template Reference
The XTreeAuxiliaryInformation class provides information specific to X trees for each node in a RectangleTree.
Classes
struct SplitHistoryStruct
The X tree requires that the tree records it's "split history".
Public Types
typedef struct mlpack::tree::XTreeAuxiliaryInformation::SplitHistoryStruct SplitHistoryStruct
The X tree requires that the tree records it's "split history".
Public Member Functions
XTreeAuxiliaryInformation ()
Default constructor.
XTreeAuxiliaryInformation (const TreeType *node)
Construct this with the specified node.
XTreeAuxiliaryInformation (const XTreeAuxiliaryInformation &other, TreeType *=NULL, bool=true)
Create an auxiliary information object by copying from another object.
XTreeAuxiliaryInformation (XTreeAuxiliaryInformation &&other)
Create an auxiliary information object by moving from the other node.
bool HandleNodeInsertion (TreeType *, TreeType *, bool)
Some tree types require to save some properties at the insertion process.
bool HandleNodeRemoval (TreeType *, const size_t)
Some tree types require to save some properties at the deletion process.
bool HandlePointDeletion (TreeType *, const size_t)
Some tree types require to save some properties at the deletion process.
bool HandlePointInsertion (TreeType *, const size_t)
Some tree types require to save some properties at the insertion process.
size_t NormalNodeMaxNumChildren () const
Return the maximum number of a normal node's children.
size_t & NormalNodeMaxNumChildren ()
Modify the maximum number of a normal node's children.
void NullifyData ()
Nullify the auxiliary information in order to prevent an invalid free.
XTreeAuxiliaryInformation & operator= (const XTreeAuxiliaryInformation &other)
Copy the auxiliary information object.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Serialize the information.
const SplitHistoryStruct & SplitHistory () const
Return the split history of the node associated with this object.
SplitHistoryStruct & SplitHistory ()
Modify the split history of the node associated with this object.
bool UpdateAuxiliaryInfo (TreeType *)
Some tree types require to propagate the information upward.
Private Attributes
size_t normalNodeMaxNumChildren
The max number of child nodes a non-leaf normal node can have.
SplitHistoryStruct splitHistory
A struct to store the "split history" for X trees.
Detailed Description
template<typename TreeType>
class mlpack::tree::XTreeAuxiliaryInformation< TreeType >
The XTreeAuxiliaryInformation class provides information specific to X trees for each node in a RectangleTree.
Definition at line 24 of file x_tree_auxiliary_information.hpp.
Member Typedef Documentation
SplitHistoryStruct
template<typename TreeType > typedef struct mlpack::tree::XTreeAuxiliaryInformation::SplitHistoryStruct mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct
The X tree requires that the tree records it's "split history".
To make this easy, we use the following structure.
Constructor & Destructor Documentation
XTreeAuxiliaryInformation() [1/4]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::XTreeAuxiliaryInformation () inline
Default constructor.
Definition at line 28 of file x_tree_auxiliary_information.hpp.
XTreeAuxiliaryInformation() [2/4]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::XTreeAuxiliaryInformation (const TreeType * node) inline
Construct this with the specified node.
Parameters
node The node that stores this auxiliary information.
Definition at line 38 of file x_tree_auxiliary_information.hpp.
XTreeAuxiliaryInformation() [3/4]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::XTreeAuxiliaryInformation (const XTreeAuxiliaryInformation< TreeType > & other, TreeType * = NULL, bool = true) inline
Create an auxiliary information object by copying from another object.
Parameters
other Another auxiliary information object from which the information will be copied.
tree The node that holds the auxiliary information.
deepCopy If false, the new object uses the same memory (not used here).
Definition at line 54 of file x_tree_auxiliary_information.hpp.
XTreeAuxiliaryInformation() [4/4]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::XTreeAuxiliaryInformation (XTreeAuxiliaryInformation< TreeType > && other) inline
Create an auxiliary information object by moving from the other node.
Parameters
other The object from which the information will be moved.
Definition at line 79 of file x_tree_auxiliary_information.hpp.
Member Function Documentation
HandleNodeInsertion()
template<typename TreeType > bool mlpack::tree::XTreeAuxiliaryInformation< TreeType >::HandleNodeInsertion (TreeType * , TreeType * , bool) inline
Some tree types require to save some properties at the insertion process.
This method allows the auxiliary information the option of manipulating the tree in order to perform the insertion process. If the auxiliary information does that, then the method should return true; if the method returns false the RectangleTree performs its default behavior.
Parameters
node The node in which the nodeToInsert is being inserted.
nodeToInsert The node being inserted.
insertionLevel The level of the tree at which the nodeToInsert should be inserted.
Definition at line 113 of file x_tree_auxiliary_information.hpp.
HandleNodeRemoval()
template<typename TreeType > bool mlpack::tree::XTreeAuxiliaryInformation< TreeType >::HandleNodeRemoval (TreeType * , const size_t) inline
Some tree types require to save some properties at the deletion process.
This method allows the auxiliary information the option of manipulating the tree in order to perform the deletion process. If the auxiliary information does that, then the method should return true; if the method returns false the RectangleTree performs its default behavior.
Parameters
node The node from which the node is being deleted.
nodeIndex The local index of the node being deleted.
Definition at line 143 of file x_tree_auxiliary_information.hpp.
HandlePointDeletion()
template<typename TreeType > bool mlpack::tree::XTreeAuxiliaryInformation< TreeType >::HandlePointDeletion (TreeType * , const size_t) inline
Some tree types require to save some properties at the deletion process.
This method allows the auxiliary information the option of manipulating the tree in order to perform the deletion process. If the auxiliary information does that, then the method should return true; if the method returns false the RectangleTree performs its default behavior.
Parameters
node The node from which the point is being deleted.
localIndex The local index of the point being deleted.
Definition at line 129 of file x_tree_auxiliary_information.hpp.
HandlePointInsertion()
template<typename TreeType > bool mlpack::tree::XTreeAuxiliaryInformation< TreeType >::HandlePointInsertion (TreeType * , const size_t) inline
Some tree types require to save some properties at the insertion process.
This method allows the auxiliary information the option of manipulating the tree in order to perform the insertion process. If the auxiliary information does that, then the method should return true; if the method returns false the RectangleTree performs its default behavior.
Parameters
node The node in which the point is being inserted.
point The global number of the point being inserted.
Definition at line 96 of file x_tree_auxiliary_information.hpp.
NormalNodeMaxNumChildren() [1/2]
template<typename TreeType > size_t mlpack::tree::XTreeAuxiliaryInformation< TreeType >::NormalNodeMaxNumChildren () const inline
Return the maximum number of a normal node's children.
Definition at line 215 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::normalNodeMaxNumChildren.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::operator=().
NormalNodeMaxNumChildren() [2/2]
template<typename TreeType > size_t& mlpack::tree::XTreeAuxiliaryInformation< TreeType >::NormalNodeMaxNumChildren () inline
Modify the maximum number of a normal node's children.
Definition at line 217 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::normalNodeMaxNumChildren.
NullifyData()
template<typename TreeType > void mlpack::tree::XTreeAuxiliaryInformation< TreeType >::NullifyData () inline
Nullify the auxiliary information in order to prevent an invalid free.
Definition at line 162 of file x_tree_auxiliary_information.hpp.
operator=()
template<typename TreeType > XTreeAuxiliaryInformation& mlpack::tree::XTreeAuxiliaryInformation< TreeType >::operator= (const XTreeAuxiliaryInformation< TreeType > & other) inline
Copy the auxiliary information object.
Parameters
other The node from which the information will be copied.
Definition at line 66 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::normalNodeMaxNumChildren, mlpack::tree::XTreeAuxiliaryInformation< TreeType >::NormalNodeMaxNumChildren(), mlpack::tree::XTreeAuxiliaryInformation< TreeType >::splitHistory, and mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistory().
Serialize()
template<typename TreeType > template<typename Archive > void mlpack::tree::XTreeAuxiliaryInformation< TreeType >::Serialize (Archive & ar, const unsigned int) inline
Serialize the information.
Definition at line 227 of file x_tree_auxiliary_information.hpp.
References mlpack::data::CreateNVP().
SplitHistory() [1/2]
template<typename TreeType > const SplitHistoryStruct& mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistory () const inline
Return the split history of the node associated with this object.
Definition at line 219 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::splitHistory.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::operator=().
SplitHistory() [2/2]
template<typename TreeType > SplitHistoryStruct& mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistory () inline
Modify the split history of the node associated with this object.
Definition at line 221 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::splitHistory.
UpdateAuxiliaryInfo()
template<typename TreeType > bool mlpack::tree::XTreeAuxiliaryInformation< TreeType >::UpdateAuxiliaryInfo (TreeType *) inline
Some tree types require to propagate the information upward.
This method should return false if this is not the case. If true is returned, the update will be propagated upward.
Parameters
node The node in which the auxiliary information being update.
Definition at line 154 of file x_tree_auxiliary_information.hpp.
Member Data Documentation
normalNodeMaxNumChildren
template<typename TreeType > size_t mlpack::tree::XTreeAuxiliaryInformation< TreeType >::normalNodeMaxNumChildren private
The max number of child nodes a non-leaf normal node can have.
Definition at line 209 of file x_tree_auxiliary_information.hpp.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::NormalNodeMaxNumChildren(), and mlpack::tree::XTreeAuxiliaryInformation< TreeType >::operator=().
splitHistory
template<typename TreeType > SplitHistoryStruct mlpack::tree::XTreeAuxiliaryInformation< TreeType >::splitHistory private
A struct to store the "split history" for X trees.
Definition at line 211 of file x_tree_auxiliary_information.hpp.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::operator=(), and mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistory().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/rectangle_tree/x_tree_auxiliary_information.hpp