mlpack: mlpack::tree::ProjVector Class Reference
mlpack::tree::ProjVector Class Reference
ProjVector defines a general projection vector (not necessarily axis-parallel).
Public Member Functions
ProjVector ()
Empty Constructor.
ProjVector (const arma::vec &vect)
Create the projection vector based on the specified vector.
template<typename VecType >
double Project (const VecType &point, typename boost::enable_if< IsVector< VecType > >::type *=0) const
Project the given point on the projection vector.
template<typename MetricType , typename VecType >
math::RangeType< typename VecType::elem_type > Project (const bound::BallBound< MetricType, VecType > &bound) const
Project the given ball bound on the projection vector.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Serialization.
Private Attributes
arma::vec projVect
Projection vector.
Detailed Description
ProjVector defines a general projection vector (not necessarily axis-parallel).
Definition at line 91 of file projection_vector.hpp.
Constructor & Destructor Documentation
ProjVector() [1/2]
mlpack::tree::ProjVector::ProjVector () inline
Empty Constructor.
Definition at line 100 of file projection_vector.hpp.
ProjVector() [2/2]
mlpack::tree::ProjVector::ProjVector (const arma::vec & vect) inline
Create the projection vector based on the specified vector.
Parameters
vect Vector to be considered.
Definition at line 109 of file projection_vector.hpp.
Member Function Documentation
Project() [1/2]
template<typename VecType > double mlpack::tree::ProjVector::Project (const VecType & point, typename boost::enable_if< IsVector< VecType > >::type * = 0) const inline
Project the given point on the projection vector.
Parameters
point Point to be projected.
Definition at line 119 of file projection_vector.hpp.
Project() [2/2]
template<typename MetricType , typename VecType > math::RangeType<typename VecType::elem_type> mlpack::tree::ProjVector::Project (const bound::BallBound< MetricType, VecType > & bound) const inline
Project the given ball bound on the projection vector.
Parameters
bound Bound to be projected.
Returns
Range of projected values.
Definition at line 132 of file projection_vector.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::Center(), mlpack::tree::AxisParallelProjVector::Project(), and mlpack::bound::BallBound< MetricType, VecType >::Radius().
Serialize()
template<typename Archive > void mlpack::tree::ProjVector::Serialize (Archive & ar, const unsigned int) inline
Serialization.
Definition at line 145 of file projection_vector.hpp.
References mlpack::data::CreateNVP().
Member Data Documentation
projVect
arma::vec mlpack::tree::ProjVector::projVect private
Projection vector.
Definition at line 94 of file projection_vector.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/tree/space_split/projection_vector.hpp