main
about
docs
get help
github
src/mlpack/bindings/python/CMakeLists.txt File Reference
Functions
not building Python bindings else () message(STATUS "Found Python
endif () include($
CMake FindPythonModule cmake find_python_module (distutils) if(NOT PY_DISTUTILS) not_found_return("distutils not found
macro (not_found_return message) message(STATUS "$
macro (add_python_binding name) endmacro() return() endmacro() if(NOT BUILD_PYTHON_BINDINGS) not_found_return("Not building Python bindings.") endif() find_program(PYTHON "python" REQUIRED) if(NOT PYTHON) not_found_return("Python not found
PROPERTY INCLUDE_DIRECTORIES set (CYTHON_INCLDIRS "${CYTHON_INCLUDE_DIRECTORIES}") if(DEBUG) set(DISABLE_CFLAGS "NDEBUG") endif() add_custom_target(python ALL DEPENDS mlpack) add_custom_target(python_copy ALL DEPENDS mlpack) add_custom_command(TARGET python_copy PRE_BUILD COMMAND $
Function Documentation
else()
not building Python bindings else ()
Definition at line 21 of file CMakeLists.txt.
endif()
not building Python bindings endif ()
Definition at line 23 of file CMakeLists.txt.
Referenced by add_custom_command(), include_directories(), macro(), and set().
find_python_module()
CMake FindPythonModule cmake find_python_module (distutils)
macro() [1/2]
macro (not_found_return message)
Definition at line 1 of file CMakeLists.txt.
macro() [2/2]
macro (add_python_binding name)
set()
PROPERTY INCLUDE_DIRECTORIES set (CYTHON_INCLDIRS "${CYTHON_INCLUDE_DIRECTORIES}")
Definition at line 93 of file CMakeLists.txt.
References install().