main
about
docs
get help
github
src/mlpack/bindings/matlab/CMakeLists.txt File Reference
Functions
the MATLAB version can probably be deleted (always save a copy in case this is wrong!)." "\nFor more information on this confusing issue
find_package (MatlabMex REQUIRED) if(UNIX) execute_process(COMMAND "$
test cpp RESULT_VARIABLE MEX_RESULT_TRASH OUTPUT_VARIABLE MEX_OUTPUT ERROR_VARIABLE MEX_ERROR_TRASH string (REGEX MATCH "Warning: You are using" MEX_WARNING "${MEX_OUTPUT}") if(MEX_WARNING) string(REGEX REPLACE ".*using [a-zA-Z]* version \[0-9.]*)[^\*\*" "\" OTHER_COMPILER_VERSION "$
string (REGEX REPLACE ".*currently supported with MEX is \[0-9.]*)[^\*\*" "\" MEX_COMPILER_VERSION "${MEX_OUTPUT}") set(NEED_TO_WARN 1) if(MEX_COMPILER_VERSION AND OTHER_COMPILER_VERSION) if(NOT("$
Variables
the MATLAB version can probably be see n http
VERSION_LESS
Function Documentation
deleted()
the MATLAB version can probably be deleted (always save a copy in case this is wrong!)
find_package()
find_package (MatlabMex REQUIRED)
Definition at line 5 of file CMakeLists.txt.
string() [1/2]
test cpp RESULT_VARIABLE MEX_RESULT_TRASH OUTPUT_VARIABLE MEX_OUTPUT ERROR_VARIABLE MEX_ERROR_TRASH string (REGEX MATCH "Warning: You are using" MEX_WARNING "${MEX_OUTPUT}")
Definition at line 18 of file CMakeLists.txt.
Referenced by add_custom_command(), mlpack::bindings::cli::AddToPO(), CLIOption< N >::CLIOption(), mlpack::bindings::cli::DefaultParam(), mlpack::bindings::cli::EndProgram(), mlpack::data::Extension(), FilterFileName(), mlpack::bindings::python::GetCythonType(), LoadCSV::GetMatrixSize(), mlpack::bindings::cli::GetParam(), mlpack::bindings::cli::GetPrintableParam(), mlpack::bindings::tests::GetPrintableParam(), mlpack::bindings::python::GetPrintableParam(), mlpack::bindings::cli::GetPrintableParamName(), mlpack::bindings::cli::GetPrintableParamValue(), mlpack::bindings::python::GetPythonType(), LoadCSV::GetTransposeMatrixSize(), mlpack::util::HyphenateString(), mlpack::bindings::python::ImportDecl(), include_directories(), mlpack::bindings::cli::MapParameterName(), mlpack::bindings::cli::ParseCommandLine(), PrefixedOutStream::PrefixedOutStream(), mlpack::bindings::python::PrintClassDefn(), mlpack::bindings::python::PrintDefn(), mlpack::bindings::python::PrintInputProcessing(), mlpack::bindings::python::PrintOutputProcessing(), RSModel::RandomBasis(), NSModel< SortPolicy >::RandomBasis(), DatasetMapper< PolicyType >::Serialize(), mlpack::SerializeObject(), mlpack::SerializePointerObject(), mlpack::bindings::cli::StringTypeParam(), mlpack::TestArmadilloSerialization(), TestOption< N >::TestOption(), and Timers::Timers().
string() [2/2]
string (REGEX REPLACE ".*currently supported with MEX is \[0-9.]*)*\*" "\" MEX_COMPILER_VERSION "${MEX_OUTPUT}" [^\"])
Definition at line 27 of file CMakeLists.txt.
Variable Documentation
http
the MATLAB version can probably be see n http
Definition at line 56 of file CMakeLists.txt.
VERSION_LESS
VERSION_LESS
Initial value:
{OTHER_COMPILER_VERSION}"))
        set(NEED_TO_WARN 0)
      endif(NOT ("${MEX_COMPILER_VERSION}" VERSION_LESS
          "${OTHER_COMPILER_VERSION}"))
    endif()
    if(NEED_TO_WARN EQUAL 1)
      message(WARNING "The MATLAB runtime glibc is different than the system "
          " glibc.  This can (and probably will) cause the MLPACK bindings "
          "generated by this build script to fail with odd GLIBCXX_a_b_c "
          "version complaints when they are run.  Assuming that the system "
          "glibc is newer than the MATLAB-provided version
Definition at line 38 of file CMakeLists.txt.