main
about
docs
get help
github
UpdateSpan Class Reference
Recalculate the optimal solution in the span of all previous solution space, used as update step for FrankWolfe algorithm.
Public Member Functions
UpdateSpan ()
Construct the span update rule.
const arma::mat & CurrentAtoms () const
Get the current atoms.
arma::mat & CurrentAtoms ()
Modify the current atoms.
const arma::uvec & CurrentIndices () const
Get the current atom indices.
arma::uvec & CurrentIndices ()
Modify the current atom indices.
void Update (FuncSq &function, const arma::mat &, const arma::mat &s, arma::mat &newCoords, const size_t)
Update rule for FrankWolfe, reoptimize in the span of current solution space.
Detailed Description
Recalculate the optimal solution in the span of all previous solution space, used as update step for FrankWolfe algorithm.
Currently only works for function in FuncSq class.
Definition at line 29 of file update_span.hpp.
Constructor & Destructor Documentation
UpdateSpan()
UpdateSpan () inline
Construct the span update rule.
The function to be optimized is input here.
Parameters
function Function to be optimized in FrankWolfe algorithm.
Definition at line 38 of file update_span.hpp.
Member Function Documentation
CurrentAtoms() [1/2]
const arma::mat& CurrentAtoms () const inline
Get the current atoms.
Definition at line 76 of file update_span.hpp.
Referenced by UpdateSpan::CurrentAtoms().
CurrentAtoms() [2/2]
arma::mat& CurrentAtoms () inline
Modify the current atoms.
Definition at line 78 of file update_span.hpp.
References UpdateSpan::CurrentAtoms(), and UpdateSpan::CurrentIndices().
CurrentIndices() [1/2]
const arma::uvec& CurrentIndices () const inline
Get the current atom indices.
Definition at line 71 of file update_span.hpp.
Referenced by UpdateSpan::CurrentAtoms().
CurrentIndices() [2/2]
arma::uvec& CurrentIndices () inline
Modify the current atom indices.
Definition at line 73 of file update_span.hpp.
Update()
void Update (FuncSq & function, const arma::mat & , const arma::mat & s, arma::mat & newCoords, const size_t) inline
Update rule for FrankWolfe, reoptimize in the span of current solution space.
Parameters
function function to be optimized.
oldCoords previous solution coords, not used in this update rule.
s current linearConstrSolution result.
newCoords output new solution coords.
numIter current iteration number.
Definition at line 51 of file update_span.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/fw/update_span.hpp