main
about
docs
get help
github
RNN< OutputLayerType, InitializationRuleType > Class Template Reference
Implementation of a standard recurrent neural network container.
Public Types
using NetworkType = RNN< OutputLayerType, InitializationRuleType >
Convenience typedef for the internal model construction.
Public Member Functions
RNN (const size_t rho, const bool single=false, OutputLayerType outputLayer=OutputLayerType(), InitializationRuleType initializeRule=InitializationRuleType())
Create the RNN object with the given predictors and responses set (this is the set that is used to train the network).
RNN (arma::mat predictors, arma::mat responses, const size_t rho, const bool single=false, OutputLayerType outputLayer=OutputLayerType(), InitializationRuleType initializeRule=InitializationRuleType())
Create the RNN object with the given predictors and responses set (this is the set that is used to train the network).
~RNN ()
Destructor to release allocated memory.
template
<
typename
LayerType
>
void Add (const LayerType &layer)
template<class LayerType , class... Args>
void Add (Args... args)
void Add (LayerTypes layer)
double Evaluate (const arma::mat &, const size_t i, const bool deterministic=true)
Evaluate the recurrent neural network with the given parameters.
void Gradient (const arma::mat &parameters, const size_t i, arma::mat &gradient)
Evaluate the gradient of the recurrent neural network with the given parameters, and with respect to only one point in the dataset.
size_t NumFunctions () const
Return the number of separable functions (the number of predictor points).
const arma::mat & Parameters () const
Return the initial point for the optimization.
arma::mat & Parameters ()
Modify the initial point for the optimization.
void Predict (arma::mat predictors, arma::mat &results)
Predict the responses to a given set of predictors.
const size_t & Rho () const
Return the maximum length of backpropagation through time.
size_t & Rho ()
Modify the maximum length of backpropagation through time.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the model.
template
<
typename
OptimizerType
>
void Train (arma::mat predictors, arma::mat responses, OptimizerType &optimizer)
Train the recurrent neural network on the given input data using the given optimizer.
template
<
typename
OptimizerType
=
mlpack::optimization::StandardSGD
>
void Train (arma::mat predictors, arma::mat responses)
Train the recurrent neural network on the given input data.
Detailed Description
template<typename OutputLayerType = NegativeLogLikelihood<>, typename InitializationRuleType = RandomInitialization> class mlpack::ann::RNN< OutputLayerType, InitializationRuleType >
Implementation of a standard recurrent neural network container.
Template Parameters
OutputLayerType The output layer type used to evaluate the network.
InitializationRuleType Rule used to initialize the weight matrix.
Definition at line 41 of file rnn.hpp.
Member Typedef Documentation
NetworkType
using NetworkType = RNN<OutputLayerType, InitializationRuleType>
Convenience typedef for the internal model construction.
Definition at line 45 of file rnn.hpp.
Constructor & Destructor Documentation
RNN() [1/2]
RNN (const size_t rho, const bool single = false, OutputLayerType outputLayer = OutputLayerType(), InitializationRuleType initializeRule = InitializationRuleType())
Create the RNN object with the given predictors and responses set (this is the set that is used to train the network).
Optionally, specify which initialize rule and performance function should be used.
If you want to pass in a parameter and discard the original parameter object, be sure to use std::move to avoid unnecessary copy.
Parameters
rho Maximum number of steps to backpropagate through time (BPTT).
single Predict only the last element of the input sequence.
outputLayer Output layer used to evaluate the network.
initializeRule Optional instantiated InitializationRule object for initializing the network parameter.
RNN() [2/2]
RNN (arma::mat predictors, arma::mat responses, const size_t rho, const bool single = false, OutputLayerType outputLayer = OutputLayerType(), InitializationRuleType initializeRule = InitializationRuleType())
Create the RNN object with the given predictors and responses set (this is the set that is used to train the network).
Optionally, specify which initialize rule and performance function should be used.
If you want to pass in a parameter and discard the original parameter object, be sure to use std::move to avoid unnecessary copy.
Parameters
predictors Input training variables.
responses Outputs results from input training variables.
rho Maximum number of steps to backpropagate through time (BPTT).
single Predict only the last element of the input sequence.
outputLayer Output layer used to evaluate the network.
initializeRule Optional instantiated InitializationRule object for initializing the network parameter.
~RNN()
~RNN ()
Destructor to release allocated memory.
Member Function Documentation
Add() [1/3]
void Add (const LayerType & layer) inline
Definition at line 180 of file rnn.hpp.
Add() [2/3]
void Add (Args... args) inline
Definition at line 188 of file rnn.hpp.
Add() [3/3]
void Add (LayerTypes layer) inline
Definition at line 195 of file rnn.hpp.
Evaluate()
double Evaluate (const arma::mat & , const size_t i, const bool deterministic = true)
Evaluate the recurrent neural network with the given parameters.
This function is usually called by the optimizer to train the model.
Parameters
parameters Matrix model parameters.
i Index of point to use for objective function evaluation.
deterministic Whether or not to train or test the model. Note some layer act differently in training or testing mode.
Gradient()
void Gradient (const arma::mat & parameters, const size_t i, arma::mat & gradient)
Evaluate the gradient of the recurrent neural network with the given parameters, and with respect to only one point in the dataset.
This is useful for optimizers such as SGD, which require a separable objective function.
Parameters
parameters Matrix of the model parameters to be optimized.
i Index of points to use for objective function gradient evaluation.
gradient Matrix to output gradient into.
Referenced by RNN< OutputLayerType, InitializationRuleType >::Rho().
NumFunctions()
size_t NumFunctions () const inline
Return the number of separable functions (the number of predictor points).
Definition at line 198 of file rnn.hpp.
Parameters() [1/2]
const arma::mat& Parameters () const inline
Return the initial point for the optimization.
Definition at line 201 of file rnn.hpp.
Parameters() [2/2]
arma::mat& Parameters () inline
Modify the initial point for the optimization.
Definition at line 203 of file rnn.hpp.
Predict()
void Predict (arma::mat predictors, arma::mat & results)
Predict the responses to a given set of predictors.
The responses will reflect the output of the given output layer as returned by the output layer function.
If you want to pass in a parameter and discard the original parameter object, be sure to use std::move to avoid unnecessary copy.
Parameters
predictors Input predictors.
results Matrix to put output predictions of responses into.
Rho() [1/2]
const size_t& Rho () const inline
Return the maximum length of backpropagation through time.
Definition at line 206 of file rnn.hpp.
Rho() [2/2]
size_t& Rho () inline
Modify the maximum length of backpropagation through time.
Definition at line 208 of file rnn.hpp.
References RNN< OutputLayerType, InitializationRuleType >::Gradient(), and RNN< OutputLayerType, InitializationRuleType >::Serialize().
Serialize()
void Serialize (Archive & ar, const unsigned int)
Serialize the model.
Referenced by RNN< OutputLayerType, InitializationRuleType >::Rho().
Train() [1/2]
void Train (arma::mat predictors, arma::mat responses, OptimizerType & optimizer)
Train the recurrent neural network on the given input data using the given optimizer.
This will use the existing model parameters as a starting point for the optimization. If this is not what you want, then you should access the parameters vector directly with Parameters() and modify it as desired.
If you want to pass in a parameter and discard the original parameter object, be sure to use std::move to avoid unnecessary copy.
Template Parameters
OptimizerType Type of optimizer to use to train the model.
Parameters
predictors Input training variables.
responses Outputs results from input training variables.
optimizer Instantiated optimizer used to train the model.
Train() [2/2]
void Train (arma::mat predictors, arma::mat responses)
Train the recurrent neural network on the given input data.
By default, the SGD optimization algorithm is used, but others can be specified (such as mlpack::optimization::RMSprop).
This will use the existing model parameters as a starting point for the optimization. If this is not what you want, then you should access the parameters vector directly with Parameters() and modify it as desired.
If you want to pass in a parameter and discard the original parameter object, be sure to use std::move to avoid unnecessary copy.
Template Parameters
OptimizerType Type of optimizer to use to train the model.
Parameters
predictors Input training variables.
responses Outputs results from input training variables.
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/rnn.hpp