main
about
docs
get help
github
MiniBatchSGDType< UpdatePolicyType, DecayPolicyType > Class Template Reference
Mini-batch Stochastic Gradient Descent is a technique for minimizing a function which can be expressed as a sum of other functions.
Public Member Functions
MiniBatchSGDType (const size_t batchSize=1000, const double stepSize=0.01, const size_t maxIterations=100000, const double tolerance=1e-5, const bool shuffle=true, const UpdatePolicyType &updatePolicy=UpdatePolicyType(), const DecayPolicyType &decayPolicy=DecayPolicyType(), const bool resetPolicy=true)
Construct the MiniBatchSGD optimizer with the given function and parameters.
size_t BatchSize () const
Get the batch size.
size_t & BatchSize ()
Modify the batch size.
DecayPolicyType DecayPolicy () const
Get the decay policy.
DecayPolicyType & DecayPolicy ()
Modify the decay policy.
size_t MaxIterations () const
Get the maximum number of iterations (0 indicates no limit).
size_t & MaxIterations ()
Modify the maximum number of iterations (0 indicates no limit).
template
<
typename
DecomposableFunctionType
>
double Optimize (DecomposableFunctionType &function, arma::mat &iterate)
Optimize the given function using mini-batch SGD.
bool ResetPolicy () const
Get whether or not the update policy parameters are reset before Optimize call.
bool & ResetPolicy ()
Modify whether or not the update policy parameters are reset before Optimize call.
bool Shuffle () const
Get whether or not the individual functions are shuffled.
bool & Shuffle ()
Modify whether or not the individual functions are shuffled.
double StepSize () const
Get the step size.
double & StepSize ()
Modify the step size.
double Tolerance () const
Get the tolerance for termination.
double & Tolerance ()
Modify the tolerance for termination.
UpdatePolicyType UpdatePolicy () const
Get the update policy.
UpdatePolicyType & UpdatePolicy ()
Modify the update policy.
Detailed Description
template
<
typename
UpdatePolicyType
=
VanillaUpdate
,
typename
DecayPolicyType
=
NoDecay
>
class mlpack::optimization::MiniBatchSGDType< UpdatePolicyType, DecayPolicyType >
Mini-batch Stochastic Gradient Descent is a technique for minimizing a function which can be expressed as a sum of other functions.
That is, suppose we have
and our task is to minimize . Mini-batch SGD iterates over batches of functions for some batch size , producing the following update scheme:
where is a parameter which specifies the step size. Each mini-batch is passed through either sequentially or randomly. The algorithm continues until reaches the maximum number of iterations—or when a full sequence of updates through each of the mini-batches produces an improvement within a certain tolerance .
The parameter is specified by the tolerance parameter tot he constructor, as is the maximum number of iterations specified by the maxIterations parameter.
This class is useful for data-dependent functions whose objective function can be expressed as a sum of objective functions operating on an individual point. Then, mini-batch SGD considers the gradient of the objective function operation on an individual mini-batch of points in its update of .
For mini-batch SGD to work, a DecomposableFunctionType template parameter is required. This class must implement the following function:
size_t NumFunctions(); double Evaluate(const arma::mat& coordinates, const size_t i); void Gradient(const arma::mat& coordinates, const size_t i, arma::mat& gradient);
NumFunctions() should return the number of functions, and in the other two functions, the parameter i refers to which individual function (or gradient) is being evaluated. So, for the case of a data-dependent function, such as NCA (see mlpack::nca::NCA), NumFunctions() should return the number of points in the dataset, and Evaluate(coordinates, 0) will evaluate the objective function on the first point in the dataset (presumably, the dataset is held internally in the DecomposableFunctionType).
Template Parameters
DecomposableFunctionType Decomposable objective function type to be minimized.
update Update policy used during the iterative update process. By default the vanilla update policy (see mlpack::optimization::VanillaUpdate) is used.
UpdatePolicyType Update policy used during the iterative update process. By default the vanilla update policy (see mlpack::optimization::VanillaUpdate) is used.
DecayPolicyType Decay policy used during the iterative update process to adjust the step size. By default the step size isn't going to be adjusted.
Definition at line 88 of file minibatch_sgd.hpp.
Constructor & Destructor Documentation
MiniBatchSGDType()
MiniBatchSGDType (const size_t batchSize = 1000, const double stepSize = 0.01, const size_t maxIterations = 100000, const double tolerance = 1e-5, const bool shuffle = true, const UpdatePolicyType & updatePolicy = UpdatePolicyType(), const DecayPolicyType & decayPolicy = DecayPolicyType(), const bool resetPolicy = true)
Construct the MiniBatchSGD optimizer with the given function and parameters.
The defaults here are not necessarily good for the given problem, so it is suggested that the values used be tailored for the task at hand. The maximum number of iterations refers to the maximum number of mini-batches that are processed.
Parameters
batchSize Size of each mini-batch.
stepSize Step size for each iteration.
maxIterations Maximum number of iterations allowed (0 means no limit).
tolerance Maximum absolute tolerance to terminate algorithm.
shuffle If true, the mini-batch order is shuffled; otherwise, each mini-batch is visited in linear order.
updatePolicy Instantiated update policy used to adjust the given parameters.
decayPolicy Instantiated decay policy used to adjust the step size.
resetPolicy Flag that determines whether update policy parameters are reset before every Optimize call.
Member Function Documentation
BatchSize() [1/2]
size_t BatchSize () const inline
Get the batch size.
Definition at line 137 of file minibatch_sgd.hpp.
Referenced by SGDR< UpdatePolicyType >::BatchSize(), and SnapshotSGDR< UpdatePolicyType >::BatchSize().
BatchSize() [2/2]
size_t& BatchSize () inline
Modify the batch size.
Definition at line 139 of file minibatch_sgd.hpp.
DecayPolicy() [1/2]
DecayPolicyType DecayPolicy () const inline
Get the decay policy.
Definition at line 174 of file minibatch_sgd.hpp.
Referenced by SnapshotSGDR< UpdatePolicyType >::Snapshots().
DecayPolicy() [2/2]
DecayPolicyType& DecayPolicy () inline
Modify the decay policy.
Definition at line 176 of file minibatch_sgd.hpp.
MaxIterations() [1/2]
size_t MaxIterations () const inline
Get the maximum number of iterations (0 indicates no limit).
Definition at line 147 of file minibatch_sgd.hpp.
Referenced by SGDR< UpdatePolicyType >::MaxIterations(), and SnapshotSGDR< UpdatePolicyType >::MaxIterations().
MaxIterations() [2/2]
size_t& MaxIterations () inline
Modify the maximum number of iterations (0 indicates no limit).
Definition at line 149 of file minibatch_sgd.hpp.
Optimize()
double Optimize (DecomposableFunctionType & function, arma::mat & iterate)
Optimize the given function using mini-batch SGD.
The given starting point will be modified to store the finishing point of the algorithm, and the final objective value is returned.
Template Parameters
DecomposableFunctionType Type of the function to be optimized.
Parameters
function Function to optimize.
iterate Starting point (will be modified).
resetPolicy Flag indicating whether update policy should be reset before running optimization.
Returns
Objective value of the final point.
ResetPolicy() [1/2]
bool ResetPolicy () const inline
Get whether or not the update policy parameters are reset before Optimize call.
Definition at line 163 of file minibatch_sgd.hpp.
ResetPolicy() [2/2]
bool& ResetPolicy () inline
Modify whether or not the update policy parameters are reset before Optimize call.
Definition at line 166 of file minibatch_sgd.hpp.
Shuffle() [1/2]
bool Shuffle () const inline
Get whether or not the individual functions are shuffled.
Definition at line 157 of file minibatch_sgd.hpp.
Referenced by SGDR< UpdatePolicyType >::Shuffle(), and SnapshotSGDR< UpdatePolicyType >::Shuffle().
Shuffle() [2/2]
bool& Shuffle () inline
Modify whether or not the individual functions are shuffled.
Definition at line 159 of file minibatch_sgd.hpp.
StepSize() [1/2]
double StepSize () const inline
Get the step size.
Definition at line 142 of file minibatch_sgd.hpp.
Referenced by SGDR< UpdatePolicyType >::StepSize(), and SnapshotSGDR< UpdatePolicyType >::StepSize().
StepSize() [2/2]
double& StepSize () inline
Modify the step size.
Definition at line 144 of file minibatch_sgd.hpp.
Tolerance() [1/2]
double Tolerance () const inline
Get the tolerance for termination.
Definition at line 152 of file minibatch_sgd.hpp.
Referenced by SGDR< UpdatePolicyType >::Tolerance(), and SnapshotSGDR< UpdatePolicyType >::Tolerance().
Tolerance() [2/2]
double& Tolerance () inline
Modify the tolerance for termination.
Definition at line 154 of file minibatch_sgd.hpp.
UpdatePolicy() [1/2]
UpdatePolicyType UpdatePolicy () const inline
Get the update policy.
Definition at line 169 of file minibatch_sgd.hpp.
UpdatePolicy() [2/2]
UpdatePolicyType& UpdatePolicy () inline
Modify the update policy.
Definition at line 171 of file minibatch_sgd.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/minibatch_sgd/minibatch_sgd.hpp