main
about
docs
get help
github
TestOption< N > Class Template Reference
A static object whose constructor registers a parameter with the CLI class.
Public Member Functions
TestOption (const N defaultValue, const std::string &identifier, const std::string &description, const std::string &alias, const std::string &cppName, const bool required=false, const bool input=true, const bool noTranspose=false)
Construct an Option object.
Detailed Description
template
<
typename
N
>
class mlpack::bindings::tests::TestOption< N >
A static object whose constructor registers a parameter with the CLI class.
This should not be used outside of CLI itself, and you should use the PARAM_FLAG(), PARAM_DOUBLE(), PARAM_INT(), PARAM_STRING(), or other similar macros to declare these objects instead of declaring them directly.
See also
core/util/cli.hpp, mlpack::CLI
Definition at line 38 of file test_option.hpp.
Constructor & Destructor Documentation
TestOption()
TestOption (const N defaultValue, const std::string & identifier, const std::string & description, const std::string & alias, const std::string & cppName, const bool required = false, const bool input = true, const bool noTranspose = false) inline
Construct an Option object.
When constructed, it will register itself with CLI.
Parameters
defaultValue Default value this parameter will be initialized to (for flags, this should be false, for instance).
identifier The name of the option (no dashes in front; for –help, we would pass "help").
description A short string describing the option.
alias Short name of the parameter. "" for no alias.
cppName Name of the C++ type of this parameter (i.e. "int").
required Whether or not the option is required at runtime.
input Whether or not the option is an input option.
noTranspose If the parameter is a matrix and this is true, then the matrix will not be transposed on loading.
Definition at line 57 of file test_option.hpp.
References CLI::Add(), ParamData::alias, CLI::ClearSettings(), ParamData::cppType, ParamData::desc, CLI::functionMap, CLI::GetSingleton(), ParamData::input, ParamData::loaded, ParamData::name, ParamData::noTranspose, ParamData::required, CLI::RestoreSettings(), CLI::SetPassed(), CLI::StoreSettings(), string(), ParamData::tname, TYPENAME, ParamData::value, and ParamData::wasPassed.
The documentation for this class was generated from the following file:
src/mlpack/bindings/tests/test_option.hpp