main
about
docs
get help
github
src/mlpack/methods/CMakeLists.txt File Reference
Functions
macro (add_cli_executable name) if(BUILD_CLI_EXECUTABLES) add_executable(mlpack_$
Function Documentation
macro()
macro (add_cli_executable name)
Definition at line 4 of file CMakeLists.txt.
References add_subdirectory(), BINDING_TYPE, BINDING_TYPE_CLI, endif(), and install().