main
about
docs
get help
github
mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct Struct Reference
The X tree requires that the tree records it's "split history".
Public Member Functions
SplitHistoryStruct (int dim)
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Public Attributes
std::vector< bool > history
int lastDimension
Detailed Description
template
<
typename
MetricType
=
metric::EuclideanDistance
,
typename
StatisticType
=
EmptyStatistic
,
typename
MatType
=
arma::mat
,
typename
SplitType
=
RTreeSplit
,
typename
DescentType
=
RTreeDescentHeuristic
>
struct mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct
The X tree requires that the tree records it's "split history".
To make this easy, we use the following structure.
Definition at line 61 of file rectangle_tree.hpp.
Constructor & Destructor Documentation
SplitHistoryStruct()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat,typenameSplitType=RTreeSplit,typenameDescentType=RTreeDescentHeuristic> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::SplitHistoryStruct (int dim) inline
Definition at line 66 of file rectangle_tree.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::Serialize().
Member Function Documentation
Serialize()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat,typenameSplitType=RTreeSplit,typenameDescentType=RTreeDescentHeuristic> template<typenameArchive> void mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::Serialize (Archive & ar, const unsigned int) inline
Definition at line 73 of file rectangle_tree.hpp.
References mlpack::data::CreateNVP(), and mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::SplitHistoryStruct().
Member Data Documentation
history
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat,typenameSplitType=RTreeSplit,typenameDescentType=RTreeDescentHeuristic> std::vector<bool> mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::history
Definition at line 64 of file rectangle_tree.hpp.
lastDimension
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat,typenameSplitType=RTreeSplit,typenameDescentType=RTreeDescentHeuristic> int mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType >::SplitHistoryStruct::lastDimension
Definition at line 63 of file rectangle_tree.hpp.
The documentation for this struct was generated from the following file:
src/mlpack/core/tree/rectangle_tree/rectangle_tree.hpp