mlpack: mlpack::tree::RTreeSplit< TreeType > Class Template Reference
mlpack::tree::RTreeSplit< TreeType > Class Template Reference
A Rectangle Tree has new points inserted at the bottom.
Public Member Functions
RTreeSplit ()
Default constructor.
RTreeSplit (const TreeType *)
Construct this with the specified node.
RTreeSplit (const TreeType &)
Create a copy of the other split.
template<typename Archive >
void Serialize (Archive &, const unsigned int)
Serialize the split.
void SplitLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a leaf node using the "default" algorithm.
bool SplitNonLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a non-leaf node using the "default" algorithm.
Static Private Member Functions
static void AssignNodeDestNode (TreeType *oldTree, TreeType *treeOne, TreeType *treeTwo, const int intI, const int intJ)
Assign nodes to the two new nodes.
static void AssignPointDestNode (TreeType *oldTree, TreeType *treeOne, TreeType *treeTwo, const int intI, const int intJ)
Assign points to the two new nodes.
static void GetBoundSeeds (const TreeType *tree, int &i, int &j)
Get the seeds for splitting a non-leaf node.
static void GetPointSeeds (const TreeType *tree, int &i, int &j)
Get the seeds for splitting a leaf node.
static void InsertNodeIntoTree (TreeType *destTree, TreeType *srcNode)
Insert a node into another node.
Detailed Description
template<typename TreeType>
class mlpack::tree::RTreeSplit< TreeType >
A Rectangle Tree has new points inserted at the bottom.
When these nodes overflow, we split them, moving up the tree and splitting nodes as necessary.
Definition at line 29 of file r_tree_split.hpp.
Constructor & Destructor Documentation
template<typename TreeType > mlpack::tree::RTreeSplit< TreeType >::RTreeSplit () inline
Default constructor.
Definition at line 33 of file r_tree_split.hpp.
template<typename TreeType > mlpack::tree::RTreeSplit< TreeType >::RTreeSplit (const TreeType *) inline
Construct this with the specified node.
Definition at line 36 of file r_tree_split.hpp.
template<typename TreeType > mlpack::tree::RTreeSplit< TreeType >::RTreeSplit (const TreeType &) inline
Create a copy of the other split.
Definition at line 39 of file r_tree_split.hpp.
References mlpack::tree::RTreeSplit< TreeType >::AssignNodeDestNode(), mlpack::tree::RTreeSplit< TreeType >::AssignPointDestNode(), mlpack::tree::RTreeSplit< TreeType >::GetBoundSeeds(), mlpack::tree::RTreeSplit< TreeType >::GetPointSeeds(), mlpack::tree::RTreeSplit< TreeType >::InsertNodeIntoTree(), mlpack::tree::RTreeSplit< TreeType >::SplitLeafNode(), and mlpack::tree::RTreeSplit< TreeType >::SplitNonLeafNode().
Member Function Documentation
template<typename TreeType > static void mlpack::tree::RTreeSplit< TreeType >::AssignNodeDestNode (TreeType * oldTree, TreeType * treeOne, TreeType * treeTwo, const int intI, const int intJ) static private
Assign nodes to the two new nodes.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > static void mlpack::tree::RTreeSplit< TreeType >::AssignPointDestNode (TreeType * oldTree, TreeType * treeOne, TreeType * treeTwo, const int intI, const int intJ) static private
Assign points to the two new nodes.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > static void mlpack::tree::RTreeSplit< TreeType >::GetBoundSeeds (const TreeType * tree, int & i, int & j) static private
Get the seeds for splitting a non-leaf node.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > static void mlpack::tree::RTreeSplit< TreeType >::GetPointSeeds (const TreeType * tree, int & i, int & j) static private
Get the seeds for splitting a leaf node.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > static void mlpack::tree::RTreeSplit< TreeType >::InsertNodeIntoTree (TreeType * destTree, TreeType * srcNode) static private
Insert a node into another node.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > template<typename Archive > void mlpack::tree::RTreeSplit< TreeType >::Serialize (Archive & , const unsigned int) inline
Serialize the split.
Definition at line 92 of file r_tree_split.hpp.
template<typename TreeType > void mlpack::tree::RTreeSplit< TreeType >::SplitLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a leaf node using the "default" algorithm.
If necessary, this split will propagate upwards through the tree.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
template<typename TreeType > bool mlpack::tree::RTreeSplit< TreeType >::SplitNonLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a non-leaf node using the "default" algorithm.
If this is a root node, the tree increases in depth.
Referenced by mlpack::tree::RTreeSplit< TreeType >::RTreeSplit().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/rectangle_tree/r_tree_split.hpp