main
about
docs
get help
github
boost::serialization Namespace Reference
Namespaces
stl
Functions
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void load (Archive &ar, std::unordered_map< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int)
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void load (Archive &ar, std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int)
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void save (Archive &ar, const std::unordered_map< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int)
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void save (Archive &ar, const std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int)
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void serialize (Archive &ar, std::unordered_map< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int file_version)
template
<
class
Archive
,
class
Key
,
class
HashFcn
,
class
EqualKey
,
class
Allocator
>
void serialize (Archive &ar, std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > &t, const unsigned int file_version)
template
<
typename
Archive
,
typename
T
>
void serialize (Archive &ar, mlpack::data::PointerShim< T > &t, const BOOST_PFTO unsigned int version)
Catch a call to serialize() with a PointerShim, and call the Serialize() function directly.
Function Documentation
load() [1/2]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::load (Archive & ar, std::unordered_map< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int) inline
Definition at line 121 of file unordered_map.hpp.
References boost::serialization::stl::load_unordered_collection().
load() [2/2]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::load (Archive & ar, std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int) inline
Definition at line 191 of file unordered_map.hpp.
References boost::serialization::stl::load_unordered_collection().
save() [1/2]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::save (Archive & ar, const std::unordered_map< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int) inline
Definition at line 99 of file unordered_map.hpp.
References boost::serialization::stl::save_unordered_collection().
save() [2/2]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::save (Archive & ar, const std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int) inline
Definition at line 169 of file unordered_map.hpp.
References boost::serialization::stl::save_unordered_collection().
serialize() [1/3]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::serialize (Archive & ar, std::unordered_map< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int file_version) inline
Definition at line 151 of file unordered_map.hpp.
serialize() [2/3]
template<classArchive,classKey,classHashFcn,classEqualKey,classAllocator> void boost::serialization::serialize (Archive & ar, std::unordered_multimap< Key, HashFcn, EqualKey, Allocator > & t, const unsigned int file_version) inline
Definition at line 221 of file unordered_map.hpp.
serialize() [3/3]
template<typenameArchive,typenameT> void boost::serialization::serialize (Archive & ar, mlpack::data::PointerShim< T > & t, const BOOST_PFTO unsigned int version) inline
Catch a call to serialize() with a PointerShim, and call the Serialize() function directly.
Definition at line 501 of file serialization_shim.hpp.