mlpack: mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct Struct Reference
mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct Struct Reference
The X tree requires that the tree records it's "split history".
Public Member Functions
SplitHistoryStruct (int dim)
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Public Attributes
std::vector< bool > history
int lastDimension
Detailed Description
template<typename TreeType>
struct mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct
The X tree requires that the tree records it's "split history".
To make this easy, we use the following structure.
Definition at line 68 of file x_tree_split.hpp.
Constructor & Destructor Documentation
template<typename TreeType > mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::SplitHistoryStruct (int dim) inline
Definition at line 73 of file x_tree_split.hpp.
Referenced by mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::Serialize().
Member Function Documentation
template<typename TreeType > template<typename Archive > void mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::Serialize (Archive & ar, const unsigned int) inline
Definition at line 80 of file x_tree_split.hpp.
References mlpack::data::CreateNVP(), and mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::SplitHistoryStruct().
Referenced by mlpack::tree::XTreeSplit< TreeType >::SplitHistory().
Member Data Documentation
template<typename TreeType > std::vector<bool> mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::history
Definition at line 71 of file x_tree_split.hpp.
template<typename TreeType > int mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::lastDimension
Definition at line 70 of file x_tree_split.hpp.
The documentation for this struct was generated from the following file:
src/mlpack/core/tree/rectangle_tree/x_tree_split.hpp