main
about
docs
get help
github
mlpack::math::Range Class Reference
Simple real-valued range.
Public Member Functions
Range ()
The upper bound.
Range (const double point)
Range (const double lo, const double hi)
Initializes to specified range.
bool Contains (const double d) const
Determines if a point is contained within the range.
bool Contains (const Range &r) const
Determines if another range overlaps with this one.
double Hi () const
Get the upper bound.
double & Hi ()
Modify the upper bound.
double Lo () const
Get the lower bound.
double & Lo ()
Modify the lower bound.
double Mid () const
Gets the midpoint of this range.
Range operator & (const Range &rhs) const
Shrinks this range to be the overlap with another range; this makes an empty set if there is no overlap.
Range & operator &= (const Range &rhs)
Shrinks this range to be the overlap with another range; this makes an empty set if there is no overlap.
bool operator!= (const Range &rhs) const
Compare with another range for strict equality.
Range operator* (const double d) const
Scale the bounds by the given double.
Range & operator*= (const double d)
Scale the bounds by the given double.
bool operator< (const Range &rhs) const
Compare with another range.
bool operator== (const Range &rhs) const
Compare with another range for strict equality.
bool operator> (const Range &rhs) const
Compare with another range.
Range operator| (const Range &rhs) const
Expands this range to include another range.
Range & operator|= (const Range &rhs)
Expands this range to include another range.
std::string ToString () const
Returns a string representation of an object.
double Width () const
Gets the span of the range (hi - lo).
Private Attributes
double hi
The lower bound.
double lo
Friends
Range operator* (const double d, const Range &r)
Scale the bounds by the given double.
Detailed Description
Simple real-valued range.
It contains an upper and lower bound.
Definition at line 31 of file range.hpp.
Constructor & Destructor Documentation
Range() [1/3]
mlpack::math::Range::Range () inline
The upper bound.
Initialize to an empty set (where lo > hi).
Range() [2/3]
mlpack::math::Range::Range (const double point) inline
Range() [3/3]
mlpack::math::Range::Range (const double lo, const double hi) inline
Initializes to specified range.
Parameters
lo Lower bound of the range.
hi Upper bound of the range.
Member Function Documentation
Contains() [1/2]
bool mlpack::math::Range::Contains (const double d) const inline
Determines if a point is contained within the range.
Parameters
d Point to check.
Referenced by Hi().
Contains() [2/2]
bool mlpack::math::Range::Contains (const Range & r) const inline
Determines if another range overlaps with this one.
Parameters
r Other range.
Returns
true if ranges overlap at all.
Hi() [1/2]
double mlpack::math::Range::Hi () const inline
Get the upper bound.
Definition at line 63 of file range.hpp.
References hi.
Hi() [2/2]
double& mlpack::math::Range::Hi () inline
Modify the upper bound.
Definition at line 65 of file range.hpp.
References Contains(), hi, Mid(), operator &(), operator &=(), operator!=(), operator*(), operator*=(), operator<(), operator==(), operator>(), operator|(), operator|=(), ToString(), and Width().
Lo() [1/2]
double mlpack::math::Range::Lo () const inline
Get the lower bound.
Definition at line 58 of file range.hpp.
References lo.
Lo() [2/2]
double& mlpack::math::Range::Lo () inline
Modify the lower bound.
Definition at line 60 of file range.hpp.
References lo.
Mid()
double mlpack::math::Range::Mid () const inline
Gets the midpoint of this range.
Referenced by Hi().
operator &()
Range mlpack::math::Range::operator& (const Range & rhs) const inline
Shrinks this range to be the overlap with another range; this makes an empty set if there is no overlap.
Parameters
rhs Other range.
Referenced by Hi().
operator &=()
Range& mlpack::math::Range::operator&= (const Range & rhs) inline
Shrinks this range to be the overlap with another range; this makes an empty set if there is no overlap.
Parameters
rhs Other range.
Referenced by Hi().
operator!=()
bool mlpack::math::Range::operator!= (const Range & rhs) const inline
Compare with another range for strict equality.
Parameters
rhs Other range.
Referenced by Hi().
operator*()
Range mlpack::math::Range::operator* (const double d) const inline
Scale the bounds by the given double.
Parameters
d Scaling factor.
Referenced by Hi().
operator*=()
Range& mlpack::math::Range::operator*= (const double d) inline
Scale the bounds by the given double.
Parameters
d Scaling factor.
Referenced by Hi().
operator<()
bool mlpack::math::Range::operator< (const Range & rhs) const inline
Compare with another range.
For Range objects x and y, x < y means that x is strictly less than y and does not overlap at all.
Parameters
rhs Other range.
Referenced by Hi().
operator==()
bool mlpack::math::Range::operator== (const Range & rhs) const inline
Compare with another range for strict equality.
Parameters
rhs Other range.
Referenced by Hi().
operator>()
bool mlpack::math::Range::operator> (const Range & rhs) const inline
Compare with another range.
For Range objects x and y, x < y means that x is strictly less than y and does not overlap at all.
Parameters
rhs Other range.
Referenced by Hi().
operator|()
Range mlpack::math::Range::operator| (const Range & rhs) const inline
Expands this range to include another range.
Parameters
rhs Range to include.
Referenced by Hi().
operator|=()
Range& mlpack::math::Range::operator|= (const Range & rhs) inline
Expands this range to include another range.
Parameters
rhs Range to include.
Referenced by Hi().
ToString()
std::string mlpack::math::Range::ToString () const inline
Returns a string representation of an object.
Referenced by Hi().
Width()
double mlpack::math::Range::Width () const inline
Gets the span of the range (hi - lo).
Referenced by Hi().
Friends And Related Function Documentation
operator*
Range operator* (const double d, const Range & r) friend
Scale the bounds by the given double.
Parameters
d Scaling factor.
Member Data Documentation
hi
double mlpack::math::Range::hi private
The lower bound.
Definition at line 35 of file range.hpp.
Referenced by Hi().
lo
double mlpack::math::Range::lo private
Definition at line 34 of file range.hpp.
Referenced by Lo().
The documentation for this class was generated from the following file:
/var/www/www.mlpack.org/mlpack-1.0.5/src/mlpack/core/math/range.hpp