main
about
docs
get help
github
mlpack::gmm::GMM< FittingType > Class Template Reference
A Gaussian Mixture Model (GMM).
Public Member Functions
GMM ()
Create an empty Gaussian Mixture Model, with zero gaussians.
GMM (const size_t gaussians, const size_t dimensionality)
Create a GMM with the given number of Gaussians, each of which have the specified dimensionality.
GMM (const size_t gaussians, const size_t dimensionality, FittingType &fitter)
Create a GMM with the given number of Gaussians, each of which have the specified dimensionality.
GMM (const std::vector< arma::vec > &means, const std::vector< arma::mat > &covariances, const arma::vec &weights)
Create a GMM with the given means, covariances, and weights.
GMM (const std::vector< arma::vec > &means, const std::vector< arma::mat > &covariances, const arma::vec &weights, FittingType &fitter)
Create a GMM with the given means, covariances, and weights, and use the given initialized FittingType class.
template
<
typename
OtherFittingType
>
GMM (const GMM< OtherFittingType > &other)
Copy constructor for GMMs which use different fitting types.
GMM (const GMM &other)
Copy constructor for GMMs using the same fitting type.
void Classify (const arma::mat &observations, arma::Col< size_t > &labels) const
Classify the given observations as being from an individual component in this GMM.
const std::vector< arma::mat > & Covariances () const
Return a const reference to the vector of covariance matrices (sigma).
std::vector< arma::mat > & Covariances ()
Return a reference to the vector of covariance matrices (sigma).
size_t Dimensionality () const
Return the dimensionality of the model.
size_t & Dimensionality ()
Modify the dimensionality of the model.
double Estimate (const arma::mat &observations, const size_t trials=1)
Estimate the probability distribution directly from the given observations, using the given algorithm in the FittingType class to fit the data.
double Estimate (const arma::mat &observations, const arma::vec &probabilities, const size_t trials=1)
Estimate the probability distribution directly from the given observations, taking into account the probability of each observation actually being from this distribution, and using the given algorithm in the FittingType class to fit the data.
const FittingType & Fitter () const
Return a const reference to the fitting type.
FittingType & Fitter ()
Return a reference to the fitting type.
size_t Gaussians () const
Return the number of gaussians in the model.
size_t & Gaussians ()
Modify the number of gaussians in the model.
void Load (const std::string &filename)
Load a GMM from an XML file.
const std::vector< arma::vec > & Means () const
Return a const reference to the vector of means (mu).
std::vector< arma::vec > & Means ()
Return a reference to the vector of means (mu).
template
<
typename
OtherFittingType
>
GMM & operator= (const GMM< OtherFittingType > &other)
Copy operator for GMMs which use different fitting types.
GMM & operator= (const GMM &other)
Copy operator for GMMs which use the same fitting type.
double Probability (const arma::vec &observation) const
Return the probability that the given observation came from this distribution.
double Probability (const arma::vec &observation, const size_t component) const
Return the probability that the given observation came from the given Gaussian component in this distribution.
arma::vec Random () const
Return a randomly generated observation according to the probability distribution defined by this object.
void Save (const std::string &filename) const
Save a GMM to an XML file.
const arma::vec & Weights () const
Return a const reference to the a priori weights of each Gaussian.
arma::vec & Weights ()
Return a reference to the a priori weights of each Gaussian.
Private Member Functions
double LogLikelihood (const arma::mat &dataPoints, const std::vector< arma::vec > &means, const std::vector< arma::mat > &covars, const arma::vec &weights) const
This function computes the loglikelihood of the given model.
Private Attributes
std::vector< arma::mat > covariances
Vector of covariances; one for each Gaussian.
size_t dimensionality
The dimensionality of the model.
FittingType & fitter
Reference to the fitting object we should use.
size_t gaussians
The number of Gaussians in the model.
FittingType localFitter
Locally-stored fitting object; in case the user did not pass one.
std::vector< arma::vec > means
Vector of means; one for each Gaussian.
arma::vec weights
Vector of a priori weights for each Gaussian.
Detailed Description
template<typename FittingType = EMFit<>> class mlpack::gmm::GMM< FittingType >
A Gaussian Mixture Model (GMM).
This class uses maximum likelihood loss functions to estimate the parameters of the GMM on a given dataset via the given fitting mechanism, defined by the FittingType template parameter. The GMM can be trained using normal data, or data with probabilities of being from this GMM (see GMM::Estimate() for more information).
The FittingType template class must provide a way for the GMM to train on data. It must provide the following two functions:
void Estimate(const arma::mat& observations,
              std::vector<arma::vec>& means,
              std::vector<arma::mat>& covariances,
              arma::vec& weights);
void Estimate(const arma::mat& observations,
              const arma::vec& probabilities,
              std::vector<arma::vec>& means,
              std::vector<arma::mat>& covariances,
              arma::vec& weights);
These functions should produce a trained GMM from the given observations and probabilities. These may modify the size of the model (by increasing the size of the mean and covariance vectors as well as the weight vectors), but the method should expect that these vectors are already set to the size of the GMM as specified in the constructor.
For a sample implementation, see the EMFit class; this class uses the EM algorithm to train a GMM, and is the default fitting type.
The GMM, once trained, can be used to generate random points from the distribution and estimate the probability of points being from the distribution. The parameters of the GMM can be obtained through the accessors and mutators.
Example use:
// Set up a mixture of 5 gaussians in a 4-dimensional space (uses the default
// EM fitting mechanism).
GMM<> g(5, 4);
// Train the GMM given the data observations.
g.Estimate(data);
// Get the probability of 'observation' being observed from this GMM.
double probability = g.Probability(observation);
// Get a random observation from the GMM.
arma::vec observation = g.Random();
Definition at line 89 of file gmm.hpp.
Constructor & Destructor Documentation
GMM() [1/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM () inline
Create an empty Gaussian Mixture Model, with zero gaussians.
Definition at line 107 of file gmm.hpp.
References mlpack::Log::Debug.
Referenced by mlpack::gmm::GMM< FittingType >::GMM().
GMM() [2/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM (const size_t gaussians, const size_t dimensionality) inline
Create a GMM with the given number of Gaussians, each of which have the specified dimensionality.
Parameters
gaussians Number of Gaussians in this GMM.
dimensionality Dimensionality of each Gaussian.
Definition at line 127 of file gmm.hpp.
GMM() [3/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM (const size_t gaussians, const size_t dimensionality, FittingType & fitter) inline
Create a GMM with the given number of Gaussians, each of which have the specified dimensionality.
Also, pass in an initialized FittingType class; this is useful in cases where the FittingType class needs to store some state.
Parameters
gaussians Number of Gaussians in this GMM.
dimensionality Dimensionality of each Gaussian.
fitter Initialized fitting mechanism.
Definition at line 146 of file gmm.hpp.
GMM() [4/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM (const std::vector< arma::vec > & means, const std::vector< arma::mat > & covariances, const arma::vec & weights) inline
Create a GMM with the given means, covariances, and weights.
Parameters
means Means of the model.
covariances Covariances of the model.
weights Weights of the model.
Definition at line 163 of file gmm.hpp.
GMM() [5/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM (const std::vector< arma::vec > & means, const std::vector< arma::mat > & covariances, const arma::vec & weights, FittingType & fitter) inline
Create a GMM with the given means, covariances, and weights, and use the given initialized FittingType class.
This is useful in cases where the FittingType class needs to store some state.
Parameters
means Means of the model.
covariances Covariances of the model.
weights Weights of the model.
Definition at line 183 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::GMM(), mlpack::gmm::GMM< FittingType >::Load(), mlpack::gmm::GMM< FittingType >::operator=(), and mlpack::gmm::GMM< FittingType >::Save().
GMM() [6/7]
template<typename FittingType = EMFit<>> template<typenameOtherFittingType> mlpack::gmm::GMM< FittingType >::GMM (const GMM< OtherFittingType > & other)
Copy constructor for GMMs which use different fitting types.
GMM() [7/7]
template<typename FittingType = EMFit<>> mlpack::gmm::GMM< FittingType >::GMM (const GMM< FittingType > & other)
Copy constructor for GMMs using the same fitting type.
This also copies the fitter.
Member Function Documentation
Classify()
template<typename FittingType = EMFit<>> void mlpack::gmm::GMM< FittingType >::Classify (const arma::mat & observations, arma::Col< size_t > & labels) const
Classify the given observations as being from an individual component in this GMM.
The resultant classifications are stored in the 'labels' object, and each label will be between 0 and (Gaussians() - 1). Supposing that a point was classified with label 2, and that our GMM object was called 'gmm', one could access the relevant Gaussian distribution as follows:
arma::vec mean = gmm.Means()[2];
arma::mat covariance = gmm.Covariances()[2];
double priorWeight = gmm.Weights()[2];
Parameters
observations List of observations to classify.
labels Object which will be filled with labels.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
Covariances() [1/2]
template<typename FittingType = EMFit<>> const std::vector<arma::mat>& mlpack::gmm::GMM< FittingType >::Covariances () const inline
Return a const reference to the vector of covariance matrices (sigma).
Definition at line 251 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::covariances.
Covariances() [2/2]
template<typename FittingType = EMFit<>> std::vector<arma::mat>& mlpack::gmm::GMM< FittingType >::Covariances () inline
Return a reference to the vector of covariance matrices (sigma).
Definition at line 253 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::covariances.
Dimensionality() [1/2]
template<typename FittingType = EMFit<>> size_t mlpack::gmm::GMM< FittingType >::Dimensionality () const inline
Return the dimensionality of the model.
Definition at line 240 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::dimensionality.
Dimensionality() [2/2]
template<typename FittingType = EMFit<>> size_t& mlpack::gmm::GMM< FittingType >::Dimensionality () inline
Modify the dimensionality of the model.
Careful! You will have to update each mean and covariance matrix yourself.
Definition at line 243 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::dimensionality.
Estimate() [1/2]
template<typename FittingType = EMFit<>> double mlpack::gmm::GMM< FittingType >::Estimate (const arma::mat & observations, const size_t trials = 1)
Estimate the probability distribution directly from the given observations, using the given algorithm in the FittingType class to fit the data.
The fitting will be performed 'trials' times; from these trials, the model with the greatest log-likelihood will be selected. By default, only one trial is performed. The log-likelihood of the best fitting is returned.
Template Parameters
FittingType The type of fitting method which should be used (EMFit<> is suggested).
Parameters
observations Observations of the model.
trials Number of trials to perform; the model in these trials with the greatest log-likelihood will be selected.
Returns
The log-likelihood of the best fit.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
Estimate() [2/2]
template<typename FittingType = EMFit<>> double mlpack::gmm::GMM< FittingType >::Estimate (const arma::mat & observations, const arma::vec & probabilities, const size_t trials = 1)
Estimate the probability distribution directly from the given observations, taking into account the probability of each observation actually being from this distribution, and using the given algorithm in the FittingType class to fit the data.
The fitting will be performed 'trials' times; from these trials, the model with the greatest log-likelihood will be selected. By default, only one trial is performed. The log-likelihood of the best fitting is returned.
Parameters
observations Observations of the model.
probabilities Probability of each observation being from this distribution.
trials Number of trials to perform; the model in these trials with the greatest log-likelihood will be selected.
Returns
The log-likelihood of the best fit.
Fitter() [1/2]
template<typename FittingType = EMFit<>> const FittingType& mlpack::gmm::GMM< FittingType >::Fitter () const inline
Return a const reference to the fitting type.
Definition at line 261 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::fitter.
Fitter() [2/2]
template<typename FittingType = EMFit<>> FittingType& mlpack::gmm::GMM< FittingType >::Fitter () inline
Return a reference to the fitting type.
Definition at line 263 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::Classify(), mlpack::gmm::GMM< FittingType >::Estimate(), mlpack::gmm::GMM< FittingType >::fitter, mlpack::gmm::GMM< FittingType >::LogLikelihood(), mlpack::gmm::GMM< FittingType >::Probability(), and mlpack::gmm::GMM< FittingType >::Random().
Gaussians() [1/2]
template<typename FittingType = EMFit<>> size_t mlpack::gmm::GMM< FittingType >::Gaussians () const inline
Return the number of gaussians in the model.
Definition at line 234 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::gaussians.
Gaussians() [2/2]
template<typename FittingType = EMFit<>> size_t& mlpack::gmm::GMM< FittingType >::Gaussians () inline
Modify the number of gaussians in the model.
Careful! You will have to resize the means, covariances, and weights yourself.
Definition at line 237 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::gaussians.
Load()
template<typename FittingType = EMFit<>> void mlpack::gmm::GMM< FittingType >::Load (const std::string & filename)
Load a GMM from an XML file.
The format of the XML file should be the same as is generated by the Save() method.
Parameters
filename Name of XML file containing model to be loaded.
Referenced by mlpack::gmm::GMM< FittingType >::GMM().
LogLikelihood()
template<typename FittingType = EMFit<>> double mlpack::gmm::GMM< FittingType >::LogLikelihood (const arma::mat & dataPoints, const std::vector< arma::vec > & means, const std::vector< arma::mat > & covars, const arma::vec & weights) const private
This function computes the loglikelihood of the given model.
This function is used by GMM::Estimate().
Parameters
dataPoints Observations to calculate the likelihood for.
means Means of the given mixture model.
covars Covariances of the given mixture model.
weights Weights of the given mixture model.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
Means() [1/2]
template<typename FittingType = EMFit<>> const std::vector<arma::vec>& mlpack::gmm::GMM< FittingType >::Means () const inline
Return a const reference to the vector of means (mu).
Definition at line 246 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::means.
Means() [2/2]
template<typename FittingType = EMFit<>> std::vector<arma::vec>& mlpack::gmm::GMM< FittingType >::Means () inline
Return a reference to the vector of means (mu).
Definition at line 248 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::means.
operator=() [1/2]
template<typename FittingType = EMFit<>> template<typenameOtherFittingType> GMM& mlpack::gmm::GMM< FittingType >::operator= (const GMM< OtherFittingType > & other)
Copy operator for GMMs which use different fitting types.
Referenced by mlpack::gmm::GMM< FittingType >::GMM().
operator=() [2/2]
template<typename FittingType = EMFit<>> GMM& mlpack::gmm::GMM< FittingType >::operator= (const GMM< FittingType > & other)
Copy operator for GMMs which use the same fitting type.
This also copies the fitter.
Probability() [1/2]
template<typename FittingType = EMFit<>> double mlpack::gmm::GMM< FittingType >::Probability (const arma::vec & observation) const
Return the probability that the given observation came from this distribution.
Parameters
observation Observation to evaluate the probability of.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
Probability() [2/2]
template<typename FittingType = EMFit<>> double mlpack::gmm::GMM< FittingType >::Probability (const arma::vec & observation, const size_t component) const
Return the probability that the given observation came from the given Gaussian component in this distribution.
Parameters
observation Observation to evaluate the probability of.
component Index of the component of the GMM to be considered.
Random()
template<typename FittingType = EMFit<>> arma::vec mlpack::gmm::GMM< FittingType >::Random () const
Return a randomly generated observation according to the probability distribution defined by this object.
Returns
Random observation from this GMM.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
Save()
template<typename FittingType = EMFit<>> void mlpack::gmm::GMM< FittingType >::Save (const std::string & filename) const
Save a GMM to an XML file.
Parameters
filename Name of XML file to write to.
Referenced by mlpack::gmm::GMM< FittingType >::GMM().
Weights() [1/2]
template<typename FittingType = EMFit<>> const arma::vec& mlpack::gmm::GMM< FittingType >::Weights () const inline
Return a const reference to the a priori weights of each Gaussian.
Definition at line 256 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::weights.
Weights() [2/2]
template<typename FittingType = EMFit<>> arma::vec& mlpack::gmm::GMM< FittingType >::Weights () inline
Return a reference to the a priori weights of each Gaussian.
Definition at line 258 of file gmm.hpp.
References mlpack::gmm::GMM< FittingType >::weights.
Member Data Documentation
covariances
template<typename FittingType = EMFit<>> std::vector<arma::mat> mlpack::gmm::GMM< FittingType >::covariances private
Vector of covariances; one for each Gaussian.
Definition at line 99 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Covariances().
dimensionality
template<typename FittingType = EMFit<>> size_t mlpack::gmm::GMM< FittingType >::dimensionality private
The dimensionality of the model.
Definition at line 95 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Dimensionality().
fitter
template<typename FittingType = EMFit<>> FittingType& mlpack::gmm::GMM< FittingType >::fitter private
Reference to the fitting object we should use.
Definition at line 368 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Fitter().
gaussians
template<typename FittingType = EMFit<>> size_t mlpack::gmm::GMM< FittingType >::gaussians private
The number of Gaussians in the model.
Definition at line 93 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Gaussians().
localFitter
template<typename FittingType = EMFit<>> FittingType mlpack::gmm::GMM< FittingType >::localFitter private
Locally-stored fitting object; in case the user did not pass one.
Definition at line 365 of file gmm.hpp.
means
template<typename FittingType = EMFit<>> std::vector<arma::vec> mlpack::gmm::GMM< FittingType >::means private
Vector of means; one for each Gaussian.
Definition at line 97 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Means().
weights
template<typename FittingType = EMFit<>> arma::vec mlpack::gmm::GMM< FittingType >::weights private
Vector of a priori weights for each Gaussian.
Definition at line 101 of file gmm.hpp.
Referenced by mlpack::gmm::GMM< FittingType >::Weights().
The documentation for this class was generated from the following file:
/var/www/www.mlpack.org/mlpack-1.0.5/src/mlpack/methods/gmm/gmm.hpp