main
about
docs
get help
github
mlpack::bound::HRectBound< MetricType, ElemType > Class Template Reference
Hyper-rectangle bound for an L-metric.
Public Member Functions
HRectBound ()
Empty constructor; creates a bound of dimensionality 0.
HRectBound (const size_t dimension)
Initializes to specified dimensionality with each dimension the empty set.
HRectBound (const HRectBound &other)
Copy constructor; necessary to prevent memory leaks.
HRectBound (HRectBound &&other)
Move constructor: take possession of another bound's information.
~HRectBound ()
Destructor: clean up memory.
void Center (arma::Col< ElemType > &center) const
Calculates the center of the range, placing it into the given vector.
void Clear ()
Resets all dimensions to the empty set (so that this bound contains nothing).
template
<
typename
VecType
>
bool Contains (const VecType &point) const
Determines if a point is within this bound.
bool Contains (const HRectBound &bound) const
Determines if this bound partially contains a bound.
ElemType Diameter () const
Returns the diameter of the hyperrectangle (that is, the longest diagonal).
size_t Dim () const
Gets the dimensionality.
template
<
typename
VecType
>
ElemType MaxDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >> *=0) const
Calculates maximum bound-to-point squared distance.
ElemType MaxDistance (const HRectBound &other) const
Computes maximum distance.
template
<
typename
VecType
>
ElemType MinDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >> *=0) const
Calculates minimum bound-to-point distance.
ElemType MinDistance (const HRectBound &other) const
Calculates minimum bound-to-bound distance.
ElemType MinWidth () const
Get the minimum width of the bound.
ElemType & MinWidth ()
Modify the minimum width of the bound.
HRectBound operator & (const HRectBound &bound) const
Returns the intersection of this bound and another.
HRectBound & operator &= (const HRectBound &bound)
Intersects this bound with another.
HRectBound & operator= (const HRectBound &other)
Same as copy constructor; necessary to prevent memory leaks.
math::RangeType< ElemType > & operator[] (const size_t i)
Get the range for a particular dimension.
const math::RangeType< ElemType > & operator[] (const size_t i) const
Modify the range for a particular dimension. No bounds checking.
template
<
typename
MatType
>
HRectBound & operator|= (const MatType &data)
Expands this region to include new points.
HRectBound & operator|= (const HRectBound &other)
Expands this region to encompass another bound.
ElemType Overlap (const HRectBound &bound) const
Returns the volume of overlap of this bound and another.
math::RangeType< ElemType > RangeDistance (const HRectBound &other) const
Calculates minimum and maximum bound-to-bound distance.
template
<
typename
VecType
>
math::RangeType< ElemType > RangeDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >> *=0) const
Calculates minimum and maximum bound-to-point distance.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int version)
Serialize the bound object.
ElemType Volume () const
Calculate the volume of the hyperrectangle.
Private Attributes
math::RangeType< ElemType > * bounds
The bounds for each dimension.
size_t dim
The dimensionality of the bound.
ElemType minWidth
Cached minimum width of bound.
Detailed Description
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> class mlpack::bound::HRectBound< MetricType, ElemType >
Hyper-rectangle bound for an L-metric.
This should be used in conjunction with the LMetric class. Be sure to use the same template parameters for LMetric as you do for HRectBound – otherwise odd results may occur.
Template Parameters
MetricType Type of metric to use; must be of type LMetric.
ElemType Element type (double/float/int/etc.).
Definition at line 54 of file hrectbound.hpp.
Constructor & Destructor Documentation
HRectBound() [1/4]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HRectBound< MetricType, ElemType >::HRectBound ()
Empty constructor; creates a bound of dimensionality 0.
HRectBound() [2/4]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HRectBound< MetricType, ElemType >::HRectBound (const size_t dimension)
Initializes to specified dimensionality with each dimension the empty set.
HRectBound() [3/4]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HRectBound< MetricType, ElemType >::HRectBound (const HRectBound< MetricType, ElemType > & other)
Copy constructor; necessary to prevent memory leaks.
HRectBound() [4/4]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HRectBound< MetricType, ElemType >::HRectBound (HRectBound< MetricType, ElemType > && other)
Move constructor: take possession of another bound's information.
~HRectBound()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HRectBound< MetricType, ElemType >::~HRectBound ()
Destructor: clean up memory.
Member Function Documentation
Center()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> void mlpack::bound::HRectBound< MetricType, ElemType >::Center (arma::Col< ElemType > & center) const
Calculates the center of the range, placing it into the given vector.
Parameters
center Vector which the center will be written to.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::Center(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::Center().
Clear()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> void mlpack::bound::HRectBound< MetricType, ElemType >::Clear ()
Resets all dimensions to the empty set (so that this bound contains nothing).
Contains() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameVecType> bool mlpack::bound::HRectBound< MetricType, ElemType >::Contains (const VecType & point) const
Determines if a point is within this bound.
Contains() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> bool mlpack::bound::HRectBound< MetricType, ElemType >::Contains (const HRectBound< MetricType, ElemType > & bound) const
Determines if this bound partially contains a bound.
Diameter()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::Diameter () const
Returns the diameter of the hyperrectangle (that is, the longest diagonal).
Dim()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> size_t mlpack::bound::HRectBound< MetricType, ElemType >::Dim () const inline
Gets the dimensionality.
Definition at line 90 of file hrectbound.hpp.
MaxDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameVecType> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::MaxDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >> * = 0) const
Calculates maximum bound-to-point squared distance.
Parameters
point Point to which the maximum distance is requested.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MaxDistance().
MaxDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::MaxDistance (const HRectBound< MetricType, ElemType > & other) const
Computes maximum distance.
Parameters
other Bound to which the maximum distance is requested.
MinDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameVecType> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::MinDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >> * = 0) const
Calculates minimum bound-to-point distance.
Parameters
point Point to which the minimum distance is requested.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinDistance().
MinDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::MinDistance (const HRectBound< MetricType, ElemType > & other) const
Calculates minimum bound-to-bound distance.
Parameters
other Bound to which the minimum distance is requested.
MinWidth() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::MinWidth () const inline
Get the minimum width of the bound.
Definition at line 100 of file hrectbound.hpp.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::MinimumBoundDistance().
MinWidth() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType& mlpack::bound::HRectBound< MetricType, ElemType >::MinWidth () inline
Modify the minimum width of the bound.
Definition at line 102 of file hrectbound.hpp.
operator &()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> HRectBound mlpack::bound::HRectBound< MetricType, ElemType >::operator& (const HRectBound< MetricType, ElemType > & bound) const
Returns the intersection of this bound and another.
operator &=()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> HRectBound& mlpack::bound::HRectBound< MetricType, ElemType >::operator&= (const HRectBound< MetricType, ElemType > & bound)
Intersects this bound with another.
operator=()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> HRectBound& mlpack::bound::HRectBound< MetricType, ElemType >::operator= (const HRectBound< MetricType, ElemType > & other)
Same as copy constructor; necessary to prevent memory leaks.
operator[]() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType>& mlpack::bound::HRectBound< MetricType, ElemType >::operator[] (const size_t i) inline
Get the range for a particular dimension.
No bounds checking. Be careful: this may make MinWidth() invalid.
Definition at line 94 of file hrectbound.hpp.
operator[]() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> const math::RangeType<ElemType>& mlpack::bound::HRectBound< MetricType, ElemType >::operator[] (const size_t i) const inline
Modify the range for a particular dimension. No bounds checking.
Definition at line 96 of file hrectbound.hpp.
operator|=() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameMatType> HRectBound& mlpack::bound::HRectBound< MetricType, ElemType >::operator|= (const MatType & data)
Expands this region to include new points.
Template Parameters
MatType Type of matrix; could be Mat, SpMat, a subview, or just a vector.
Parameters
data Data points to expand this region to include.
operator|=() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> HRectBound& mlpack::bound::HRectBound< MetricType, ElemType >::operator|= (const HRectBound< MetricType, ElemType > & other)
Expands this region to encompass another bound.
Overlap()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::Overlap (const HRectBound< MetricType, ElemType > & bound) const
Returns the volume of overlap of this bound and another.
RangeDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType> mlpack::bound::HRectBound< MetricType, ElemType >::RangeDistance (const HRectBound< MetricType, ElemType > & other) const
Calculates minimum and maximum bound-to-bound distance.
Parameters
other Bound to which the minimum and maximum distances are requested.
Referenced by mlpack::tree::RectangleTree< MetricType, StatisticType, MatType, SplitType, DescentType, AuxiliaryInformationType >::RangeDistance().
RangeDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameVecType> math::RangeType<ElemType> mlpack::bound::HRectBound< MetricType, ElemType >::RangeDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >> * = 0) const
Calculates minimum and maximum bound-to-point distance.
Parameters
point Point to which the minimum and maximum distances are requested.
Serialize()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> template<typenameArchive> void mlpack::bound::HRectBound< MetricType, ElemType >::Serialize (Archive & ar, const unsigned int version)
Serialize the bound object.
Volume()
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::Volume () const
Calculate the volume of the hyperrectangle.
Returns
Volume of the hyperrectangle.
Member Data Documentation
bounds
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType>* mlpack::bound::HRectBound< MetricType, ElemType >::bounds private
The bounds for each dimension.
Definition at line 225 of file hrectbound.hpp.
dim
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> size_t mlpack::bound::HRectBound< MetricType, ElemType >::dim private
The dimensionality of the bound.
Definition at line 223 of file hrectbound.hpp.
minWidth
template<typename MetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HRectBound< MetricType, ElemType >::minWidth private
Cached minimum width of bound.
Definition at line 227 of file hrectbound.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/tree/hrectbound.hpp