main
about
docs
get help
github
mlpack::data::DatasetMapper< PolicyType > Class Template Reference
Auxiliary information for a dataset, including mappings to/from strings and the datatype of each dimension.
Public Member Functions
DatasetMapper (const size_t dimensionality=0)
Create the DatasetMapper object with the given dimensionality.
DatasetMapper (PolicyType &policy, const size_t dimensionality=0)
Create the DatasetMapper object with the given policy and dimensionality.
size_t Dimensionality () const
Get the dimensionality of the DatasetMapper object (that is, how many dimensions it has information for).
template
<
typename
T
>
void MapFirstPass (const std::string &string, const size_t dimension)
Preprocessing: during a first pass of the data, pass the strings on to the MapPolicy if they are needed.
template
<
typename
T
>
T MapString (const std::string &string, const size_t dimension)
Given the string and the dimension to which it belongs, return its numeric mapping.
template
<
typename
eT
>
void MapTokens (const std::vector< std::string > &tokens, size_t &row, arma::Mat< eT > &matrix)
MapTokens turns vector of strings into numeric variables and puts them into a given matrix.
size_t NumMappings (const size_t dimension) const
Get the number of mappings for a particular dimension.
const PolicyType & Policy () const
Return the policy of the mapper.
PolicyType & Policy ()
Modify the policy of the mapper (be careful!).
void Policy (PolicyType &&policy)
Modify (Replace) the policy of the mapper with a new policy.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the dataset information.
Datatype Type (const size_t dimension) const
Return the type of a given dimension (numeric or categorical).
Datatype & Type (const size_t dimension)
Modify the type of a given dimension (be careful!).
const std::string & UnmapString (const size_t value, const size_t dimension)
Return the string that corresponds to a given value in a given dimension.
PolicyType::MappedType UnmapValue (const std::string &string, const size_t dimension)
Return the value that corresponds to a given string in a given dimension.
Private Types
using BiMapType = boost::bimap< std::string, typename PolicyType::MappedType >
using MapType = std::unordered_map< size_t, std::pair< BiMapType, size_t > >
Private Attributes
MapType maps
maps object stores string and numerical pairs.
PolicyType policy
policy object tells dataset mapper how the categorical values should be
std::vector< Datatype > types
Types of each dimension.
Detailed Description
template
<
typename
PolicyType
>
class mlpack::data::DatasetMapper< PolicyType >
Auxiliary information for a dataset, including mappings to/from strings and the datatype of each dimension.
DatasetMapper objects are optionally produced by data::Load(), and store the type of each dimension (Datatype::numeric or Datatype::categorical) as well as mappings from strings to unsigned integers and vice versa.
Template Parameters
PolicyType Mapping policy used to specify MapString();
Definition at line 36 of file dataset_mapper.hpp.
Member Typedef Documentation
BiMapType
template<typenamePolicyType> using mlpack::data::DatasetMapper< PolicyType >::BiMapType = boost::bimap<std::string, typename PolicyType::MappedType> private
Definition at line 157 of file dataset_mapper.hpp.
MapType
template<typenamePolicyType> using mlpack::data::DatasetMapper< PolicyType >::MapType = std::unordered_map<size_t, std::pair<BiMapType, size_t> > private
Definition at line 162 of file dataset_mapper.hpp.
Constructor & Destructor Documentation
DatasetMapper() [1/2]
template<typenamePolicyType> mlpack::data::DatasetMapper< PolicyType >::DatasetMapper (const size_t dimensionality = 0) explicit
Create the DatasetMapper object with the given dimensionality.
Note that the dimensionality cannot be changed later; you will have to create a new DatasetMapper object.
DatasetMapper() [2/2]
template<typenamePolicyType> mlpack::data::DatasetMapper< PolicyType >::DatasetMapper (PolicyType & policy, const size_t dimensionality = 0) explicit
Create the DatasetMapper object with the given policy and dimensionality.
Note that the dimensionality cannot be changed later; you will have to create a new DatasetMapper object. Policy can be modified by the modifier.
Member Function Documentation
Dimensionality()
template<typenamePolicyType> size_t mlpack::data::DatasetMapper< PolicyType >::Dimensionality () const
Get the dimensionality of the DatasetMapper object (that is, how many dimensions it has information for).
If this object was created by a call to mlpack::data::Load(), then the dimensionality will be the same as the number of rows (dimensions) in the dataset.
MapFirstPass()
template<typenamePolicyType> template<typenameT> void mlpack::data::DatasetMapper< PolicyType >::MapFirstPass (const std::string & string, const size_t dimension)
Preprocessing: during a first pass of the data, pass the strings on to the MapPolicy if they are needed.
Parameters
string String to map.
dimension Dimension to map for.
MapString()
template<typenamePolicyType> template<typenameT> T mlpack::data::DatasetMapper< PolicyType >::MapString (const std::string & string, const size_t dimension)
Given the string and the dimension to which it belongs, return its numeric mapping.
If no mapping yet exists, the string is added to the list of mappings for the given dimension. The dimension parameter refers to the index of the dimension of the string (i.e. the row in the dataset).
Template Parameters
T Numeric type to map to (int/double/float/etc.).
Parameters
string String to find/create mapping for.
dimension Index of the dimension of the string.
MapTokens()
template<typenamePolicyType> template<typenameeT> void mlpack::data::DatasetMapper< PolicyType >::MapTokens (const std::vector< std::string > & tokens, size_t & row, arma::Mat< eT > & matrix)
MapTokens turns vector of strings into numeric variables and puts them into a given matrix.
It is uses mapping policy to store categorical values to maps. How it determines whether a value is categorical and how it stores the categorical value into map and replaces with the numerical value all depends on the mapping policy object's MapTokens() funciton.
Template Parameters
eT Type of armadillo matrix.
Parameters
tokens Vector of variables inside a dimension.
row Position of the given tokens.
matrix Matrix to save the data into.
NumMappings()
template<typenamePolicyType> size_t mlpack::data::DatasetMapper< PolicyType >::NumMappings (const size_t dimension) const
Get the number of mappings for a particular dimension.
If the dimension is numeric, then this will return 0.
Policy() [1/3]
template<typenamePolicyType> const PolicyType& mlpack::data::DatasetMapper< PolicyType >::Policy () const
Return the policy of the mapper.
Referenced by mlpack::data::DatasetMapper< PolicyType >::Serialize().
Policy() [2/3]
template<typenamePolicyType> PolicyType& mlpack::data::DatasetMapper< PolicyType >::Policy ()
Modify the policy of the mapper (be careful!).
Policy() [3/3]
template<typenamePolicyType> void mlpack::data::DatasetMapper< PolicyType >::Policy (PolicyType && policy)
Modify (Replace) the policy of the mapper with a new policy.
Serialize()
template<typenamePolicyType> template<typenameArchive> void mlpack::data::DatasetMapper< PolicyType >::Serialize (Archive & ar, const unsigned int) inline
Serialize the dataset information.
Definition at line 138 of file dataset_mapper.hpp.
References mlpack::data::CreateNVP(), mlpack::data::DatasetMapper< PolicyType >::maps, mlpack::data::DatasetMapper< PolicyType >::Policy(), and mlpack::data::DatasetMapper< PolicyType >::types.
Type() [1/2]
template<typenamePolicyType> Datatype mlpack::data::DatasetMapper< PolicyType >::Type (const size_t dimension) const
Return the type of a given dimension (numeric or categorical).
Type() [2/2]
template<typenamePolicyType> Datatype& mlpack::data::DatasetMapper< PolicyType >::Type (const size_t dimension)
Modify the type of a given dimension (be careful!).
UnmapString()
template<typenamePolicyType> const std::string& mlpack::data::DatasetMapper< PolicyType >::UnmapString (const size_t value, const size_t dimension)
Return the string that corresponds to a given value in a given dimension.
If the string is not a valid mapping in the given dimension, a std::invalid_argument is thrown.
Parameters
value Mapped value for string.
dimension Dimension to unmap string from.
UnmapValue()
template<typenamePolicyType> PolicyType::MappedType mlpack::data::DatasetMapper< PolicyType >::UnmapValue (const std::string & string, const size_t dimension)
Return the value that corresponds to a given string in a given dimension.
If the value is not a valid mapping in the given dimension, a std::invalid_argument is thrown.
Parameters
string Mapped string for value.
dimension Dimension to unmap string from.
Member Data Documentation
maps
template<typenamePolicyType> MapType mlpack::data::DatasetMapper< PolicyType >::maps private
maps object stores string and numerical pairs.
Definition at line 165 of file dataset_mapper.hpp.
Referenced by mlpack::data::DatasetMapper< PolicyType >::Serialize().
policy
template<typenamePolicyType> PolicyType mlpack::data::DatasetMapper< PolicyType >::policy private
policy object tells dataset mapper how the categorical values should be
Definition at line 169 of file dataset_mapper.hpp.
types
template<typenamePolicyType> std::vector<Datatype> mlpack::data::DatasetMapper< PolicyType >::types private
Types of each dimension.
Definition at line 154 of file dataset_mapper.hpp.
Referenced by mlpack::data::DatasetMapper< PolicyType >::Serialize().
The documentation for this class was generated from the following file:
src/mlpack/core/data/dataset_mapper.hpp