main
about
docs
get help
github
mlpack::kmeans::MaxVarianceNewCluster Class Reference
When an empty cluster is detected, this class takes the point furthest from the centroid of the cluster with maximum variance as a new cluster.
Public Member Functions
MaxVarianceNewCluster ()
Default constructor required by EmptyClusterPolicy.
template
<
typename
MetricType
,
typename
MatType
>
size_t EmptyCluster (const MatType &data, const size_t emptyCluster, const arma::mat &oldCentroids, arma::mat &newCentroids, arma::Col< size_t > &clusterCounts, MetricType &metric, const size_t iteration)
Take the point furthest from the centroid of the cluster with maximum variance to be a new cluster.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int version)
Serialize the object.
Private Member Functions
template
<
typename
MetricType
,
typename
MatType
>
void Precalculate (const MatType &data, const arma::mat &oldCentroids, arma::Col< size_t > &clusterCounts, MetricType &metric)
Called when we are on a new iteration.
Private Attributes
arma::Row< size_t > assignments
Cached assignments for each point.
size_t iteration
Index of iteration for which variance is cached.
arma::vec variances
Cached variances for each cluster.
Detailed Description
When an empty cluster is detected, this class takes the point furthest from the centroid of the cluster with maximum variance as a new cluster.
Definition at line 26 of file max_variance_new_cluster.hpp.
Constructor & Destructor Documentation
MaxVarianceNewCluster()
mlpack::kmeans::MaxVarianceNewCluster::MaxVarianceNewCluster () inline
Default constructor required by EmptyClusterPolicy.
Definition at line 30 of file max_variance_new_cluster.hpp.
References EmptyCluster(), iteration, and Serialize().
Member Function Documentation
EmptyCluster()
template<typenameMetricType,typenameMatType> size_t mlpack::kmeans::MaxVarianceNewCluster::EmptyCluster (const MatType & data, const size_t emptyCluster, const arma::mat & oldCentroids, arma::mat & newCentroids, arma::Col< size_t > & clusterCounts, MetricType & metric, const size_t iteration)
Take the point furthest from the centroid of the cluster with maximum variance to be a new cluster.
Template Parameters
MatType Type of data (arma::mat or arma::sp_mat).
Parameters
data Dataset on which clustering is being performed.
emptyCluster Index of cluster which is empty.
oldCentroids Centroids of each cluster (one per column), at the start of the iteration.
newCentroids Centroids of each cluster (one per column), at the end of the iteration. This will be modified!
clusterCounts Number of points in each cluster.
assignments Cluster assignments of each point.
Returns
Number of points changed.
Referenced by MaxVarianceNewCluster().
Precalculate()
template<typenameMetricType,typenameMatType> void mlpack::kmeans::MaxVarianceNewCluster::Precalculate (const MatType & data, const arma::mat & oldCentroids, arma::Col< size_t > & clusterCounts, MetricType & metric) private
Called when we are on a new iteration.
Serialize()
template<typenameArchive> void mlpack::kmeans::MaxVarianceNewCluster::Serialize (Archive & ar, const unsigned int version)
Serialize the object.
Referenced by MaxVarianceNewCluster().
Member Data Documentation
assignments
arma::Row<size_t> mlpack::kmeans::MaxVarianceNewCluster::assignments private
Cached assignments for each point.
Definition at line 67 of file max_variance_new_cluster.hpp.
iteration
size_t mlpack::kmeans::MaxVarianceNewCluster::iteration private
Index of iteration for which variance is cached.
Definition at line 63 of file max_variance_new_cluster.hpp.
Referenced by MaxVarianceNewCluster().
variances
arma::vec mlpack::kmeans::MaxVarianceNewCluster::variances private
Cached variances for each cluster.
Definition at line 65 of file max_variance_new_cluster.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/kmeans/max_variance_new_cluster.hpp