main
about
docs
get help
github
mlpack::distribution::RegressionDistribution Class Reference
A class that represents a univariate conditionally Gaussian distribution.
Public Member Functions
RegressionDistribution ()
Default constructor, which creates a Gaussian with zero dimension.
RegressionDistribution (const arma::mat &predictors, const arma::vec &responses)
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
size_t Dimensionality () const
Return the dimensionality.
const GaussianDistribution & Err () const
Return error distribution.
GaussianDistribution & Err ()
Modify error distribution.
double LogProbability (const arma::vec &observation) const
Evaluate log probability density function of given observation.
const arma::vec & Parameters () const
Return the parameters (the b vector).
void Predict (const arma::mat &points, arma::vec &predictions) const
Calculate y_i for each data point in points.
double Probability (const arma::vec &observation) const
Evaluate probability density function of given observation.
const regression::LinearRegression & Rf () const
Return regression function.
regression::LinearRegression & Rf ()
Modify regression function.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the distribution.
void Train (const arma::mat &observations)
Estimate the Gaussian distribution directly from the given observations.
void Train (const arma::mat &observations, const arma::vec &weights)
Estimate parameters using provided observation weights.
Private Attributes
GaussianDistribution err
Error distribution.
regression::LinearRegression rf
Regression function for representing conditional mean.
Detailed Description
A class that represents a univariate conditionally Gaussian distribution.
Can be used as an emission distribution with the hmm class to implement HMM regression (HMMR) as described in https://www.ima.umn.edu/preprints/January1994/1195.pdf The hmm observations should have the dependent variable in the first row, with the independent variables in the other rows.
Definition at line 30 of file regression_distribution.hpp.
Constructor & Destructor Documentation
RegressionDistribution() [1/2]
mlpack::distribution::RegressionDistribution::RegressionDistribution () inline
Default constructor, which creates a Gaussian with zero dimension.
Definition at line 42 of file regression_distribution.hpp.
RegressionDistribution() [2/2]
mlpack::distribution::RegressionDistribution::RegressionDistribution (const arma::mat & predictors, const arma::vec & responses) inline
Create a Conditional Gaussian distribution with conditional mean function obtained by running RegressionFunction on predictors, responses.
Parameters
predictors Matrix of predictors (X).
responses Vector of responses (y).
Definition at line 51 of file regression_distribution.hpp.
References mlpack::regression::LinearRegression::ComputeError(), and mlpack::distribution::GaussianDistribution::Covariance().
Member Function Documentation
Dimensionality()
size_t mlpack::distribution::RegressionDistribution::Dimensionality () const inline
Return the dimensionality.
Definition at line 123 of file regression_distribution.hpp.
References mlpack::regression::LinearRegression::Parameters().
Err() [1/2]
const GaussianDistribution& mlpack::distribution::RegressionDistribution::Err () const inline
Return error distribution.
Definition at line 77 of file regression_distribution.hpp.
References err.
Err() [2/2]
GaussianDistribution& mlpack::distribution::RegressionDistribution::Err () inline
Modify error distribution.
Definition at line 79 of file regression_distribution.hpp.
References err, Probability(), and Train().
LogProbability()
double mlpack::distribution::RegressionDistribution::LogProbability (const arma::vec & observation) const inline
Evaluate log probability density function of given observation.
Parameters
observation point to evaluate log probability at
Definition at line 107 of file regression_distribution.hpp.
References Predict(), and Probability().
Parameters()
const arma::vec& mlpack::distribution::RegressionDistribution::Parameters () const inline
Return the parameters (the b vector).
Definition at line 120 of file regression_distribution.hpp.
References mlpack::regression::LinearRegression::Parameters().
Predict()
void mlpack::distribution::RegressionDistribution::Predict (const arma::mat & points, arma::vec & predictions) const
Calculate y_i for each data point in points.
Parameters
points the data points to calculate with.
predictions y, will contain calculated values on completion.
Referenced by LogProbability().
Probability()
double mlpack::distribution::RegressionDistribution::Probability (const arma::vec & observation) const
Evaluate probability density function of given observation.
Parameters
observation point to evaluate probability at
Referenced by Err(), and LogProbability().
Rf() [1/2]
const regression::LinearRegression& mlpack::distribution::RegressionDistribution::Rf () const inline
Return regression function.
Definition at line 72 of file regression_distribution.hpp.
References rf.
Rf() [2/2]
regression::LinearRegression& mlpack::distribution::RegressionDistribution::Rf () inline
Modify regression function.
Definition at line 74 of file regression_distribution.hpp.
References rf.
Serialize()
template<typenameArchive> void mlpack::distribution::RegressionDistribution::Serialize (Archive & ar, const unsigned int) inline
Serialize the distribution.
Definition at line 65 of file regression_distribution.hpp.
References mlpack::data::CreateNVP().
Train() [1/2]
void mlpack::distribution::RegressionDistribution::Train (const arma::mat & observations)
Estimate the Gaussian distribution directly from the given observations.
Parameters
observations List of observations.
Referenced by Err().
Train() [2/2]
void mlpack::distribution::RegressionDistribution::Train (const arma::mat & observations, const arma::vec & weights)
Estimate parameters using provided observation weights.
Parameters
weights probability that given observation is from distribution
Member Data Documentation
err
GaussianDistribution mlpack::distribution::RegressionDistribution::err private
Error distribution.
Definition at line 36 of file regression_distribution.hpp.
Referenced by Err().
rf
regression::LinearRegression mlpack::distribution::RegressionDistribution::rf private
Regression function for representing conditional mean.
Definition at line 34 of file regression_distribution.hpp.
Referenced by Rf().
The documentation for this class was generated from the following file:
src/mlpack/core/dists/regression_distribution.hpp