main
about
docs
get help
github
mlpack::distribution::LaplaceDistribution Class Reference
The multivariate Laplace distribution centered at 0 has pdf.
Public Member Functions
LaplaceDistribution ()
Default constructor, which creates a Laplace distribution with zero dimension and zero scale parameter.
LaplaceDistribution (const size_t dimensionality, const double scale)
Construct the Laplace distribution with the given scale and dimensionality.
LaplaceDistribution (const arma::vec &mean, const double scale)
Construct the Laplace distribution with the given mean and scale parameter.
size_t Dimensionality () const
Return the dimensionality of this distribution.
void Estimate (const arma::mat &observations)
Estimate the Laplace distribution directly from the given observations.
void Estimate (const arma::mat &observations, const arma::vec &probabilities)
Estimate the Laplace distribution from the given observations, taking into account the probability of each observation actually being from this distribution.
double LogProbability (const arma::vec &observation) const
Return the log probability of the given observation.
const arma::vec & Mean () const
Return the mean.
arma::vec & Mean ()
Modify the mean.
double Probability (const arma::vec &observation) const
Return the probability of the given observation.
arma::vec Random () const
Return a randomly generated observation according to the probability distribution defined by this object.
double Scale () const
Return the scale parameter.
double & Scale ()
Modify the scale parameter.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the distribution.
Private Attributes
arma::vec mean
Mean of the distribution.
double scale
Scale parameter of the distribution.
Detailed Description
The multivariate Laplace distribution centered at 0 has pdf.
given scale parameter and mean . This implementation assumes a diagonal covariance, but a rewrite to support arbitrary covariances is possible.
See the following paper for more information on the non-diagonal-covariance Laplace distribution and estimation techniques:
@article{eltoft2006multivariate,
  title={{On the Multivariate Laplace Distribution}},
  author={Eltoft, Torbj\orn and Kim, Taesu and Lee, Te-Won},
  journal={IEEE Signal Processing Letters},
  volume={13},
  number={5},
  pages={300--304},
  year={2006}
}
Note that because of the diagonal covariance restriction, much of the algebra in the paper above becomes simplified, and the PDF takes roughly the same form as the univariate case.
Definition at line 49 of file laplace_distribution.hpp.
Constructor & Destructor Documentation
LaplaceDistribution() [1/3]
mlpack::distribution::LaplaceDistribution::LaplaceDistribution () inline
Default constructor, which creates a Laplace distribution with zero dimension and zero scale parameter.
Definition at line 56 of file laplace_distribution.hpp.
LaplaceDistribution() [2/3]
mlpack::distribution::LaplaceDistribution::LaplaceDistribution (const size_t dimensionality, const double scale) inline
Construct the Laplace distribution with the given scale and dimensionality.
The mean is initialized to zero.
Parameters
dimensionality Dimensionality of distribution.
scale Scale of distribution.
Definition at line 65 of file laplace_distribution.hpp.
LaplaceDistribution() [3/3]
mlpack::distribution::LaplaceDistribution::LaplaceDistribution (const arma::vec & mean, const double scale) inline
Construct the Laplace distribution with the given mean and scale parameter.
Parameters
mean Mean of distribution.
scale Scale of distribution.
Definition at line 74 of file laplace_distribution.hpp.
Member Function Documentation
Dimensionality()
size_t mlpack::distribution::LaplaceDistribution::Dimensionality () const inline
Return the dimensionality of this distribution.
Definition at line 78 of file laplace_distribution.hpp.
References mean.
Estimate() [1/2]
void mlpack::distribution::LaplaceDistribution::Estimate (const arma::mat & observations)
Estimate the Laplace distribution directly from the given observations.
Parameters
observations List of observations.
Referenced by Random().
Estimate() [2/2]
void mlpack::distribution::LaplaceDistribution::Estimate (const arma::mat & observations, const arma::vec & probabilities)
Estimate the Laplace distribution from the given observations, taking into account the probability of each observation actually being from this distribution.
LogProbability()
double mlpack::distribution::LaplaceDistribution::LogProbability (const arma::vec & observation) const
Return the log probability of the given observation.
Referenced by Probability().
Mean() [1/2]
const arma::vec& mlpack::distribution::LaplaceDistribution::Mean () const inline
Return the mean.
Definition at line 134 of file laplace_distribution.hpp.
References mean.
Mean() [2/2]
arma::vec& mlpack::distribution::LaplaceDistribution::Mean () inline
Modify the mean.
Definition at line 136 of file laplace_distribution.hpp.
References mean.
Probability()
double mlpack::distribution::LaplaceDistribution::Probability (const arma::vec & observation) const inline
Return the probability of the given observation.
Definition at line 83 of file laplace_distribution.hpp.
References LogProbability().
Random()
arma::vec mlpack::distribution::LaplaceDistribution::Random () const inline
Return a randomly generated observation according to the probability distribution defined by this object.
This is inlined for speed.
Returns
Random observation from this Laplace distribution.
Definition at line 99 of file laplace_distribution.hpp.
References Estimate(), mean, and scale.
Scale() [1/2]
double mlpack::distribution::LaplaceDistribution::Scale () const inline
Return the scale parameter.
Definition at line 139 of file laplace_distribution.hpp.
References scale.
Scale() [2/2]
double& mlpack::distribution::LaplaceDistribution::Scale () inline
Modify the scale parameter.
Definition at line 141 of file laplace_distribution.hpp.
References scale.
Serialize()
template<typenameArchive> void mlpack::distribution::LaplaceDistribution::Serialize (Archive & ar, const unsigned int) inline
Serialize the distribution.
Definition at line 147 of file laplace_distribution.hpp.
References mlpack::data::CreateNVP(), mean, and scale.
Member Data Documentation
mean
arma::vec mlpack::distribution::LaplaceDistribution::mean private
Mean of the distribution.
Definition at line 155 of file laplace_distribution.hpp.
Referenced by Dimensionality(), Mean(), Random(), and Serialize().
scale
double mlpack::distribution::LaplaceDistribution::scale private
Scale parameter of the distribution.
Definition at line 157 of file laplace_distribution.hpp.
Referenced by Random(), Scale(), and Serialize().
The documentation for this class was generated from the following file:
src/mlpack/core/dists/laplace_distribution.hpp