main
about
docs
get help
github
mlpack::range::RSModel Class Reference
Public Types
enum TreeTypes
{ KD_TREE
, COVER_TREE
, R_TREE
, R_STAR_TREE
, BALL_TREE
, X_TREE
, HILBERT_R_TREE
, R_PLUS_TREE
, R_PLUS_PLUS_TREE
, VP_TREE
, RP_TREE
, MAX_RP_TREE
, UB_TREE
, OCTREE
}
Public Member Functions
RSModel (const TreeTypes treeType=TreeTypes::KD_TREE, const bool randomBasis=false)
Initialize the RSModel with the given type and whether or not a random basis should be used.
~RSModel ()
Clean memory, if necessary.
void BuildModel (arma::mat &&referenceSet, const size_t leafSize, const bool naive, const bool singleMode)
Build the reference tree on the given dataset with the given parameters.
const arma::mat & Dataset () const
Expose the dataset.
size_t LeafSize () const
Get the leaf size (applicable to everything but the cover tree).
size_t & LeafSize ()
Modify the leaf size (applicable to everything but the cover tree).
bool Naive () const
Get whether the model is in naive search mode.
bool & Naive ()
Modify whether the model is in naive search mode.
bool RandomBasis () const
Get whether a random basis is used.
bool & RandomBasis ()
Modify whether a random basis is used (don't do this after the model has been built).
void Search (arma::mat &&querySet, const math::Range &range, std::vector< std::vector< size_t >> &neighbors, std::vector< std::vector< double >> &distances)
Perform range search.
void Search (const math::Range &range, std::vector< std::vector< size_t >> &neighbors, std::vector< std::vector< double >> &distances)
Perform monochromatic range search, with the reference set as the query set.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the range search model.
bool SingleMode () const
Get whether the model is in single-tree search mode.
bool & SingleMode ()
Modify whether the model is in single-tree search mode.
TreeTypes TreeType () const
Get the type of tree.
TreeTypes & TreeType ()
Modify the type of tree (don't do this after the model has been built).
Private Types
template
<
template
<
typename
TreeMetricType
,
typename
TreeStatType
,
typename
TreeMatType
>
class
TreeType
>
using RSType = RangeSearch< metric::EuclideanDistance, arma::mat, TreeType >
The mostly-specified type of the range search model.
Private Member Functions
void CleanMemory ()
Clean up memory.
std::string TreeName () const
Return a string representing the name of the tree.
Private Attributes
RSType< tree::BallTree > * ballTreeRS
Ball tree based range search object (NULL if not in use).
RSType< tree::StandardCoverTree > * coverTreeRS
Cover tree based range search object (NULL if not in use).
RSType< tree::HilbertRTree > * hilbertRTreeRS
Hilbert R tree based range search object (NULL if not in use).
RSType< tree::KDTree > * kdTreeRS
kd-tree based range search object (NULL if not in use).
size_t leafSize
RSType< tree::MaxRPTree > * maxRPTreeRS
Random projection tree (max) based range search object (NULL if not in use).
RSType< tree::Octree > * octreeRS
Octree-based range search object (NULL if not in use).
arma::mat q
Random projection matrix.
bool randomBasis
If true, we randomly project the data into a new basis before search.
RSType< tree::RPlusPlusTree > * rPlusPlusTreeRS
R++ tree based range search object (NULL if not in use).
RSType< tree::RPlusTree > * rPlusTreeRS
R+ tree based range search object (NULL if not in use).
RSType< tree::RPTree > * rpTreeRS
Random projection tree (mean) based range search object (NULL if not in use).
RSType< tree::RStarTree > * rStarTreeRS
R* tree based range search object (NULL if not in use).
RSType< tree::RTree > * rTreeRS
R tree based range search object (NULL if not in use).
TreeTypes treeType
RSType< tree::UBTree > * ubTreeRS
Universal B tree based range search object (NULL if not in use).
RSType< tree::VPTree > * vpTreeRS
VP tree based range search object (NULL if not in use).
RSType< tree::XTree > * xTreeRS
X tree based range search object (NULL if not in use).
Detailed Description
Definition at line 28 of file rs_model.hpp.
Member Typedef Documentation
RSType
template<template<typenameTreeMetricType,typenameTreeStatType,typenameTreeMatType>classTreeType> using mlpack::range::RSModel::RSType = RangeSearch<metric::EuclideanDistance, arma::mat, TreeType> private
The mostly-specified type of the range search model.
Definition at line 62 of file rs_model.hpp.
Member Enumeration Documentation
TreeTypes
enum mlpack::range::RSModel::TreeTypes
Enumerator
KD_TREE
COVER_TREE
R_TREE
R_STAR_TREE
BALL_TREE
X_TREE
HILBERT_R_TREE
R_PLUS_TREE
R_PLUS_PLUS_TREE
VP_TREE
RP_TREE
MAX_RP_TREE
UB_TREE
OCTREE
Definition at line 31 of file rs_model.hpp.
Constructor & Destructor Documentation
RSModel()
mlpack::range::RSModel::RSModel (const TreeTypes treeType = TreeTypes::KD_TREE, const bool randomBasis = false)
Initialize the RSModel with the given type and whether or not a random basis should be used.
Parameters
treeType Type of tree to use.
randomBasis Whether or not to use a random basis.
~RSModel()
mlpack::range::RSModel::~RSModel ()
Clean memory, if necessary.
Member Function Documentation
BuildModel()
void mlpack::range::RSModel::BuildModel (arma::mat && referenceSet, const size_t leafSize, const bool naive, const bool singleMode)
Build the reference tree on the given dataset with the given parameters.
This takes possession of the reference set to avoid a copy.
Parameters
referenceSet Set of reference points.
leafSize Leaf size of tree (ignored for the cover tree).
naive Whether naive search should be used.
singleMode Whether single-tree search should be used.
Referenced by RandomBasis().
CleanMemory()
void mlpack::range::RSModel::CleanMemory () private
Clean up memory.
Referenced by RandomBasis().
Dataset()
const arma::mat& mlpack::range::RSModel::Dataset () const
Expose the dataset.
LeafSize() [1/2]
size_t mlpack::range::RSModel::LeafSize () const inline
Get the leaf size (applicable to everything but the cover tree).
Definition at line 131 of file rs_model.hpp.
References leafSize.
LeafSize() [2/2]
size_t& mlpack::range::RSModel::LeafSize () inline
Modify the leaf size (applicable to everything but the cover tree).
Definition at line 133 of file rs_model.hpp.
References leafSize.
Naive() [1/2]
bool mlpack::range::RSModel::Naive () const
Get whether the model is in naive search mode.
Naive() [2/2]
bool& mlpack::range::RSModel::Naive ()
Modify whether the model is in naive search mode.
RandomBasis() [1/2]
bool mlpack::range::RSModel::RandomBasis () const inline
Get whether a random basis is used.
Definition at line 141 of file rs_model.hpp.
References randomBasis.
RandomBasis() [2/2]
bool& mlpack::range::RSModel::RandomBasis () inline
Modify whether a random basis is used (don't do this after the model has been built).
Definition at line 144 of file rs_model.hpp.
References BuildModel(), CleanMemory(), randomBasis, Search(), and TreeName().
Search() [1/2]
void mlpack::range::RSModel::Search (arma::mat && querySet, const math::Range & range, std::vector< std::vector< size_t >> & neighbors, std::vector< std::vector< double >> & distances)
Perform range search.
This takes possession of the query set, so the query set will not be usable after the search. For more information on the output format, see RangeSearch<>::Search().
Parameters
querySet Set of query points.
range Range to search for.
neighbors Output: neighbors falling within the desired range.
distances Output: distances of neighbors.
Referenced by RandomBasis().
Search() [2/2]
void mlpack::range::RSModel::Search (const math::Range & range, std::vector< std::vector< size_t >> & neighbors, std::vector< std::vector< double >> & distances)
Perform monochromatic range search, with the reference set as the query set.
For more information on the output format, see RangeSearch<>::Search().
Parameters
range Range to search for.
neighbors Output: neighbors falling within the desired range.
distances Output: distances of neighbors.
Serialize()
template<typenameArchive> void mlpack::range::RSModel::Serialize (Archive & ar, const unsigned int)
Serialize the range search model.
SingleMode() [1/2]
bool mlpack::range::RSModel::SingleMode () const
Get whether the model is in single-tree search mode.
SingleMode() [2/2]
bool& mlpack::range::RSModel::SingleMode ()
Modify whether the model is in single-tree search mode.
TreeName()
std::string mlpack::range::RSModel::TreeName () const private
Return a string representing the name of the tree.
This is used for logging output.
Referenced by RandomBasis().
TreeType() [1/2]
TreeTypes mlpack::range::RSModel::TreeType () const inline
Get the type of tree.
Definition at line 136 of file rs_model.hpp.
References treeType.
TreeType() [2/2]
TreeTypes& mlpack::range::RSModel::TreeType () inline
Modify the type of tree (don't do this after the model has been built).
Definition at line 138 of file rs_model.hpp.
References treeType.
Member Data Documentation
ballTreeRS
RSType<tree::BallTree>* mlpack::range::RSModel::ballTreeRS private
Ball tree based range search object (NULL if not in use).
Definition at line 74 of file rs_model.hpp.
coverTreeRS
RSType<tree::StandardCoverTree>* mlpack::range::RSModel::coverTreeRS private
Cover tree based range search object (NULL if not in use).
Definition at line 68 of file rs_model.hpp.
hilbertRTreeRS
RSType<tree::HilbertRTree>* mlpack::range::RSModel::hilbertRTreeRS private
Hilbert R tree based range search object (NULL if not in use).
Definition at line 78 of file rs_model.hpp.
kdTreeRS
RSType<tree::KDTree>* mlpack::range::RSModel::kdTreeRS private
kd-tree based range search object (NULL if not in use).
Definition at line 66 of file rs_model.hpp.
leafSize
size_t mlpack::range::RSModel::leafSize private
Definition at line 51 of file rs_model.hpp.
Referenced by LeafSize().
maxRPTreeRS
RSType<tree::MaxRPTree>* mlpack::range::RSModel::maxRPTreeRS private
Random projection tree (max) based range search object (NULL if not in use).
Definition at line 90 of file rs_model.hpp.
octreeRS
RSType<tree::Octree>* mlpack::range::RSModel::octreeRS private
Octree-based range search object (NULL if not in use).
Definition at line 95 of file rs_model.hpp.
q
arma::mat mlpack::range::RSModel::q private
Random projection matrix.
Definition at line 56 of file rs_model.hpp.
randomBasis
bool mlpack::range::RSModel::randomBasis private
If true, we randomly project the data into a new basis before search.
Definition at line 54 of file rs_model.hpp.
Referenced by RandomBasis().
rPlusPlusTreeRS
RSType<tree::RPlusPlusTree>* mlpack::range::RSModel::rPlusPlusTreeRS private
R++ tree based range search object (NULL if not in use).
Definition at line 82 of file rs_model.hpp.
rPlusTreeRS
RSType<tree::RPlusTree>* mlpack::range::RSModel::rPlusTreeRS private
R+ tree based range search object (NULL if not in use).
Definition at line 80 of file rs_model.hpp.
rpTreeRS
RSType<tree::RPTree>* mlpack::range::RSModel::rpTreeRS private
Random projection tree (mean) based range search object (NULL if not in use).
Definition at line 87 of file rs_model.hpp.
rStarTreeRS
RSType<tree::RStarTree>* mlpack::range::RSModel::rStarTreeRS private
R* tree based range search object (NULL if not in use).
Definition at line 72 of file rs_model.hpp.
rTreeRS
RSType<tree::RTree>* mlpack::range::RSModel::rTreeRS private
R tree based range search object (NULL if not in use).
Definition at line 70 of file rs_model.hpp.
treeType
TreeTypes mlpack::range::RSModel::treeType private
Definition at line 50 of file rs_model.hpp.
Referenced by TreeType().
ubTreeRS
RSType<tree::UBTree>* mlpack::range::RSModel::ubTreeRS private
Universal B tree based range search object (NULL if not in use).
Definition at line 93 of file rs_model.hpp.
vpTreeRS
RSType<tree::VPTree>* mlpack::range::RSModel::vpTreeRS private
VP tree based range search object (NULL if not in use).
Definition at line 84 of file rs_model.hpp.
xTreeRS
RSType<tree::XTree>* mlpack::range::RSModel::xTreeRS private
X tree based range search object (NULL if not in use).
Definition at line 76 of file rs_model.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/range_search/rs_model.hpp