main
about
docs
get help
github
mlpack::tree::HyperplaneBase< BoundT, ProjVectorT > Class Template Reference
HyperplaneBase defines a splitting hyperplane based on a projection vector and projection value.
Public Types
typedef BoundT BoundType
Useful typedef for the bound type.
typedef ProjVectorT ProjVectorType
Useful typedef for the projection vector type.
Public Member Functions
HyperplaneBase ()
Empty Constructor.
HyperplaneBase (const ProjVectorType &projVect, double splitVal)
Create the hyperplane with the specified projection vector and split value.
template
<
typename
VecType
>
bool Left (const VecType &point, typename boost::enable_if< IsVector< VecType > >::type *=0) const
Determine if the given point is to the left of the hyperplane, this means if the projection over the projection vector is negative or zero.
bool Left (const BoundType &bound) const
Determine if the given bound is to the left of the hyperplane.
template
<
typename
VecType
>
double Project (const VecType &point, typename boost::enable_if< IsVector< VecType > >::type *=0) const
Project the given point on the projection vector and subtract the split value.
template
<
typename
VecType
>
bool Right (const VecType &point, typename boost::enable_if< IsVector< VecType > >::type *=0) const
Determine if the given point is to the right of the hyperplane, this means if the projection over the projection vector is positive.
bool Right (const BoundType &bound) const
Determine if the given bound is to the right of the hyperplane.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialization.
Private Attributes
ProjVectorType projVect
Projection vector.
double splitVal
Projection value that determines the decision boundary.
Detailed Description
template
<
typename
BoundT
,
typename
ProjVectorT
>
class mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >
HyperplaneBase defines a splitting hyperplane based on a projection vector and projection value.
Template Parameters
BoundT The bound type considered.
ProjVectorT Type of projection vector (AxisParallelProjVector, ProjVector).
Definition at line 30 of file hyperplane.hpp.
Member Typedef Documentation
BoundType
template<typenameBoundT,typenameProjVectorT> typedef BoundT mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::BoundType
Useful typedef for the bound type.
Definition at line 34 of file hyperplane.hpp.
ProjVectorType
template<typenameBoundT,typenameProjVectorT> typedef ProjVectorT mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::ProjVectorType
Useful typedef for the projection vector type.
Definition at line 36 of file hyperplane.hpp.
Constructor & Destructor Documentation
HyperplaneBase() [1/2]
template<typenameBoundT,typenameProjVectorT> mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::HyperplaneBase () inline
Empty Constructor.
By default will consider all points to the left.
Definition at line 49 of file hyperplane.hpp.
HyperplaneBase() [2/2]
template<typenameBoundT,typenameProjVectorT> mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::HyperplaneBase (const ProjVectorType & projVect, double splitVal) inline
Create the hyperplane with the specified projection vector and split value.
Parameters
projVect Projection vector.
splitVal Split value.
Definition at line 59 of file hyperplane.hpp.
Member Function Documentation
Left() [1/2]
template<typenameBoundT,typenameProjVectorT> template<typenameVecType> bool mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Left (const VecType & point, typename boost::enable_if< IsVector< VecType > >::type * = 0) const inline
Determine if the given point is to the left of the hyperplane, this means if the projection over the projection vector is negative or zero.
Parameters
point Point to be analyzed.
Definition at line 86 of file hyperplane.hpp.
References mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Project().
Left() [2/2]
template<typenameBoundT,typenameProjVectorT> bool mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Left (const BoundType & bound) const inline
Determine if the given bound is to the left of the hyperplane.
Parameters
point Bound to be analyzed.
Definition at line 110 of file hyperplane.hpp.
References mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::splitVal.
Project()
template<typenameBoundT,typenameProjVectorT> template<typenameVecType> double mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Project (const VecType & point, typename boost::enable_if< IsVector< VecType > >::type * = 0) const inline
Project the given point on the projection vector and subtract the split value.
Parameters
point Point to be projected.
Definition at line 71 of file hyperplane.hpp.
References mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::splitVal.
Referenced by mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Left(), and mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Right().
Right() [1/2]
template<typenameBoundT,typenameProjVectorT> template<typenameVecType> bool mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Right (const VecType & point, typename boost::enable_if< IsVector< VecType > >::type * = 0) const inline
Determine if the given point is to the right of the hyperplane, this means if the projection over the projection vector is positive.
Parameters
point Point to be analyzed.
Definition at line 99 of file hyperplane.hpp.
References mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Project().
Right() [2/2]
template<typenameBoundT,typenameProjVectorT> bool mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Right (const BoundType & bound) const inline
Determine if the given bound is to the right of the hyperplane.
Parameters
point Bound to be analyzed.
Definition at line 122 of file hyperplane.hpp.
References mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::splitVal.
Serialize()
template<typenameBoundT,typenameProjVectorT> template<typenameArchive> void mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Serialize (Archive & ar, const unsigned int) inline
Serialization.
Definition at line 133 of file hyperplane.hpp.
References mlpack::data::CreateNVP().
Member Data Documentation
projVect
template<typenameBoundT,typenameProjVectorT> ProjVectorType mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::projVect private
Projection vector.
Definition at line 40 of file hyperplane.hpp.
splitVal
template<typenameBoundT,typenameProjVectorT> double mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::splitVal private
Projection value that determines the decision boundary.
Definition at line 43 of file hyperplane.hpp.
Referenced by mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Left(), mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Project(), and mlpack::tree::HyperplaneBase< BoundT, ProjVectorT >::Right().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/space_split/hyperplane.hpp