main
about
docs
get help
github
mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy > Class Template Reference
This class contains methods which can fit a GMM to observations using the EM algorithm.
Public Member Functions
EMFit (const size_t maxIterations=300, const double tolerance=1e-10, InitialClusteringType clusterer=InitialClusteringType(), CovarianceConstraintPolicy constraint=CovarianceConstraintPolicy())
Construct the EMFit object, optionally passing an InitialClusteringType object (just in case it needs to store state).
const InitialClusteringType & Clusterer () const
Get the clusterer.
InitialClusteringType & Clusterer ()
Modify the clusterer.
const CovarianceConstraintPolicy & Constraint () const
Get the covariance constraint policy class.
CovarianceConstraintPolicy & Constraint ()
Modify the covariance constraint policy class.
void Estimate (const arma::mat &observations, std::vector< distribution::GaussianDistribution > &dists, arma::vec &weights, const bool useInitialModel=false)
Fit the observations to a Gaussian mixture model (GMM) using the EM algorithm.
void Estimate (const arma::mat &observations, const arma::vec &probabilities, std::vector< distribution::GaussianDistribution > &dists, arma::vec &weights, const bool useInitialModel=false)
Fit the observations to a Gaussian mixture model (GMM) using the EM algorithm, taking into account the probabilities of each point being from this mixture.
size_t MaxIterations () const
Get the maximum number of iterations of the EM algorithm.
size_t & MaxIterations ()
Modify the maximum number of iterations of the EM algorithm.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int version)
Serialize the fitter.
double Tolerance () const
Get the tolerance for the convergence of the EM algorithm.
double & Tolerance ()
Modify the tolerance for the convergence of the EM algorithm.
Private Member Functions
void InitialClustering (const arma::mat &observations, std::vector< distribution::GaussianDistribution > &dists, arma::vec &weights)
Run the clusterer, and then turn the cluster assignments into Gaussians.
double LogLikelihood (const arma::mat &data, const std::vector< distribution::GaussianDistribution > &dists, const arma::vec &weights) const
Calculate the log-likelihood of a model.
Private Attributes
InitialClusteringType clusterer
Object which will perform the clustering.
CovarianceConstraintPolicy constraint
Object which applies constraints to the covariance matrix.
size_t maxIterations
Maximum iterations of EM algorithm.
double tolerance
Tolerance for convergence of EM.
Detailed Description
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> class mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >
This class contains methods which can fit a GMM to observations using the EM algorithm.
It requires an initial clustering mechanism, which is by default the KMeans algorithm. The clustering mechanism must implement the following method:
void Cluster(const arma::mat& observations, const size_t clusters, arma::Row<size_t>& assignments);
This method should create 'clusters' clusters, and return the assignment of each point to a cluster.
Definition at line 42 of file em_fit.hpp.
Constructor & Destructor Documentation
EMFit()
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::EMFit (const size_t maxIterations = 300, const double tolerance = 1e-10, InitialClusteringType clusterer = InitialClusteringType(), CovarianceConstraintPolicy constraint = CovarianceConstraintPolicy())
Construct the EMFit object, optionally passing an InitialClusteringType object (just in case it needs to store state).
Setting the maximum number of iterations to 0 means that the EM algorithm will iterate until convergence (with the given tolerance).
The parameter forcePositive controls whether or not the covariance matrices are checked for positive definiteness at each iteration. This could be a time-consuming task, so, if you know your data is well-behaved, you can set it to false and save some runtime.
Parameters
maxIterations Maximum number of iterations for EM.
tolerance Log-likelihood tolerance required for convergence.
forcePositive Check for positive-definiteness of each covariance matrix at each iteration.
clusterer Object which will perform the initial clustering.
Member Function Documentation
Clusterer() [1/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> const InitialClusteringType& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Clusterer () const inline
Get the clusterer.
Definition at line 111 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::clusterer.
Clusterer() [2/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> InitialClusteringType& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Clusterer () inline
Modify the clusterer.
Definition at line 113 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::clusterer.
Constraint() [1/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> const CovarianceConstraintPolicy& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Constraint () const inline
Get the covariance constraint policy class.
Definition at line 116 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::constraint.
Constraint() [2/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> CovarianceConstraintPolicy& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Constraint () inline
Modify the covariance constraint policy class.
Definition at line 118 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::constraint.
Estimate() [1/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> void mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Estimate (const arma::mat & observations, std::vector< distribution::GaussianDistribution > & dists, arma::vec & weights, const bool useInitialModel = false)
Fit the observations to a Gaussian mixture model (GMM) using the EM algorithm.
The size of the vectors (indicating the number of components) must already be set. Optionally, if useInitialModel is set to true, then the model given in the means, covariances, and weights parameters is used as the initial model, instead of using the InitialClusteringType::Cluster() option.
Parameters
observations List of observations to train on.
means Vector to store trained means in.
covariances Vector to store trained covariances in.
weights Vector to store a priori weights in.
useInitialModel If true, the given model is used for the initial clustering.
Estimate() [2/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> void mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Estimate (const arma::mat & observations, const arma::vec & probabilities, std::vector< distribution::GaussianDistribution > & dists, arma::vec & weights, const bool useInitialModel = false)
Fit the observations to a Gaussian mixture model (GMM) using the EM algorithm, taking into account the probabilities of each point being from this mixture.
The size of the vectors (indicating the number of components) must already be set. Optionally, if useInitialModel is set to true, then the model given in the means, covariances, and weights parameters is used as the initial model, instead of using the InitialClusteringType::Cluster() option.
Parameters
observations List of observations to train on.
probabilities Probability of each point being from this model.
means Vector to store trained means in.
covariances Vector to store trained covariances in.
weights Vector to store a priori weights in.
useInitialModel If true, the given model is used for the initial clustering.
InitialClustering()
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> void mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::InitialClustering (const arma::mat & observations, std::vector< distribution::GaussianDistribution > & dists, arma::vec & weights) private
Run the clusterer, and then turn the cluster assignments into Gaussians.
This is a helper function for both overloads of Estimate(). The vectors must be already set to the number of clusters.
Parameters
observations List of observations.
means Vector to store means in.
covariances Vector to store covariances in.
weights Vector to store a priori weights in.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance().
LogLikelihood()
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> double mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::LogLikelihood (const arma::mat & data, const std::vector< distribution::GaussianDistribution > & dists, const arma::vec & weights) const private
Calculate the log-likelihood of a model.
Yes, this is reimplemented in the GMM code. Intuition suggests that the log-likelihood is not the best way to determine if the EM algorithm has converged.
Parameters
data Data matrix.
means Vector of means.
covariances Vector of covariance matrices.
weights Vector of a priori weights.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance().
MaxIterations() [1/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> size_t mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::MaxIterations () const inline
Get the maximum number of iterations of the EM algorithm.
Definition at line 121 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::maxIterations.
MaxIterations() [2/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> size_t& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::MaxIterations () inline
Modify the maximum number of iterations of the EM algorithm.
Definition at line 123 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::maxIterations.
Serialize()
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> template<typenameArchive> void mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Serialize (Archive & ar, const unsigned int version)
Serialize the fitter.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance().
Tolerance() [1/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> double mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance () const inline
Get the tolerance for the convergence of the EM algorithm.
Definition at line 126 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::tolerance.
Tolerance() [2/2]
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> double& mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance () inline
Modify the tolerance for the convergence of the EM algorithm.
Definition at line 128 of file em_fit.hpp.
References mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::InitialClustering(), mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::LogLikelihood(), mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Serialize(), and mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::tolerance.
Member Data Documentation
clusterer
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> InitialClusteringType mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::clusterer private
Object which will perform the clustering.
Definition at line 169 of file em_fit.hpp.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Clusterer().
constraint
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> CovarianceConstraintPolicy mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::constraint private
Object which applies constraints to the covariance matrix.
Definition at line 171 of file em_fit.hpp.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Constraint().
maxIterations
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> size_t mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::maxIterations private
Maximum iterations of EM algorithm.
Definition at line 165 of file em_fit.hpp.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::MaxIterations().
tolerance
template<typename InitialClusteringType = kmeans::KMeans<>, typename CovarianceConstraintPolicy = PositiveDefiniteConstraint> double mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::tolerance private
Tolerance for convergence of EM.
Definition at line 167 of file em_fit.hpp.
Referenced by mlpack::gmm::EMFit< InitialClusteringType, CovarianceConstraintPolicy >::Tolerance().
The documentation for this class was generated from the following file:
src/mlpack/methods/gmm/em_fit.hpp