main
about
docs
get help
github
mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples > Class Template Reference
The class splits a binary space partitioning tree node according to the median distance to the vantage point.
Classes
struct SplitInfo
A struct that contains an information about the split.
Public Types
typedef MatType::elem_type ElemType
The matrix element type.
typedef BoundType::MetricType MetricType
The bounding shape type.
Static Public Member Functions
template
<
typename
VecType
>
static bool AssignToLeftNode (const VecType &point, const SplitInfo &splitInfo)
Indicates that a point should be assigned to the left subtree.
static size_t PerformSplit (MatType &data, const size_t begin, const size_t count, const SplitInfo &splitInfo)
Perform the split process according to the information about the split.
static size_t PerformSplit (MatType &data, const size_t begin, const size_t count, const SplitInfo &splitInfo, std::vector< size_t > &oldFromNew)
Perform the split process according to the information about the split and return the list of changed indices.
static bool SplitNode (const BoundType &bound, MatType &data, const size_t begin, const size_t count, SplitInfo &splitInfo)
Split the node according to the distance to a vantage point.
Static Private Member Functions
static void SelectVantagePoint (const MetricType &metric, const MatType &data, const size_t begin, const size_t count, size_t &vantagePoint, ElemType &mu)
Select the best vantage point, i.e., the point with the largest second moment of the distance from a number of random node points to the vantage point.
Detailed Description
template<typename BoundType, typename MatType = arma::mat, size_t MaxNumSamples = 100> class mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >
The class splits a binary space partitioning tree node according to the median distance to the vantage point.
Thus points that are closer to the vantage point belong to the left subtree and points that are farther from the vantage point belong to the right subtree.
Definition at line 31 of file vantage_point_split.hpp.
Member Typedef Documentation
ElemType
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> typedef MatType::elem_type mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::ElemType
The matrix element type.
Definition at line 35 of file vantage_point_split.hpp.
MetricType
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> typedef BoundType::MetricType mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::MetricType
The bounding shape type.
Definition at line 37 of file vantage_point_split.hpp.
Member Function Documentation
AssignToLeftNode()
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> template<typenameVecType> static bool mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::AssignToLeftNode (const VecType & point, const SplitInfo & splitInfo) inline static
Indicates that a point should be assigned to the left subtree.
This method returns true if a point should be assigned to the left subtree, i.e., if the distance from the point to the vantage point is less then the median value. Otherwise it returns false.
Parameters
point The point that is being assigned.
splitInfo An information about the split.
Definition at line 137 of file vantage_point_split.hpp.
References mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SplitInfo::metric, mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SplitInfo::mu, mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SelectVantagePoint(), and mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SplitInfo::vantagePoint.
PerformSplit() [1/2]
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> static size_t mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::PerformSplit (MatType & data, const size_t begin, const size_t count, const SplitInfo & splitInfo) inline static
Perform the split process according to the information about the split.
This will order the dataset such that points that belong to the left subtree are on the left of the split column, and points from the right subtree are on the right side of the split column.
Parameters
bound The bound used for this node.
data The dataset used by the binary space tree.
begin Index of the starting point in the dataset that belongs to this node.
count Number of points in this node.
splitInfo The information about the split.
Definition at line 92 of file vantage_point_split.hpp.
PerformSplit() [2/2]
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> static size_t mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::PerformSplit (MatType & data, const size_t begin, const size_t count, const SplitInfo & splitInfo, std::vector< size_t > & oldFromNew) inline static
Perform the split process according to the information about the split and return the list of changed indices.
This will order the dataset such that points that belong to the left subtree are on the left of the split column, and points from the right subtree are on the right side of the split column.
Parameters
bound The bound used for this node.
data The dataset used by the binary space tree.
begin Index of the starting point in the dataset that belongs to this node.
count Number of points in this node.
splitInfo The information about the split.
oldFromNew Vector which will be filled with the old positions for each new point.
Definition at line 117 of file vantage_point_split.hpp.
SelectVantagePoint()
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> static void mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SelectVantagePoint (const MetricType & metric, const MatType & data, const size_t begin, const size_t count, size_t & vantagePoint, ElemType & mu) static private
Select the best vantage point, i.e., the point with the largest second moment of the distance from a number of random node points to the vantage point.
Firstly this method selects no more than MaxNumSamples random points. Then it evaluates each point, i.e., calculates the corresponding second moment and selects the point with the largest moment. Each random point belongs to the node.
Parameters
metric The metric used by the tree.
data The dataset used by the tree.
begin Index of the starting point in the dataset that belongs to this node.
count Number of points in this node.
vantagePoint The index of the vantage point in the dataset.
mu The median value of distance form the vantage point to a number of random points.
Referenced by mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::AssignToLeftNode().
SplitNode()
template<typename BoundType , typename MatType = arma::mat, size_t MaxNumSamples = 100> static bool mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SplitNode (const BoundType & bound, MatType & data, const size_t begin, const size_t count, SplitInfo & splitInfo) static
Split the node according to the distance to a vantage point.
Parameters
bound The bound used for this node.
data The dataset used by the binary space tree.
begin Index of the starting point in the dataset that belongs to this node.
count Number of points in this node.
splitInfo An information about the split. This information contains the vantage point and the median distance to the vantage point.
Referenced by mlpack::tree::VantagePointSplit< BoundType, MatType, MaxNumSamples >::SplitInfo::SplitInfo().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/binary_space_tree/vantage_point_split.hpp