main
about
docs
get help
github
mlpack::regression::LinearRegression Class Reference
A simple linear regression algorithm using ordinary least squares.
Public Member Functions
LinearRegression (const arma::mat &predictors, const arma::vec &responses, const double lambda=0, const bool intercept=true, const arma::vec &weights=arma::vec())
Creates the model.
LinearRegression (const LinearRegression &linearRegression)
Copy constructor.
LinearRegression ()
Empty constructor.
double ComputeError (const arma::mat &points, const arma::vec &responses) const
Calculate the L2 squared error on the given predictors and responses using this linear regression model.
bool Intercept () const
Return whether or not an intercept term is used in the model.
double Lambda () const
Return the Tikhonov regularization parameter for ridge regression.
double & Lambda ()
Modify the Tikhonov regularization parameter for ridge regression.
const arma::vec & Parameters () const
Return the parameters (the b vector).
arma::vec & Parameters ()
Modify the parameters (the b vector).
void Predict (const arma::mat &points, arma::vec &predictions) const
Calculate y_i for each data point in points.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the model.
void Train (const arma::mat &predictors, const arma::vec &responses, const bool intercept=true, const arma::vec &weights=arma::vec())
Train the LinearRegression model on the given data.
Private Attributes
bool intercept
Indicates whether first parameter is intercept.
double lambda
The Tikhonov regularization parameter for ridge regression (0 for linear regression).
arma::vec parameters
The calculated B.
Detailed Description
A simple linear regression algorithm using ordinary least squares.
Optionally, this class can perform ridge regression, if the lambda parameter is set to a number greater than zero.
Definition at line 28 of file linear_regression.hpp.
Constructor & Destructor Documentation
LinearRegression() [1/3]
mlpack::regression::LinearRegression::LinearRegression (const arma::mat & predictors, const arma::vec & responses, const double lambda = 0, const bool intercept = true, const arma::vec & weights = arma::vec())
Creates the model.
Parameters
predictors X, matrix of data points to create B with.
responses y, the measured data for each point in X.
lambda Regularization constant for ridge regression.
intercept Whether or not to include an intercept term.
weights Observation weights (for boosting).
LinearRegression() [2/3]
mlpack::regression::LinearRegression::LinearRegression (const LinearRegression & linearRegression)
Copy constructor.
Parameters
linearRegression the other instance to copy parameters from.
LinearRegression() [3/3]
mlpack::regression::LinearRegression::LinearRegression () inline
Empty constructor.
This gives a non-working model, so make sure Train() is called (or make sure the model parameters are set) before calling Predict()!
Definition at line 58 of file linear_regression.hpp.
References ComputeError(), intercept, Predict(), and Train().
Member Function Documentation
ComputeError()
double mlpack::regression::LinearRegression::ComputeError (const arma::mat & points, const arma::vec & responses) const
Calculate the L2 squared error on the given predictors and responses using this linear regression model.
This calculation returns
where is the responses vector, is the matrix of predictors, and is the parameters of the trained linear regression model.
As this number decreases to 0, the linear regression fit is better.
Parameters
points Matrix of predictors (X).
responses Vector of responses (y).
Referenced by LinearRegression(), and mlpack::distribution::RegressionDistribution::RegressionDistribution().
Intercept()
bool mlpack::regression::LinearRegression::Intercept () const inline
Return whether or not an intercept term is used in the model.
Definition at line 116 of file linear_regression.hpp.
References intercept.
Lambda() [1/2]
double mlpack::regression::LinearRegression::Lambda () const inline
Return the Tikhonov regularization parameter for ridge regression.
Definition at line 111 of file linear_regression.hpp.
References lambda.
Lambda() [2/2]
double& mlpack::regression::LinearRegression::Lambda () inline
Modify the Tikhonov regularization parameter for ridge regression.
Definition at line 113 of file linear_regression.hpp.
References lambda.
Parameters() [1/2]
const arma::vec& mlpack::regression::LinearRegression::Parameters () const inline
Return the parameters (the b vector).
Definition at line 106 of file linear_regression.hpp.
References parameters.
Referenced by mlpack::distribution::RegressionDistribution::Dimensionality(), and mlpack::distribution::RegressionDistribution::Parameters().
Parameters() [2/2]
arma::vec& mlpack::regression::LinearRegression::Parameters () inline
Modify the parameters (the b vector).
Definition at line 108 of file linear_regression.hpp.
References parameters.
Predict()
void mlpack::regression::LinearRegression::Predict (const arma::mat & points, arma::vec & predictions) const
Calculate y_i for each data point in points.
Parameters
points the data points to calculate with.
predictions y, will contain calculated values on completion.
Referenced by LinearRegression().
Serialize()
template<typenameArchive> void mlpack::regression::LinearRegression::Serialize (Archive & ar, const unsigned int) inline
Serialize the model.
Definition at line 122 of file linear_regression.hpp.
References mlpack::data::CreateNVP(), intercept, lambda, and parameters.
Train()
void mlpack::regression::LinearRegression::Train (const arma::mat & predictors, const arma::vec & responses, const bool intercept = true, const arma::vec & weights = arma::vec())
Train the LinearRegression model on the given data.
Careful! This will completely ignore and overwrite the existing model. This particular implementation does not have an incremental training algorithm. To set the regularization parameter lambda, call Lambda() or set a different value in the constructor.
Parameters
predictors X, the matrix of data points to train the model on.
responses y, the vector of responses to each data point.
intercept Whether or not to fit an intercept term.
weights Observation weights (for boosting).
Referenced by LinearRegression().
Member Data Documentation
intercept
bool mlpack::regression::LinearRegression::intercept private
Indicates whether first parameter is intercept.
Definition at line 143 of file linear_regression.hpp.
Referenced by Intercept(), LinearRegression(), and Serialize().
lambda
double mlpack::regression::LinearRegression::lambda private
The Tikhonov regularization parameter for ridge regression (0 for linear regression).
Definition at line 140 of file linear_regression.hpp.
Referenced by Lambda(), and Serialize().
parameters
arma::vec mlpack::regression::LinearRegression::parameters private
The calculated B.
Initialized and filled by constructor to hold the least squares solution.
Definition at line 134 of file linear_regression.hpp.
Referenced by Parameters(), and Serialize().
The documentation for this class was generated from the following file:
src/mlpack/methods/linear_regression/linear_regression.hpp