main
about
docs
get help
github
mlpack::tree::XTreeSplit< TreeType > Class Template Reference
A Rectangle Tree has new points inserted at the bottom.
Classes
class sortStruct
Class to allow for faster sorting.
struct SplitHistoryStruct
The X tree requires that the tree records it's "split history".
Public Types
typedef struct mlpack::tree::XTreeSplit::SplitHistoryStruct SplitHistoryStruct
The X tree requires that the tree records it's "split history".
Public Member Functions
XTreeSplit ()
Default constructor.
XTreeSplit (const TreeType *node)
Construct this with the specified node.
XTreeSplit (const TreeType &other)
Create a copy of the other.split.
size_t NormalNodeMaxNumChildren () const
Return the maximum number of a normal node's children.
size_t & NormalNodeMaxNumChildren ()
Modify the maximum number of a normal node's children.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the split.
const SplitHistoryStruct & SplitHistory () const
Return the split history of the node assosiated with this object.
SplitHistoryStruct & SplitHistory ()
Modify the split history of the node assosiated with this object.
void SplitLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a leaf node using the algorithm described in "The R*-tree: An Efficient and Robust Access method for Points and Rectangles.
bool SplitNonLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a non-leaf node using the "default" algorithm.
Static Private Member Functions
static void InsertNodeIntoTree (TreeType *destTree, TreeType *srcNode)
Insert a node into another node.
template
<
typename
ElemType
>
static bool structComp (const sortStruct< ElemType > &s1, const sortStruct< ElemType > &s2)
Comparator for sorting with sortStruct.
Private Attributes
size_t normalNodeMaxNumChildren
The max number of child nodes a non-leaf normal node can have.
SplitHistoryStruct splitHistory
A struct to store the "split history" for X trees.
Detailed Description
template
<
typename
TreeType
>
class mlpack::tree::XTreeSplit< TreeType >
A Rectangle Tree has new points inserted at the bottom.
When these nodes overflow, we split them, moving up the tree and splitting nodes as necessary.
Definition at line 39 of file x_tree_split.hpp.
Member Typedef Documentation
SplitHistoryStruct
template<typenameTreeType> typedef struct mlpack::tree::XTreeSplit::SplitHistoryStruct mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct
The X tree requires that the tree records it's "split history".
To make this easy, we use the following structure.
Constructor & Destructor Documentation
XTreeSplit() [1/3]
template<typenameTreeType> mlpack::tree::XTreeSplit< TreeType >::XTreeSplit ()
Default constructor.
XTreeSplit() [2/3]
template<typenameTreeType> mlpack::tree::XTreeSplit< TreeType >::XTreeSplit (const TreeType * node)
Construct this with the specified node.
XTreeSplit() [3/3]
template<typenameTreeType> mlpack::tree::XTreeSplit< TreeType >::XTreeSplit (const TreeType & other)
Create a copy of the other.split.
Member Function Documentation
InsertNodeIntoTree()
template<typenameTreeType> static void mlpack::tree::XTreeSplit< TreeType >::InsertNodeIntoTree (TreeType * destTree, TreeType * srcNode) static private
Insert a node into another node.
Referenced by mlpack::tree::XTreeSplit< TreeType >::structComp().
NormalNodeMaxNumChildren() [1/2]
template<typenameTreeType> size_t mlpack::tree::XTreeSplit< TreeType >::NormalNodeMaxNumChildren () const inline
Return the maximum number of a normal node's children.
Definition at line 121 of file x_tree_split.hpp.
References mlpack::tree::XTreeSplit< TreeType >::normalNodeMaxNumChildren.
NormalNodeMaxNumChildren() [2/2]
template<typenameTreeType> size_t& mlpack::tree::XTreeSplit< TreeType >::NormalNodeMaxNumChildren () inline
Modify the maximum number of a normal node's children.
Definition at line 123 of file x_tree_split.hpp.
References mlpack::tree::XTreeSplit< TreeType >::normalNodeMaxNumChildren.
Serialize()
template<typenameTreeType> template<typenameArchive> void mlpack::tree::XTreeSplit< TreeType >::Serialize (Archive & ar, const unsigned int)
Serialize the split.
SplitHistory() [1/2]
template<typenameTreeType> const SplitHistoryStruct& mlpack::tree::XTreeSplit< TreeType >::SplitHistory () const inline
Return the split history of the node assosiated with this object.
Definition at line 125 of file x_tree_split.hpp.
References mlpack::tree::XTreeSplit< TreeType >::splitHistory.
SplitHistory() [2/2]
template<typenameTreeType> SplitHistoryStruct& mlpack::tree::XTreeSplit< TreeType >::SplitHistory () inline
Modify the split history of the node assosiated with this object.
Definition at line 127 of file x_tree_split.hpp.
References mlpack::tree::XTreeSplit< TreeType >::SplitHistoryStruct::Serialize(), and mlpack::tree::XTreeSplit< TreeType >::splitHistory.
SplitLeafNode()
template<typenameTreeType> void mlpack::tree::XTreeSplit< TreeType >::SplitLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a leaf node using the algorithm described in "The R*-tree: An Efficient and Robust Access method for Points and Rectangles.
" If necessary, this split will propagate upwards through the tree.
SplitNonLeafNode()
template<typenameTreeType> bool mlpack::tree::XTreeSplit< TreeType >::SplitNonLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a non-leaf node using the "default" algorithm.
If this is a root node, the tree increases in depth.
structComp()
template<typenameTreeType> template<typenameElemType> static bool mlpack::tree::XTreeSplit< TreeType >::structComp (const sortStruct< ElemType > & s1, const sortStruct< ElemType > & s2) inline static private
Comparator for sorting with sortStruct.
Definition at line 108 of file x_tree_split.hpp.
References mlpack::tree::XTreeSplit< TreeType >::sortStruct< ElemType >::d, and mlpack::tree::XTreeSplit< TreeType >::InsertNodeIntoTree().
Member Data Documentation
normalNodeMaxNumChildren
template<typenameTreeType> size_t mlpack::tree::XTreeSplit< TreeType >::normalNodeMaxNumChildren private
The max number of child nodes a non-leaf normal node can have.
Definition at line 89 of file x_tree_split.hpp.
Referenced by mlpack::tree::XTreeSplit< TreeType >::NormalNodeMaxNumChildren().
splitHistory
template<typenameTreeType> SplitHistoryStruct mlpack::tree::XTreeSplit< TreeType >::splitHistory private
A struct to store the "split history" for X trees.
Definition at line 91 of file x_tree_split.hpp.
Referenced by mlpack::tree::XTreeSplit< TreeType >::SplitHistory().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/rectangle_tree/x_tree_split.hpp