main
about
docs
get help
github
mlpack::tree::RStarTreeSplit< TreeType > Class Template Reference
A Rectangle Tree has new points inserted at the bottom.
Classes
struct SortStruct
Class to allow for faster sorting.
Public Member Functions
RStarTreeSplit ()
Default constructor.
RStarTreeSplit (const TreeType *)
Construct this with the specified node.
RStarTreeSplit (const TreeType &)
Create a copy of the other.split.
template
<
typename
Archive
>
void Serialize (Archive &, const unsigned int)
Serialize the split.
void SplitLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a leaf node using the algorithm described in "The R*-tree: An Efficient and Robust Access method for Points and Rectangles.
bool SplitNonLeafNode (TreeType *tree, std::vector< bool > &relevels)
Split a non-leaf node using the "default" algorithm.
Static Private Member Functions
static void InsertNodeIntoTree (TreeType *destTree, TreeType *srcNode)
Insert a node into another node.
template
<
typename
ElemType
>
static bool StructComp (const SortStruct< ElemType > &s1, const SortStruct< ElemType > &s2)
Comparator for sorting with SortStruct.
Detailed Description
template
<
typename
TreeType
>
class mlpack::tree::RStarTreeSplit< TreeType >
A Rectangle Tree has new points inserted at the bottom.
When these nodes overflow, we split them, moving up the tree and splitting nodes as necessary.
Definition at line 29 of file r_star_tree_split.hpp.
Constructor & Destructor Documentation
RStarTreeSplit() [1/3]
template<typenameTreeType> mlpack::tree::RStarTreeSplit< TreeType >::RStarTreeSplit () inline
Default constructor.
Definition at line 33 of file r_star_tree_split.hpp.
RStarTreeSplit() [2/3]
template<typenameTreeType> mlpack::tree::RStarTreeSplit< TreeType >::RStarTreeSplit (const TreeType *) inline
Construct this with the specified node.
Definition at line 36 of file r_star_tree_split.hpp.
RStarTreeSplit() [3/3]
template<typenameTreeType> mlpack::tree::RStarTreeSplit< TreeType >::RStarTreeSplit (const TreeType &) inline
Create a copy of the other.split.
Definition at line 39 of file r_star_tree_split.hpp.
References mlpack::tree::RStarTreeSplit< TreeType >::SplitLeafNode(), and mlpack::tree::RStarTreeSplit< TreeType >::SplitNonLeafNode().
Member Function Documentation
InsertNodeIntoTree()
template<typenameTreeType> static void mlpack::tree::RStarTreeSplit< TreeType >::InsertNodeIntoTree (TreeType * destTree, TreeType * srcNode) static private
Insert a node into another node.
Referenced by mlpack::tree::RStarTreeSplit< TreeType >::StructComp().
Serialize()
template<typenameTreeType> template<typenameArchive> void mlpack::tree::RStarTreeSplit< TreeType >::Serialize (Archive & , const unsigned int) inline
Serialize the split.
Definition at line 85 of file r_star_tree_split.hpp.
SplitLeafNode()
template<typenameTreeType> void mlpack::tree::RStarTreeSplit< TreeType >::SplitLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a leaf node using the algorithm described in "The R*-tree: An Efficient and Robust Access method for Points and Rectangles.
" If necessary, this split will propagate upwards through the tree.
Referenced by mlpack::tree::RStarTreeSplit< TreeType >::RStarTreeSplit().
SplitNonLeafNode()
template<typenameTreeType> bool mlpack::tree::RStarTreeSplit< TreeType >::SplitNonLeafNode (TreeType * tree, std::vector< bool > & relevels)
Split a non-leaf node using the "default" algorithm.
If this is a root node, the tree increases in depth.
Referenced by mlpack::tree::RStarTreeSplit< TreeType >::RStarTreeSplit().
StructComp()
template<typenameTreeType> template<typenameElemType> static bool mlpack::tree::RStarTreeSplit< TreeType >::StructComp (const SortStruct< ElemType > & s1, const SortStruct< ElemType > & s2) inline static private
Comparator for sorting with SortStruct.
Definition at line 69 of file r_star_tree_split.hpp.
References mlpack::tree::RStarTreeSplit< TreeType >::SortStruct< ElemType >::d, and mlpack::tree::RStarTreeSplit< TreeType >::InsertNodeIntoTree().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/rectangle_tree/r_star_tree_split.hpp