main
about
docs
get help
github
mlpack::bound::BallBound< MetricType, VecType > Class Template Reference
Ball bound encloses a set of points at a specific distance (radius) from a specific point (center).
Public Types
typedef VecType::elem_type ElemType
The underlying data type.
typedef VecType Vec
A public version of the vector type.
Public Member Functions
BallBound ()
Empty Constructor.
BallBound (const size_t dimension)
Create the ball bound with the specified dimensionality.
BallBound (const ElemType radius, const VecType &center)
Create the ball bound with the specified radius and center.
BallBound (const BallBound &other)
Copy constructor. To prevent memory leaks.
BallBound (BallBound &&other)
Move constructor: take possession of another bound.
~BallBound ()
Destructor to release allocated memory.
const VecType & Center () const
Get the center point of the ball.
VecType & Center ()
Modify the center point of the ball.
void Center (VecType &center) const
Place the center of BallBound into the given vector.
bool Contains (const VecType &point) const
Determines if a point is within this bound.
ElemType Diameter () const
Returns the diameter of the ballbound.
size_t Dim () const
Get the dimensionality of the ball.
template
<
typename
OtherVecType
>
ElemType MaxDistance (const OtherVecType &point, typename boost::enable_if< IsVector< OtherVecType >> *=0) const
Computes maximum distance.
ElemType MaxDistance (const BallBound &other) const
Computes maximum distance.
const MetricType & Metric () const
Returns the distance metric used in this bound.
MetricType & Metric ()
Modify the distance metric used in this bound.
template
<
typename
OtherVecType
>
ElemType MinDistance (const OtherVecType &point, typename boost::enable_if< IsVector< OtherVecType >> *=0) const
Calculates minimum bound-to-point squared distance.
ElemType MinDistance (const BallBound &other) const
Calculates minimum bound-to-bound squared distance.
ElemType MinWidth () const
Get the minimum width of the bound (this is same as the diameter).
BallBound & operator= (const BallBound &other)
For the same reason as the copy constructor: to prevent memory leaks.
math::RangeType< ElemType > operator[] (const size_t i) const
Get the range in a certain dimension.
const BallBound & operator|= (const BallBound &other)
Expand the bound to include the given node.
template
<
typename
MatType
>
const BallBound & operator|= (const MatType &data)
Expand the bound to include the given point.
ElemType Radius () const
Get the radius of the ball.
ElemType & Radius ()
Modify the radius of the ball.
template
<
typename
OtherVecType
>
math::RangeType< ElemType > RangeDistance (const OtherVecType &other, typename boost::enable_if< IsVector< OtherVecType >> *=0) const
Calculates minimum and maximum bound-to-point distance.
math::RangeType< ElemType > RangeDistance (const BallBound &other) const
Calculates minimum and maximum bound-to-bound distance.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int version)
Serialize the bound.
Private Attributes
VecType center
The center of the ball bound.
MetricType * metric
The metric used in this bound.
bool ownsMetric
To know whether this object allocated memory to the metric member variable.
ElemType radius
The radius of the ball bound.
Detailed Description
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> class mlpack::bound::BallBound< MetricType, VecType >
Ball bound encloses a set of points at a specific distance (radius) from a specific point (center).
MetricType is the custom metric type that defaults to the Euclidean (L2) distance.
Template Parameters
MetricType metric type used in the distance measure.
VecType Type of vector (arma::vec or arma::sp_vec or similar).
Definition at line 32 of file ballbound.hpp.
Member Typedef Documentation
ElemType
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> typedef VecType::elem_type mlpack::bound::BallBound< MetricType, VecType >::ElemType
The underlying data type.
Definition at line 36 of file ballbound.hpp.
Vec
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> typedef VecType mlpack::bound::BallBound< MetricType, VecType >::Vec
A public version of the vector type.
Definition at line 38 of file ballbound.hpp.
Constructor & Destructor Documentation
BallBound() [1/5]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::BallBound ()
Empty Constructor.
BallBound() [2/5]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::BallBound (const size_t dimension)
Create the ball bound with the specified dimensionality.
Parameters
dimension Dimensionality of ball bound.
BallBound() [3/5]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::BallBound (const ElemType radius, const VecType & center)
Create the ball bound with the specified radius and center.
Parameters
radius Radius of ball bound.
center Center of ball bound.
BallBound() [4/5]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::BallBound (const BallBound< MetricType, VecType > & other)
Copy constructor. To prevent memory leaks.
BallBound() [5/5]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::BallBound (BallBound< MetricType, VecType > && other)
Move constructor: take possession of another bound.
~BallBound()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> mlpack::bound::BallBound< MetricType, VecType >::~BallBound ()
Destructor to release allocated memory.
Member Function Documentation
Center() [1/3]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> const VecType& mlpack::bound::BallBound< MetricType, VecType >::Center () const inline
Get the center point of the ball.
Definition at line 94 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::center.
Referenced by mlpack::tree::ProjVector::Project().
Center() [2/3]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> VecType& mlpack::bound::BallBound< MetricType, VecType >::Center () inline
Modify the center point of the ball.
Definition at line 96 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::center.
Center() [3/3]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> void mlpack::bound::BallBound< MetricType, VecType >::Center (VecType & center) const inline
Place the center of BallBound into the given vector.
Parameters
center Vector which the centroid will be written to.
Definition at line 120 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::center, mlpack::bound::BallBound< MetricType, VecType >::MaxDistance(), mlpack::bound::BallBound< MetricType, VecType >::MinDistance(), mlpack::bound::BallBound< MetricType, VecType >::operator|=(), and mlpack::bound::BallBound< MetricType, VecType >::RangeDistance().
Contains()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> bool mlpack::bound::BallBound< MetricType, VecType >::Contains (const VecType & point) const
Determines if a point is within this bound.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::MinWidth().
Diameter()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::Diameter () const inline
Returns the diameter of the ballbound.
Definition at line 182 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::radius.
Dim()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> size_t mlpack::bound::BallBound< MetricType, VecType >::Dim () const inline
Get the dimensionality of the ball.
Definition at line 99 of file ballbound.hpp.
MaxDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> template<typenameOtherVecType> ElemType mlpack::bound::BallBound< MetricType, VecType >::MaxDistance (const OtherVecType & point, typename boost::enable_if< IsVector< OtherVecType >> * = 0) const
Computes maximum distance.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Center().
MaxDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::MaxDistance (const BallBound< MetricType, VecType > & other) const
Computes maximum distance.
Metric() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> const MetricType& mlpack::bound::BallBound< MetricType, VecType >::Metric () const inline
Returns the distance metric used in this bound.
Definition at line 185 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::metric.
Metric() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> MetricType& mlpack::bound::BallBound< MetricType, VecType >::Metric () inline
Modify the distance metric used in this bound.
Definition at line 187 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::metric, and mlpack::bound::BallBound< MetricType, VecType >::Serialize().
MinDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> template<typenameOtherVecType> ElemType mlpack::bound::BallBound< MetricType, VecType >::MinDistance (const OtherVecType & point, typename boost::enable_if< IsVector< OtherVecType >> * = 0) const
Calculates minimum bound-to-point squared distance.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Center().
MinDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::MinDistance (const BallBound< MetricType, VecType > & other) const
Calculates minimum bound-to-bound squared distance.
MinWidth()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::MinWidth () const inline
Get the minimum width of the bound (this is same as the diameter).
For ball bounds, width along all dimensions remain same.
Definition at line 105 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::Contains(), and mlpack::bound::BallBound< MetricType, VecType >::operator[]().
operator=()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> BallBound& mlpack::bound::BallBound< MetricType, VecType >::operator= (const BallBound< MetricType, VecType > & other)
For the same reason as the copy constructor: to prevent memory leaks.
operator[]()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> math::RangeType<ElemType> mlpack::bound::BallBound< MetricType, VecType >::operator[] (const size_t i) const
Get the range in a certain dimension.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::MinWidth().
operator|=() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> const BallBound& mlpack::bound::BallBound< MetricType, VecType >::operator|= (const BallBound< MetricType, VecType > & other)
Expand the bound to include the given node.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Center().
operator|=() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> template<typenameMatType> const BallBound& mlpack::bound::BallBound< MetricType, VecType >::operator|= (const MatType & data)
Expand the bound to include the given point.
The centroid is recalculated to be the center of all of the given points.
Template Parameters
MatType Type of matrix; could be arma::mat, arma::spmat, or a vector.
data Data points to add.
Radius() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::Radius () const inline
Get the radius of the ball.
Definition at line 89 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::radius.
Referenced by mlpack::tree::ProjVector::Project().
Radius() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType& mlpack::bound::BallBound< MetricType, VecType >::Radius () inline
Modify the radius of the ball.
Definition at line 91 of file ballbound.hpp.
References mlpack::bound::BallBound< MetricType, VecType >::radius.
RangeDistance() [1/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> template<typenameOtherVecType> math::RangeType<ElemType> mlpack::bound::BallBound< MetricType, VecType >::RangeDistance (const OtherVecType & other, typename boost::enable_if< IsVector< OtherVecType >> * = 0) const
Calculates minimum and maximum bound-to-point distance.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Center().
RangeDistance() [2/2]
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> math::RangeType<ElemType> mlpack::bound::BallBound< MetricType, VecType >::RangeDistance (const BallBound< MetricType, VecType > & other) const
Calculates minimum and maximum bound-to-bound distance.
Example: bound1.MinDistanceSq(other) for minimum distance.
Serialize()
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> template<typenameArchive> void mlpack::bound::BallBound< MetricType, VecType >::Serialize (Archive & ar, const unsigned int version)
Serialize the bound.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Metric().
Member Data Documentation
center
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> VecType mlpack::bound::BallBound< MetricType, VecType >::center private
The center of the ball bound.
Definition at line 44 of file ballbound.hpp.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Center().
metric
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> MetricType* mlpack::bound::BallBound< MetricType, VecType >::metric private
The metric used in this bound.
Definition at line 46 of file ballbound.hpp.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Metric().
ownsMetric
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> bool mlpack::bound::BallBound< MetricType, VecType >::ownsMetric private
To know whether this object allocated memory to the metric member variable.
This will be true except in the copy constructor and the overloaded assignment operator. We need this to know whether we should delete the metric member variable in the destructor.
Definition at line 54 of file ballbound.hpp.
radius
template<typename MetricType = metric::LMetric<2, true>, typename VecType = arma::vec> ElemType mlpack::bound::BallBound< MetricType, VecType >::radius private
The radius of the ball bound.
Definition at line 42 of file ballbound.hpp.
Referenced by mlpack::bound::BallBound< MetricType, VecType >::Diameter(), and mlpack::bound::BallBound< MetricType, VecType >::Radius().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/ballbound.hpp