main
about
docs
get help
github
src/mlpack/bindings/CMakeLists.txt File Reference
Functions
add_subdirectory (${dir}) endforeach() set(MLPACK_SRCS $
set (DIRS cli python tests) foreach(dir $
PARENT_SCOPE set (MLPACK_PYXS ${MLPACK_PYXS} PARENT_SCOPE) set(DISABLE_CFLAGS $
Function Documentation
add_subdirectory()
add_subdirectory (${dir})
Definition at line 9 of file CMakeLists.txt.
Referenced by include_directories(), macro(), and set().
set() [1/2]
set (DIRS cli python tests)
Definition at line 2 of file CMakeLists.txt.
set() [2/2]
PARENT_SCOPE set (MLPACK_PYXS ${MLPACK_PYXS} PARENT_SCOPE)
Definition at line 13 of file CMakeLists.txt.