main
about
docs
get help
github
OivsInitialization< ActivationFunction > Class Template Reference
This class is used to initialize the weight matrix with the oivs method.
Public Member Functions
OivsInitialization (const double epsilon=0.1, const int k=5, const double gamma=0.9)
Initialize the random initialization rule with the given values.
template
<
typename
eT
>
void Initialize (arma::Mat< eT > &W, const size_t rows, const size_t cols)
Initialize the elements of the specified weight matrix with the oivs method.
template
<
typename
eT
>
void Initialize (arma::Cube< eT > &W, const size_t rows, const size_t cols, const size_t slices)
Initialize the elements of the specified weight 3rd order tensor with the oivs method.
Detailed Description
template
<
class
ActivationFunction
=
LogisticFunction
>
class mlpack::ann::OivsInitialization< ActivationFunction >
This class is used to initialize the weight matrix with the oivs method.
The method is based on the equations representing the characteristics of the information transformation mechanism of a node. The method is defined by
Where f is the transfer function epsilon, k custom parameters, n the number of neurons in the outgoing layer and gamma a parameter that defines the random interval.
Template Parameters
ActivationFunction The activation function used for the oivs method.
Definition at line 59 of file oivs_init.hpp.
Constructor & Destructor Documentation
OivsInitialization()
OivsInitialization (const double epsilon = 0.1, const int k = 5, const double gamma = 0.9) inline
Initialize the random initialization rule with the given values.
Parameters
epsilon Parameter to control the activation region.
k Parameter to control the activation region width.
gamma Parameter to define the uniform random range.
Definition at line 69 of file oivs_init.hpp.
Member Function Documentation
Initialize() [1/2]
void Initialize (arma::Mat< eT > & W, const size_t rows, const size_t cols) inline
Initialize the elements of the specified weight matrix with the oivs method.
Parameters
W Weight matrix to initialize.
rows Number of rows.
cols Number of columns.
Definition at line 86 of file oivs_init.hpp.
References RandomInitialization::Initialize().
Referenced by OivsInitialization< ActivationFunction >::Initialize().
Initialize() [2/2]
void Initialize (arma::Cube< eT > & W, const size_t rows, const size_t cols, const size_t slices) inline
Initialize the elements of the specified weight 3rd order tensor with the oivs method.
Parameters
W 3rd order tensor to initialize.
rows Number of rows.
cols Number of columns.
slices Number of slices.
Definition at line 104 of file oivs_init.hpp.
References OivsInitialization< ActivationFunction >::Initialize().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/init_rules/oivs_init.hpp