main
about
docs
get help
github
SparseSVMFunction Class Reference
Public Member Functions
SparseSVMFunction ()
Nothing to do for the default constructor.
SparseSVMFunction (const arma::sp_mat &dataset, const arma::vec &labels)
Member initialization constructor.
const arma::sp_mat & Dataset () const
Get the dataset.
arma::sp_mat & Dataset ()
Modify the dataset.
double Evaluate (const arma::mat &parameters, const size_t startId, const size_t batchSize=1)
Evaluate the hinge loss function on the specified datapoints.
template
<
typename
GradType
>
void Gradient (const arma::mat &parameters, size_t id, GradType &gradient)
Evaluate the gradient the gradient of the hinge loss function, following the SparseFunctionType requirements on the Gradient function.
const arma::mat & InitialPoint () const
Return the initial point for the optimization.
arma::mat & InitialPoint ()
Modify the initial point for the optimization.
const arma::vec & Labels () const
Get the labels.
arma::vec & Labels ()
Modify the labels.
size_t NumFunctions ()
Return the number of functions.
void Shuffle ()
Shuffle the dataset.
Detailed Description
Definition at line 18 of file sparse_svm_function.hpp.
Constructor & Destructor Documentation
SparseSVMFunction() [1/2]
SparseSVMFunction () inline
Nothing to do for the default constructor.
Definition at line 22 of file sparse_svm_function.hpp.
References Evaluate(), Gradient(), and Shuffle().
SparseSVMFunction() [2/2]
SparseSVMFunction (const arma::sp_mat & dataset, const arma::vec & labels)
Member initialization constructor.
Member Function Documentation
Dataset() [1/2]
const arma::sp_mat& Dataset () const inline
Get the dataset.
Definition at line 62 of file sparse_svm_function.hpp.
Dataset() [2/2]
arma::sp_mat& Dataset () inline
Modify the dataset.
Definition at line 64 of file sparse_svm_function.hpp.
Evaluate()
double Evaluate (const arma::mat & parameters, const size_t startId, const size_t batchSize = 1)
Evaluate the hinge loss function on the specified datapoints.
Parameters
parameters The parameters of the SVM.
startId First index of the datapoints to use for function evaluation.
batchSize Size of batch to process.
Returns
The value of the loss function at the given parameters.
Referenced by SparseSVMFunction().
Gradient()
void Gradient (const arma::mat & parameters, size_t id, GradType & gradient)
Evaluate the gradient the gradient of the hinge loss function, following the SparseFunctionType requirements on the Gradient function.
Parameters
parameters The parameters of the SVM.
id Index of the datapoint to use for the gradient evaluation.
gradient Sparse matrix to output the gradient into.
Referenced by SparseSVMFunction().
InitialPoint() [1/2]
const arma::mat& InitialPoint () const inline
Return the initial point for the optimization.
Definition at line 57 of file sparse_svm_function.hpp.
InitialPoint() [2/2]
arma::mat& InitialPoint () inline
Modify the initial point for the optimization.
Definition at line 59 of file sparse_svm_function.hpp.
Labels() [1/2]
const arma::vec& Labels () const inline
Get the labels.
Definition at line 67 of file sparse_svm_function.hpp.
Labels() [2/2]
arma::vec& Labels () inline
Modify the labels.
Definition at line 69 of file sparse_svm_function.hpp.
References NumFunctions().
NumFunctions()
size_t NumFunctions ()
Return the number of functions.
Referenced by Labels().
Shuffle()
void Shuffle ()
Shuffle the dataset.
Referenced by SparseSVMFunction().
The documentation for this class was generated from the following file:
src/mlpack/methods/sparse_svm/sparse_svm_function.hpp