main
about
docs
get help
github
RosenbrockWoodFunction Class Reference
The Generalized Rosenbrock function in 4 dimensions with the Wood Function in four dimensions.
Public Member Functions
RosenbrockWoodFunction ()
Initialize the RosenbrockWoodFunction.
double Evaluate (const arma::mat &coordinates, const size_t begin, const size_t batchSize) const
double Evaluate (const arma::mat &coordinates) const
const arma::mat & GetInitialPoint () const
Get the starting point.
void Gradient (const arma::mat &coordinates, const size_t begin, arma::mat &gradient, const size_t batchSize) const
void Gradient (const arma::mat &coordinates, arma::mat &gradient) const
size_t NumFunctions () const
Return 1 (the number of functions).
void Shuffle ()
Shuffle the order of function visitation.
Detailed Description
The Generalized Rosenbrock function in 4 dimensions with the Wood Function in four dimensions.
In this function we are actually optimizing a 2x4 matrix of coordinates, not a vector.
Definition at line 30 of file rosenbrock_wood_function.hpp.
Constructor & Destructor Documentation
RosenbrockWoodFunction()
RosenbrockWoodFunction ()
Initialize the RosenbrockWoodFunction.
Member Function Documentation
Evaluate() [1/2]
double Evaluate (const arma::mat & coordinates, const size_t begin, const size_t batchSize) const
Referenced by RosenbrockWoodFunction::GetInitialPoint().
Evaluate() [2/2]
double Evaluate (const arma::mat & coordinates) const
GetInitialPoint()
const arma::mat& GetInitialPoint () const inline
Get the starting point.
Definition at line 46 of file rosenbrock_wood_function.hpp.
References RosenbrockWoodFunction::Evaluate(), and RosenbrockWoodFunction::Gradient().
Gradient() [1/2]
void Gradient (const arma::mat & coordinates, const size_t begin, arma::mat & gradient, const size_t batchSize) const
Referenced by RosenbrockWoodFunction::GetInitialPoint().
Gradient() [2/2]
void Gradient (const arma::mat & coordinates, arma::mat & gradient) const
NumFunctions()
size_t NumFunctions () const inline
Return 1 (the number of functions).
Definition at line 43 of file rosenbrock_wood_function.hpp.
Shuffle()
void Shuffle ()
Shuffle the order of function visitation.
This may be called by the optimizer.
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/problems/rosenbrock_wood_function.hpp