main
about
docs
get help
github
RectifierFunction Class Reference
The rectifier function, defined by.
Static Public Member Functions
static double Deriv (const double y)
Computes the first derivative of the rectifier function.
template
<
typename
InputType
,
typename
OutputType
>
static void Deriv (const InputType &y, OutputType &x)
Computes the first derivatives of the rectifier function.
static double Fn (const double x)
Computes the rectifier function.
template
<
typename
eT
>
static void Fn (const arma::Mat< eT > &x, arma::Mat< eT > &y)
Computes the rectifier function using a dense matrix as input.
template
<
typename
eT
>
static void Fn (const arma::Cube< eT > &x, arma::Cube< eT > &y)
Computes the rectifier function using a 3rd-order tensor as input.
Detailed Description
The rectifier function, defined by.
Definition at line 45 of file rectifier_function.hpp.
Member Function Documentation
Deriv() [1/2]
static double Deriv (const double y) inline static
Computes the first derivative of the rectifier function.
Parameters
x Input data.
Returns
f'(x)
Definition at line 91 of file rectifier_function.hpp.
Referenced by RectifierFunction::Deriv().
Deriv() [2/2]
static void Deriv (const InputType & y, OutputType & x) inline static
Computes the first derivatives of the rectifier function.
Parameters
y Input activations.
x The resulting derivatives.
Definition at line 103 of file rectifier_function.hpp.
References RectifierFunction::Deriv().
Fn() [1/3]
static double Fn (const double x) inline static
Computes the rectifier function.
Parameters
x Input data.
Returns
f(x).
Definition at line 54 of file rectifier_function.hpp.
Referenced by RectifierFunction::Fn().
Fn() [2/3]
static void Fn (const arma::Mat< eT > & x, arma::Mat< eT > & y) inline static
Computes the rectifier function using a dense matrix as input.
Parameters
x Input data.
y The resulting output activation.
Definition at line 66 of file rectifier_function.hpp.
Fn() [3/3]
static void Fn (const arma::Cube< eT > & x, arma::Cube< eT > & y) inline static
Computes the rectifier function using a 3rd-order tensor as input.
Parameters
x Input data.
y The resulting output activation.
Definition at line 78 of file rectifier_function.hpp.
References RectifierFunction::Fn().
The documentation for this class was generated from the following file:
src/mlpack/methods/ann/activation_functions/rectifier_function.hpp