main
about
docs
get help
github
mock_categorical_data.hpp File Reference
Generate categorical dataset for tests.
Functions
void MockCategoricalData (arma::mat &d, arma::Row< size_t > &l, mlpack::data::DatasetInfo &datasetInfo)
Create a mock categorical dataset for testing.
Detailed Description
Generate categorical dataset for tests.
mlpack is free software; you may redistribute it and/or modify it under the terms of the 3-clause BSD license. You should have received a copy of the 3-clause BSD license along with mlpack. If not, see http://www.opensource.org/licenses/BSD-3-Clause for more information.
Definition in file mock_categorical_data.hpp.
Function Documentation
MockCategoricalData()
void MockCategoricalData (arma::mat & d, arma::Row< size_t > & l, mlpack::data::DatasetInfo & datasetInfo) inline
Create a mock categorical dataset for testing.
Definition at line 20 of file mock_categorical_data.hpp.
References mlpack::data::categorical, M_PI, DatasetMapper< PolicyType, InputType >::MapString(), mlpack::math::Random(), DiscreteDistribution::Random(), and DatasetMapper< PolicyType, InputType >::Type().