main
about
docs
get help
github
mlpack::utilities::SaveRestoreUtility Class Reference
Public Member Functions
SaveRestoreUtility ()
~SaveRestoreUtility ()
template
<
typename
T
>
T & LoadParameter (T &t, const std::string &name)
LoadParameter loads a parameter from the parameters map.
template
<
typename
T
>
std::vector< T > & LoadParameter (std::vector< T > &v, const std::string &name)
LoadParameter loads a parameter from the parameters map.
char LoadParameter (char c, const std::string &name)
LoadParameter loads a character from the parameters map.
std::string LoadParameter (std::string &str, const std::string &name)
LoadParameter loads a string from the parameters map.
arma::mat & LoadParameter (arma::mat &matrix, const std::string &name)
LoadParameter loads an arma::mat from the parameters map.
template
<
>
arma::vec & LoadParameter (arma::vec &t, const std::string &name)
Specialization for arma::vec.
bool ReadFile (const std::string &filename)
ReadFile reads an XML tree from a file.
template
<
typename
T
>
void SaveParameter (const T &t, const std::string &name)
SaveParameter saves a parameter to the parameters map.
template
<
typename
T
>
void SaveParameter (const std::vector< T > &v, const std::string &name)
SaveParameter saves a parameter to the parameters map.
void SaveParameter (const char c, const std::string &name)
SaveParameter saves a character to the parameters map.
void SaveParameter (const arma::mat &mat, const std::string &name)
SaveParameter saves an arma::mat to the parameters map.
template
<
>
void SaveParameter (const arma::vec &t, const std::string &name)
Specialization for arma::vec.
bool WriteFile (const std::string &filename)
WriteFile writes the XML tree to a file.
Private Member Functions
void RecurseOnNodes (xmlNode *n)
RecurseOnNodes performs a depth first search of the XML tree.
Private Attributes
std::map< std::string, std::string > parameters
parameters contains a list of names and parameters in string form.
Detailed Description
Definition at line 42 of file save_restore_utility.hpp.
Constructor & Destructor Documentation
SaveRestoreUtility()
mlpack::utilities::SaveRestoreUtility::SaveRestoreUtility () inline
Definition at line 56 of file save_restore_utility.hpp.
~SaveRestoreUtility()
mlpack::utilities::SaveRestoreUtility::~SaveRestoreUtility () inline
Definition at line 57 of file save_restore_utility.hpp.
References LoadParameter(), ReadFile(), SaveParameter(), and WriteFile().
Member Function Documentation
LoadParameter() [1/6]
template<typenameT> T& mlpack::utilities::SaveRestoreUtility::LoadParameter (T & t, const std::string & name)
LoadParameter loads a parameter from the parameters map.
Referenced by ~SaveRestoreUtility().
LoadParameter() [2/6]
template<typenameT> std::vector<T>& mlpack::utilities::SaveRestoreUtility::LoadParameter (std::vector< T > & v, const std::string & name)
LoadParameter loads a parameter from the parameters map.
LoadParameter() [3/6]
char mlpack::utilities::SaveRestoreUtility::LoadParameter (char c, const std::string & name)
LoadParameter loads a character from the parameters map.
LoadParameter() [4/6]
std::string mlpack::utilities::SaveRestoreUtility::LoadParameter (std::string & str, const std::string & name)
LoadParameter loads a string from the parameters map.
LoadParameter() [5/6]
arma::mat& mlpack::utilities::SaveRestoreUtility::LoadParameter (arma::mat & matrix, const std::string & name)
LoadParameter loads an arma::mat from the parameters map.
LoadParameter() [6/6]
template<> arma::vec& mlpack::utilities::SaveRestoreUtility::LoadParameter (arma::vec & t, const std::string & name)
Specialization for arma::vec.
ReadFile()
bool mlpack::utilities::SaveRestoreUtility::ReadFile (const std::string & filename)
ReadFile reads an XML tree from a file.
Referenced by ~SaveRestoreUtility().
RecurseOnNodes()
void mlpack::utilities::SaveRestoreUtility::RecurseOnNodes (xmlNode * n) private
RecurseOnNodes performs a depth first search of the XML tree.
SaveParameter() [1/5]
template<typenameT> void mlpack::utilities::SaveRestoreUtility::SaveParameter (const T & t, const std::string & name)
SaveParameter saves a parameter to the parameters map.
Referenced by ~SaveRestoreUtility().
SaveParameter() [2/5]
template<typenameT> void mlpack::utilities::SaveRestoreUtility::SaveParameter (const std::vector< T > & v, const std::string & name)
SaveParameter saves a parameter to the parameters map.
SaveParameter() [3/5]
void mlpack::utilities::SaveRestoreUtility::SaveParameter (const char c, const std::string & name)
SaveParameter saves a character to the parameters map.
SaveParameter() [4/5]
void mlpack::utilities::SaveRestoreUtility::SaveParameter (const arma::mat & mat, const std::string & name)
SaveParameter saves an arma::mat to the parameters map.
SaveParameter() [5/5]
template<> void mlpack::utilities::SaveRestoreUtility::SaveParameter (const arma::vec & t, const std::string & name)
Specialization for arma::vec.
WriteFile()
bool mlpack::utilities::SaveRestoreUtility::WriteFile (const std::string & filename)
WriteFile writes the XML tree to a file.
Referenced by ~SaveRestoreUtility().
Member Data Documentation
parameters
std::map<std::string, std::string> mlpack::utilities::SaveRestoreUtility::parameters private
parameters contains a list of names and parameters in string form.
Definition at line 48 of file save_restore_utility.hpp.
The documentation for this class was generated from the following file:
/var/www/www.mlpack.org/mlpack-1.0.3/src/mlpack/core/util/save_restore_utility.hpp