main
about
docs
get help
github
mlpack::bound::PeriodicHRectBound< t_pow > Class Template Reference
Hyper-rectangle bound for an L-metric.
Public Member Functions
PeriodicHRectBound ()
Empty constructor.
PeriodicHRectBound (arma::vec box)
Specifies the box size.
PeriodicHRectBound (const PeriodicHRectBound &other)
~PeriodicHRectBound ()
Destructor: clean up memory.
const arma::vec & Box () const
Returns the box vector.
void Centroid (arma::vec &centroid) const
void Clear ()
Resets all dimensions to the empty set.
bool Contains (const arma::vec &point) const
Determines if a point is within this bound.
size_t Dim () const
Gets the dimensionality.
double MaxDistance (const arma::vec &point) const
Calculates maximum bound-to-point squared distance in the periodic bound case.
double MaxDistance (const PeriodicHRectBound &other) const
Computes maximum bound-to-bound squared distance in the periodic bound case.
double MinDistance (const arma::vec &point) const
Calculates minimum bound-to-point squared distance in the periodic bound case.
double MinDistance (const PeriodicHRectBound &other) const
Calculates minimum bound-to-bound squared distance in the periodic bound case.
PeriodicHRectBound & operator= (const PeriodicHRectBound &other)
math::Range & operator[] (size_t i)
Sets and gets the range for a particular dimension.
const math::Range operator[] (size_t i) const
PeriodicHRectBound & operator|= (const arma::vec &vector)
Expands this region to include a new point.
PeriodicHRectBound & operator|= (const PeriodicHRectBound &other)
Expands this region to encompass another bound.
math::Range RangeDistance (const arma::vec &point) const
Calculates minimum and maximum bound-to-point squared distance in the periodic bound case.
math::Range RangeDistance (const PeriodicHRectBound &other) const
Calculates minimum and maximum bound-to-bound squared distance in the periodic bound case.
void SetBoxSize (arma::vec box)
Modifies the box to the desired dimenstions.
Private Attributes
math::Range * bounds
arma::vec box
size_t dim
Detailed Description
template<int t_pow = 2> class mlpack::bound::PeriodicHRectBound< t_pow >
Hyper-rectangle bound for an L-metric.
Template parameter t_pow is the metric to use; use 2 for Euclidean (L2).
Definition at line 38 of file periodichrectbound.hpp.
Constructor & Destructor Documentation
PeriodicHRectBound() [1/3]
template<int t_pow = 2> mlpack::bound::PeriodicHRectBound< t_pow >::PeriodicHRectBound ()
Empty constructor.
PeriodicHRectBound() [2/3]
template<int t_pow = 2> mlpack::bound::PeriodicHRectBound< t_pow >::PeriodicHRectBound (arma::vec box)
Specifies the box size.
The dimensionality is set to the same of the box size, and the bounds are initialized to be empty.
PeriodicHRectBound() [3/3]
template<int t_pow = 2> mlpack::bound::PeriodicHRectBound< t_pow >::PeriodicHRectBound (const PeriodicHRectBound< t_pow > & other)
~PeriodicHRectBound()
template<int t_pow = 2> mlpack::bound::PeriodicHRectBound< t_pow >::~PeriodicHRectBound ()
Destructor: clean up memory.
Member Function Documentation
Box()
template<int t_pow = 2> const arma::vec& mlpack::bound::PeriodicHRectBound< t_pow >::Box () const inline
Returns the box vector.
Definition at line 72 of file periodichrectbound.hpp.
References mlpack::bound::PeriodicHRectBound< t_pow >::box, and mlpack::bound::PeriodicHRectBound< t_pow >::Clear().
Centroid()
template<int t_pow = 2> void mlpack::bound::PeriodicHRectBound< t_pow >::Centroid (arma::vec & centroid) const
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
Clear()
template<int t_pow = 2> void mlpack::bound::PeriodicHRectBound< t_pow >::Clear ()
Resets all dimensions to the empty set.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Box().
Contains()
template<int t_pow = 2> bool mlpack::bound::PeriodicHRectBound< t_pow >::Contains (const arma::vec & point) const
Determines if a point is within this bound.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
Dim()
template<int t_pow = 2> size_t mlpack::bound::PeriodicHRectBound< t_pow >::Dim () const inline
Gets the dimensionality.
Definition at line 80 of file periodichrectbound.hpp.
References mlpack::bound::PeriodicHRectBound< t_pow >::Centroid(), mlpack::bound::PeriodicHRectBound< t_pow >::Contains(), mlpack::bound::PeriodicHRectBound< t_pow >::dim, mlpack::bound::PeriodicHRectBound< t_pow >::MaxDistance(), mlpack::bound::PeriodicHRectBound< t_pow >::MinDistance(), mlpack::bound::PeriodicHRectBound< t_pow >::operator[](), mlpack::bound::PeriodicHRectBound< t_pow >::operator|=(), and mlpack::bound::PeriodicHRectBound< t_pow >::RangeDistance().
MaxDistance() [1/2]
template<int t_pow = 2> double mlpack::bound::PeriodicHRectBound< t_pow >::MaxDistance (const arma::vec & point) const
Calculates maximum bound-to-point squared distance in the periodic bound case.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
MaxDistance() [2/2]
template<int t_pow = 2> double mlpack::bound::PeriodicHRectBound< t_pow >::MaxDistance (const PeriodicHRectBound< t_pow > & other) const
Computes maximum bound-to-bound squared distance in the periodic bound case.
MinDistance() [1/2]
template<int t_pow = 2> double mlpack::bound::PeriodicHRectBound< t_pow >::MinDistance (const arma::vec & point) const
Calculates minimum bound-to-point squared distance in the periodic bound case.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
MinDistance() [2/2]
template<int t_pow = 2> double mlpack::bound::PeriodicHRectBound< t_pow >::MinDistance (const PeriodicHRectBound< t_pow > & other) const
Calculates minimum bound-to-bound squared distance in the periodic bound case.
Example: bound1.MinDistance(other) for minimum squared distance.
operator=()
template<int t_pow = 2> PeriodicHRectBound& mlpack::bound::PeriodicHRectBound< t_pow >::operator= (const PeriodicHRectBound< t_pow > & other)
operator[]() [1/2]
template<int t_pow = 2> math::Range& mlpack::bound::PeriodicHRectBound< t_pow >::operator[] (size_t i)
Sets and gets the range for a particular dimension.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
operator[]() [2/2]
template<int t_pow = 2> const math::Range mlpack::bound::PeriodicHRectBound< t_pow >::operator[] (size_t i) const
operator|=() [1/2]
template<int t_pow = 2> PeriodicHRectBound& mlpack::bound::PeriodicHRectBound< t_pow >::operator|= (const arma::vec & vector)
Expands this region to include a new point.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
operator|=() [2/2]
template<int t_pow = 2> PeriodicHRectBound& mlpack::bound::PeriodicHRectBound< t_pow >::operator|= (const PeriodicHRectBound< t_pow > & other)
Expands this region to encompass another bound.
RangeDistance() [1/2]
template<int t_pow = 2> math::Range mlpack::bound::PeriodicHRectBound< t_pow >::RangeDistance (const arma::vec & point) const
Calculates minimum and maximum bound-to-point squared distance in the periodic bound case.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
RangeDistance() [2/2]
template<int t_pow = 2> math::Range mlpack::bound::PeriodicHRectBound< t_pow >::RangeDistance (const PeriodicHRectBound< t_pow > & other) const
Calculates minimum and maximum bound-to-bound squared distance in the periodic bound case.
SetBoxSize()
template<int t_pow = 2> void mlpack::bound::PeriodicHRectBound< t_pow >::SetBoxSize (arma::vec box)
Modifies the box to the desired dimenstions.
Member Data Documentation
bounds
template<int t_pow = 2> math::Range* mlpack::bound::PeriodicHRectBound< t_pow >::bounds private
Definition at line 150 of file periodichrectbound.hpp.
box
template<int t_pow = 2> arma::vec mlpack::bound::PeriodicHRectBound< t_pow >::box private
Definition at line 152 of file periodichrectbound.hpp.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Box().
dim
template<int t_pow = 2> size_t mlpack::bound::PeriodicHRectBound< t_pow >::dim private
Definition at line 151 of file periodichrectbound.hpp.
Referenced by mlpack::bound::PeriodicHRectBound< t_pow >::Dim().
The documentation for this class was generated from the following file:
/var/www/www.mlpack.org/mlpack-1.0.3/src/mlpack/core/tree/periodichrectbound.hpp