main
about
docs
get help
github
mlpack::tree::Octree< MetricType, StatisticType, MatType > Class Template Reference
Classes
class DualTreeTraverser
A dual-tree traverser; see dual_tree_traverser.hpp.
class SingleTreeTraverser
A single-tree traverser; see single_tree_traverser.hpp.
struct SplitInfo
This is used for sorting points while splitting.
Public Types
typedef MatType::elem_type ElemType
The type of element held in MatType.
typedef MatType Mat
So other classes can use TreeType::Mat.
Public Member Functions
Octree (const MatType &data, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (const MatType &data, std::vector< size_t > &oldFromNew, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (const MatType &data, std::vector< size_t > &oldFromNew, std::vector< size_t > &newFromOld, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (MatType &&data, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (MatType &&data, std::vector< size_t > &oldFromNew, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (MatType &&data, std::vector< size_t > &oldFromNew, std::vector< size_t > &newFromOld, const size_t maxLeafSize=20)
Construct this as the root node of an octree on the given dataset.
Octree (Octree *parent, const size_t begin, const size_t count, const arma::vec &center, const double width, const size_t maxLeafSize=20)
Construct this node as a child of the given parent, starting at column begin and using count points.
Octree (Octree *parent, const size_t begin, const size_t count, std::vector< size_t > &oldFromNew, const arma::vec &center, const double width, const size_t maxLeafSize=20)
Construct this node as a child of the given parent, starting at column begin and using count points.
Octree (const Octree &other)
Copy the given tree.
Octree (Octree &&other)
Move the given tree.
template
<
typename
Archive
>
Octree (Archive &ar, const typename boost::enable_if< typename Archive::is_loading >::type *=0)
Initialize the tree from a boost::serialization archive.
~Octree ()
Destroy the tree.
const bound::HRectBound< MetricType > & Bound () const
Return the bound object for this node.
bound::HRectBound< MetricType > & Bound ()
Modify the bound object for this node.
void Center (arma::vec &center) const
Store the center of the bounding region in the given vector.
const Octree & Child (const size_t child) const
Return the specified child.
Octree & Child (const size_t child)
Return the specified child.
Octree *& ChildPtr (const size_t child)
Return the pointer to the given child.
const MatType & Dataset () const
Return the dataset used by this node.
size_t Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant.
ElemType FurthestDescendantDistance () const
Return the furthest possible descendant distance.
ElemType FurthestPointDistance () const
Return the furthest distance to a point held in this node.
template
<
typename
VecType
>
size_t GetFurthestChild (const VecType &point, typename boost::enable_if< IsVector< VecType > >::type *=0) const
Return the index of the furthest child node to the given query point.
size_t GetFurthestChild (const Octree &queryNode) const
Return the index of the furthest child node to the given query node.
template
<
typename
VecType
>
size_t GetNearestChild (const VecType &point, typename boost::enable_if< IsVector< VecType >>::type *=0) const
Return the index of the nearest child node to the given query point.
size_t GetNearestChild (const Octree &queryNode) const
Return the index of the nearest child node to the given query node.
bool IsLeaf () const
Return whether or not the node is a leaf.
ElemType MaxDistance (const Octree &other) const
Return the maximum distance to another node.
template
<
typename
VecType
>
ElemType MaxDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >>::type *=0) const
Return the maximum distance to the given point.
MetricType Metric () const
Return the metric that this tree uses.
ElemType MinDistance (const Octree &other) const
Return the minimum distance to another node.
template
<
typename
VecType
>
ElemType MinDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >>::type *=0) const
Return the minimum distance to the given point.
ElemType MinimumBoundDistance () const
Return the minimum distance from the center of the node to any bound edge.
size_t NumChildren () const
Return the number of children in this node.
size_t NumDescendants () const
Return the number of descendants of this node.
size_t NumPoints () const
Return the number of points in this node (0 if not a leaf).
Octree * Parent () const
Get the pointer to the parent.
Octree *& Parent ()
Modify the pointer to the parent (be careful!).
ElemType ParentDistance () const
Return the distance from the center of this node to the center of the parent node.
ElemType & ParentDistance ()
Modify the distance from the center of this node to the center of the parent node.
size_t Point (const size_t index) const
Return the index (with reference to the dataset) of a particular point in this node.
math::RangeType< ElemType > RangeDistance (const Octree &other) const
Return the minimum and maximum distance to another node.
template
<
typename
VecType
>
math::RangeType< ElemType > RangeDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >>::type *=0) const
Return the minimum and maximum distance to another node.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the tree.
const StatisticType & Stat () const
Return the statistic object for this node.
StatisticType & Stat ()
Modify the statistic object for this node.
Protected Member Functions
Octree ()
A default constructor.
Private Member Functions
void SplitNode (const arma::vec &center, const double width, const size_t maxLeafSize)
Split the node, using the given center and the given maximum width of this node.
void SplitNode (const arma::vec &center, const double width, std::vector< size_t > &oldFromNew, const size_t maxLeafSize)
Split the node, using the given center and the given maximum width of this node, and fill the mappings vector.
Private Attributes
size_t begin
The index of the first point in the dataset contained in this node (and its children).
bound::HRectBound< MetricType > bound
The minimum bounding rectangle of the points held in the node (and its children).
std::vector< Octree * > children
The children held by this node.
size_t count
The number of points of the dataset contained in this node (and its children).
MatType * dataset
The dataset.
ElemType furthestDescendantDistance
The distance to the furthest descendant, cached to speed things up.
MetricType metric
An instantiated metric.
Octree * parent
The parent (NULL if this node is the root).
ElemType parentDistance
The distance from the center of this node to the center of the parent.
StatisticType stat
The statistic.
Detailed Description
template
<
typename
MetricType
=
metric::EuclideanDistance
,
typename
StatisticType
=
EmptyStatistic
,
typename
MatType
=
arma::mat
>
class mlpack::tree::Octree< MetricType, StatisticType, MatType >
Definition at line 25 of file octree.hpp.
Member Typedef Documentation
ElemType
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> typedef MatType::elem_type mlpack::tree::Octree< MetricType, StatisticType, MatType >::ElemType
The type of element held in MatType.
Definition at line 31 of file octree.hpp.
Mat
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> typedef MatType mlpack::tree::Octree< MetricType, StatisticType, MatType >::Mat
So other classes can use TreeType::Mat.
Definition at line 29 of file octree.hpp.
Constructor & Destructor Documentation
Octree() [1/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (const MatType & data, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This copies the dataset. If you don't want to copy the input dataset, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
maxLeafSize Maximum number of points in a leaf node.
Octree() [2/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (const MatType & data, std::vector< size_t > & oldFromNew, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This copies the dataset and modifies its ordering; a mapping of the old point indices to the new point indices is filled. If you don't want the matrix to be copied, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
maxLeafSize Maximum number of points in a leaf node.
Octree() [3/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (const MatType & data, std::vector< size_t > & oldFromNew, std::vector< size_t > & newFromOld, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This copies the dataset and modifies its ordering; a mapping of the old point indices to the new point indices is filled, and a mapping of the new point indices to the old point indices is filled. If you don't want the matrix to be copied, consider using the constructor that takes an rvalue reference and use std::move().
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
newFromOld Vector which will be filled with the new positions for each old point.
maxLeafSize Maximum number of points in a leaf node.
Octree() [4/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (MatType && data, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This will take ownership of the dataset; if you don't want this, consider using the constructor that takes a const reference to the dataset.
Parameters
data Dataset to create tree from. This will be copied!
maxLeafSize Maximum number of points in a leaf node.
Octree() [5/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (MatType && data, std::vector< size_t > & oldFromNew, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This will take ownership of the dataset; if you don't want this, consider using the constructor that takes a const reference to the dataset. This modifies the ordering of the dataset; a mapping of the old point indices to the new point indices is filled.
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
maxLeafSize Maximum number of points in a leaf node.
Octree() [6/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (MatType && data, std::vector< size_t > & oldFromNew, std::vector< size_t > & newFromOld, const size_t maxLeafSize = 20)
Construct this as the root node of an octree on the given dataset.
This will take ownership of the dataset; if you don't want this, consider using the constructor that takes a const reference to the dataset. This modifies the ordering of the dataset; a mapping of the old point indices to the new point indices is filled, and a mapping of the new point indices to the old point indices is filled.
Parameters
data Dataset to create tree from. This will be copied!
oldFromNew Vector which will be filled with the old positions for each new point.
newFromOld Vector which will be filled with the new positions for each old point.
maxLeafSize Maximum number of points in a leaf node.
Octree() [7/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (Octree< MetricType, StatisticType, MatType > * parent, const size_t begin, const size_t count, const arma::vec & center, const double width, const size_t maxLeafSize = 20)
Construct this node as a child of the given parent, starting at column begin and using count points.
The ordering of that subset of points in the parent's data matrix will be modified! This is used for recursive tree-building by the other constructors that don't specify point indices.
Parameters
parent Parent of this node. Its dataset will be modified!
begin Index of point to start tree construction with.
count Number of points to use to construct tree.
center Center of the node (for splitting).
width Width of the node in each dimension.
maxLeafSize Maximum number of points in a leaf node.
Octree() [8/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (Octree< MetricType, StatisticType, MatType > * parent, const size_t begin, const size_t count, std::vector< size_t > & oldFromNew, const arma::vec & center, const double width, const size_t maxLeafSize = 20)
Construct this node as a child of the given parent, starting at column begin and using count points.
The ordering of that subset of points in the parent's data matrix will be modified! This is used for recursive tree-building by the other constructors that don't specify point indices.
A mapping of the old point indices to the new point indices is filled, but it is expected that the vector is already allocated with size greater than or equal to (begin + count), and if that is not true, invalid memory reads (and writes) will occur.
Parameters
parent Parent of this node. Its dataset will be modified!
begin Index of point to start tree construction with.
count Number of points to use to construct tree.
oldFromNew Vector which will be filled with the old positions for each new point.
center Center of the node (for splitting).
width Width of the node in each dimension.
maxLeafSize Maximum number of points in a leaf node.
Octree() [9/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (const Octree< MetricType, StatisticType, MatType > & other)
Copy the given tree.
Be careful! This may use a lot of memory.
Parameters
other Tree to copy from.
Octree() [10/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (Octree< MetricType, StatisticType, MatType > && other)
Move the given tree.
The tree passed as a parameter will be emptied and will not be usable after this call.
Parameters
other Tree to move.
Octree() [11/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameArchive> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree (Archive & ar, const typename boost::enable_if< typename Archive::is_loading >::type * = 0)
Initialize the tree from a boost::serialization archive.
Parameters
ar Archive to load tree from. Must be an iarchive, not an oarchive.
~Octree()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::~Octree ()
Destroy the tree.
Octree() [12/12]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree () protected
A default constructor.
This is meant to only be used with boost::serialization, which is allowed with the friend declaration below. This does not return a valid treee! The method must be protected, so that the serialization shim can work with the default constructor.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Center().
Member Function Documentation
Bound() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> const bound::HRectBound<MetricType>& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Bound () const inline
Return the bound object for this node.
Definition at line 247 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::bound.
Bound() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> bound::HRectBound<MetricType>& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Bound () inline
Modify the bound object for this node.
Definition at line 249 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::bound.
Center()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> void mlpack::tree::Octree< MetricType, StatisticType, MatType >::Center (arma::vec & center) const inline
Store the center of the bounding region in the given vector.
Definition at line 383 of file octree.hpp.
References mlpack::bound::HRectBound< MetricType, ElemType >::Center(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::Octree(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::Serialize().
Child() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> const Octree& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Child (const size_t child) const inline
Return the specified child.
If the index is out of bounds, unspecified behavior will occur.
Definition at line 326 of file octree.hpp.
Child() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> Octree& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Child (const size_t child) inline
Return the specified child.
If the index is out of bounds, unspecified behavior will occur.
Definition at line 332 of file octree.hpp.
ChildPtr()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> Octree*& mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr (const size_t child) inline
Return the pointer to the given child.
This allows the child itself to be modified.
Definition at line 338 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::Descendant(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::MaxDistance(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::MinDistance(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumDescendants(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumPoints(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::Point(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::RangeDistance().
Dataset()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> const MatType& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Dataset () const inline
Return the dataset used by this node.
Definition at line 239 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::dataset.
Descendant()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::Descendant (const size_t index) const
Return the index (with reference to the dataset) of a particular descendant.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
FurthestDescendantDistance()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::FurthestDescendantDistance () const
Return the furthest possible descendant distance.
This returns the maximum distance from the centroid to the edge of the bound and not the empirical quantity which is the actual furthest descendant distance. So the actual furthest descendant distance may be less than what this method returns (but it will never be greater than this).
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf().
FurthestPointDistance()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::FurthestPointDistance () const
Return the furthest distance to a point held in this node.
If this is not a leaf node, then the distance is 0 because the node holds no points.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf().
GetFurthestChild() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameVecType> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetFurthestChild (const VecType & point, typename boost::enable_if< IsVector< VecType > >::type * = 0) const
Return the index of the furthest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::Metric().
GetFurthestChild() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetFurthestChild (const Octree< MetricType, StatisticType, MatType > & queryNode) const
Return the index of the furthest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
GetNearestChild() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameVecType> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetNearestChild (const VecType & point, typename boost::enable_if< IsVector< VecType >>::type * = 0) const
Return the index of the nearest child node to the given query point.
If this is a leaf node, it will return NumChildren() (invalid index).
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::Metric().
GetNearestChild() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetNearestChild (const Octree< MetricType, StatisticType, MatType > & queryNode) const
Return the index of the nearest child node to the given query node.
If it can't decide, it will return NumChildren() (invalid index).
IsLeaf()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> bool mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf () const inline
Return whether or not the node is a leaf.
Definition at line 283 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::FurthestDescendantDistance(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::FurthestPointDistance(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetFurthestChild(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetNearestChild(), mlpack::tree::Octree< MetricType, StatisticType, MatType >::MinimumBoundDistance(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumChildren().
MaxDistance() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::MaxDistance (const Octree< MetricType, StatisticType, MatType > & other) const
Return the maximum distance to another node.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
MaxDistance() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameVecType> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::MaxDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >>::type * = 0) const
Return the maximum distance to the given point.
Metric()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> MetricType mlpack::tree::Octree< MetricType, StatisticType, MatType >::Metric () const inline
Return the metric that this tree uses.
Definition at line 260 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetFurthestChild(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::GetNearestChild().
MinDistance() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::MinDistance (const Octree< MetricType, StatisticType, MatType > & other) const
Return the minimum distance to another node.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
MinDistance() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameVecType> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::MinDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >>::type * = 0) const
Return the minimum distance to the given point.
MinimumBoundDistance()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::MinimumBoundDistance () const
Return the minimum distance from the center of the node to any bound edge.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf().
NumChildren()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumChildren () const
Return the number of children in this node.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::IsLeaf(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::Stat().
NumDescendants()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumDescendants () const
Return the number of descendants of this node.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
NumPoints()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumPoints () const
Return the number of points in this node (0 if not a leaf).
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
Parent() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> Octree* mlpack::tree::Octree< MetricType, StatisticType, MatType >::Parent () const inline
Get the pointer to the parent.
Definition at line 242 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::parent.
Parent() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> Octree*& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Parent () inline
Modify the pointer to the parent (be careful!).
Definition at line 244 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::parent.
ParentDistance() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::ParentDistance () const inline
Return the distance from the center of this node to the center of the parent node.
Definition at line 317 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::parentDistance.
ParentDistance() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType& mlpack::tree::Octree< MetricType, StatisticType, MatType >::ParentDistance () inline
Modify the distance from the center of this node to the center of the parent node.
Definition at line 320 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::parentDistance.
Point()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::Point (const size_t index) const
Return the index (with reference to the dataset) of a particular point in this node.
If the given index is invalid (i.e. if it is greater than NumPoints()), the indices returned will be invalid.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
RangeDistance() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> math::RangeType<ElemType> mlpack::tree::Octree< MetricType, StatisticType, MatType >::RangeDistance (const Octree< MetricType, StatisticType, MatType > & other) const
Return the minimum and maximum distance to another node.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ChildPtr().
RangeDistance() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameVecType> math::RangeType<ElemType> mlpack::tree::Octree< MetricType, StatisticType, MatType >::RangeDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >>::type * = 0) const
Return the minimum and maximum distance to another node.
Serialize()
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> template<typenameArchive> void mlpack::tree::Octree< MetricType, StatisticType, MatType >::Serialize (Archive & ar, const unsigned int)
Serialize the tree.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Center().
SplitNode() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> void mlpack::tree::Octree< MetricType, StatisticType, MatType >::SplitNode (const arma::vec & center, const double width, const size_t maxLeafSize) private
Split the node, using the given center and the given maximum width of this node.
Parameters
center Center of the node.
width Width of the current node.
maxLeafSize Maximum number of points allowed in a leaf.
SplitNode() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> void mlpack::tree::Octree< MetricType, StatisticType, MatType >::SplitNode (const arma::vec & center, const double width, std::vector< size_t > & oldFromNew, const size_t maxLeafSize) private
Split the node, using the given center and the given maximum width of this node, and fill the mappings vector.
Parameters
center Center of the node.
width Width of the current node.
oldFromNew Mappings from old to new.
maxLeafSize Maximum number of points allowed in a leaf.
Stat() [1/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> const StatisticType& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Stat () const inline
Return the statistic object for this node.
Definition at line 252 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::stat.
Stat() [2/2]
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> StatisticType& mlpack::tree::Octree< MetricType, StatisticType, MatType >::Stat () inline
Modify the statistic object for this node.
Definition at line 254 of file octree.hpp.
References mlpack::tree::Octree< MetricType, StatisticType, MatType >::NumChildren(), and mlpack::tree::Octree< MetricType, StatisticType, MatType >::stat.
Member Data Documentation
begin
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::begin private
The index of the first point in the dataset contained in this node (and its children).
Definition at line 47 of file octree.hpp.
bound
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> bound::HRectBound<MetricType> mlpack::tree::Octree< MetricType, StatisticType, MatType >::bound private
The minimum bounding rectangle of the points held in the node (and its children).
Definition at line 53 of file octree.hpp.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Bound().
children
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> std::vector<Octree*> mlpack::tree::Octree< MetricType, StatisticType, MatType >::children private
The children held by this node.
Definition at line 39 of file octree.hpp.
count
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> size_t mlpack::tree::Octree< MetricType, StatisticType, MatType >::count private
The number of points of the dataset contained in this node (and its children).
Definition at line 50 of file octree.hpp.
dataset
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> MatType* mlpack::tree::Octree< MetricType, StatisticType, MatType >::dataset private
The dataset.
Definition at line 55 of file octree.hpp.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Dataset().
furthestDescendantDistance
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::furthestDescendantDistance private
The distance to the furthest descendant, cached to speed things up.
Definition at line 63 of file octree.hpp.
metric
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> MetricType mlpack::tree::Octree< MetricType, StatisticType, MatType >::metric private
An instantiated metric.
Definition at line 65 of file octree.hpp.
parent
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> Octree* mlpack::tree::Octree< MetricType, StatisticType, MatType >::parent private
The parent (NULL if this node is the root).
Definition at line 57 of file octree.hpp.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Parent().
parentDistance
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> ElemType mlpack::tree::Octree< MetricType, StatisticType, MatType >::parentDistance private
The distance from the center of this node to the center of the parent.
Definition at line 61 of file octree.hpp.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::ParentDistance().
stat
template<typenameMetricType=metric::EuclideanDistance,typenameStatisticType=EmptyStatistic,typenameMatType=arma::mat> StatisticType mlpack::tree::Octree< MetricType, StatisticType, MatType >::stat private
The statistic.
Definition at line 59 of file octree.hpp.
Referenced by mlpack::tree::Octree< MetricType, StatisticType, MatType >::Stat().
The documentation for this class was generated from the following file:
src/mlpack/core/tree/octree/octree.hpp