mlpack: mlpack::bound::HollowBallBound< TMetricType, ElemType > Class Template Reference
mlpack::bound::HollowBallBound< TMetricType, ElemType > Class Template Reference
Hollow ball bound encloses a set of points at a specific distance (radius) from a specific point (center) except points at a specific distance from another point (the center of the hole).
Public Types
typedef TMetricType MetricType
A public version of the metric type.
Public Member Functions
HollowBallBound ()
Empty Constructor.
HollowBallBound (const size_t dimension)
Create the ball bound with the specified dimensionality.
template<typename VecType >
HollowBallBound (const ElemType innerRadius, const ElemType outerRadius, const VecType &center)
Create the ball bound with the specified radius and center.
HollowBallBound (const HollowBallBound &other)
Copy constructor. To prevent memory leaks.
HollowBallBound (HollowBallBound &&other)
Move constructor: take possession of another bound.
~HollowBallBound ()
Destructor to release allocated memory.
const arma::Col< ElemType > & Center () const
Get the center point of the ball.
arma::Col< ElemType > & Center ()
Modify the center point of the ball.
template<typename VecType >
void Center (VecType &center) const
Place the center of BallBound into the given vector.
template<typename VecType >
bool Contains (const VecType &point) const
Determines if a point is within this bound.
bool Contains (const HollowBallBound &other) const
Determines if another bound is within this bound.
ElemType Diameter () const
Returns the diameter of the ballbound.
size_t Dim () const
Get the dimensionality of the ball.
const arma::Col< ElemType > & HollowCenter () const
Get the center point of the hollow.
arma::Col< ElemType > & HollowCenter ()
Modify the center point of the hollow.
ElemType InnerRadius () const
Get the innner radius of the ball.
ElemType & InnerRadius ()
Modify the inner radius of the ball.
template<typename VecType >
ElemType MaxDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >> *=0) const
Computes maximum distance.
ElemType MaxDistance (const HollowBallBound &other) const
Computes maximum distance.
const MetricType & Metric () const
Returns the distance metric used in this bound.
MetricType & Metric ()
Modify the distance metric used in this bound.
template<typename VecType >
ElemType MinDistance (const VecType &point, typename boost::enable_if< IsVector< VecType >> *=0) const
Calculates minimum bound-to-point squared distance.
ElemType MinDistance (const HollowBallBound &other) const
Calculates minimum bound-to-bound squared distance.
ElemType MinWidth () const
Get the minimum width of the bound (this is same as the diameter).
HollowBallBound & operator= (const HollowBallBound &other)
For the same reason as the copy constructor: to prevent memory leaks.
math::RangeType< ElemType > operator[] (const size_t i) const
Get the range in a certain dimension.
template<typename MatType >
const HollowBallBound & operator|= (const MatType &data)
Expand the bound to include the given point.
const HollowBallBound & operator|= (const HollowBallBound &other)
Expand the bound to include the given bound.
ElemType OuterRadius () const
Get the outer radius of the ball.
ElemType & OuterRadius ()
Modify the outer radius of the ball.
template<typename VecType >
math::RangeType< ElemType > RangeDistance (const VecType &other, typename boost::enable_if< IsVector< VecType >> *=0) const
Calculates minimum and maximum bound-to-point distance.
math::RangeType< ElemType > RangeDistance (const HollowBallBound &other) const
Calculates minimum and maximum bound-to-bound distance.
template<typename Archive >
void Serialize (Archive &ar, const unsigned int version)
Serialize the bound.
Private Attributes
arma::Col< ElemType > center
The center of the ball bound.
arma::Col< ElemType > hollowCenter
The center of the hollow.
MetricType * metric
The metric used in this bound.
bool ownsMetric
To know whether this object allocated memory to the metric member variable.
math::RangeType< ElemType > radii
The inner and the outer radii of the bound.
Detailed Description
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double>
class mlpack::bound::HollowBallBound< TMetricType, ElemType >
Hollow ball bound encloses a set of points at a specific distance (radius) from a specific point (center) except points at a specific distance from another point (the center of the hole).
MetricType is the custom metric type that defaults to the Euclidean (L2) distance.
Template Parameters
TMetricType metric type used in the distance measure.
ElemType Type of element (float or double or similar).
Definition at line 33 of file hollow_ball_bound.hpp.
Member Typedef Documentation
MetricType
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> typedef TMetricType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MetricType
A public version of the metric type.
Definition at line 37 of file hollow_ball_bound.hpp.
Constructor & Destructor Documentation
HollowBallBound() [1/5]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowBallBound ()
Empty Constructor.
HollowBallBound() [2/5]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowBallBound (const size_t dimension)
Create the ball bound with the specified dimensionality.
Parameters
dimension Dimensionality of ball bound.
HollowBallBound() [3/5]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowBallBound (const ElemType innerRadius, const ElemType outerRadius, const VecType & center)
Create the ball bound with the specified radius and center.
Parameters
innerRadius Inner radius of ball bound.
outerRadius Outer radius of ball bound.
center Center of ball bound.
HollowBallBound() [4/5]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowBallBound (const HollowBallBound< TMetricType, ElemType > & other)
Copy constructor. To prevent memory leaks.
HollowBallBound() [5/5]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowBallBound (HollowBallBound< TMetricType, ElemType > && other)
Move constructor: take possession of another bound.
~HollowBallBound()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> mlpack::bound::HollowBallBound< TMetricType, ElemType >::~HollowBallBound ()
Destructor to release allocated memory.
Member Function Documentation
Center() [1/3]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> const arma::Col<ElemType>& mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center () const inline
Get the center point of the ball.
Definition at line 104 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::center.
Center() [2/3]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> arma::Col<ElemType>& mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center () inline
Modify the center point of the ball.
Definition at line 106 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::center.
Center() [3/3]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > void mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center (VecType & center) const inline
Place the center of BallBound into the given vector.
Parameters
center Vector which the centroid will be written to.
Definition at line 142 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::center, mlpack::bound::HollowBallBound< TMetricType, ElemType >::MaxDistance(), mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinDistance(), mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator|=(), and mlpack::bound::HollowBallBound< TMetricType, ElemType >::RangeDistance().
Contains() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > bool mlpack::bound::HollowBallBound< TMetricType, ElemType >::Contains (const VecType & point) const
Determines if a point is within this bound.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinWidth().
Contains() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> bool mlpack::bound::HollowBallBound< TMetricType, ElemType >::Contains (const HollowBallBound< TMetricType, ElemType > & other) const
Determines if another bound is within this bound.
Diameter()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::Diameter () const inline
Returns the diameter of the ballbound.
Definition at line 209 of file hollow_ball_bound.hpp.
References mlpack::math::RangeType< T >::Hi().
Dim()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> size_t mlpack::bound::HollowBallBound< TMetricType, ElemType >::Dim () const inline
Get the dimensionality of the ball.
Definition at line 114 of file hollow_ball_bound.hpp.
HollowCenter() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> const arma::Col<ElemType>& mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowCenter () const inline
Get the center point of the hollow.
Definition at line 109 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::hollowCenter.
HollowCenter() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> arma::Col<ElemType>& mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowCenter () inline
Modify the center point of the hollow.
Definition at line 111 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::hollowCenter.
InnerRadius() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::InnerRadius () const inline
Get the innner radius of the ball.
Definition at line 99 of file hollow_ball_bound.hpp.
References mlpack::math::RangeType< T >::Lo().
InnerRadius() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType& mlpack::bound::HollowBallBound< TMetricType, ElemType >::InnerRadius () inline
Modify the inner radius of the ball.
Definition at line 101 of file hollow_ball_bound.hpp.
References mlpack::math::RangeType< T >::Lo().
MaxDistance() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MaxDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >> * = 0) const
Computes maximum distance.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center().
MaxDistance() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MaxDistance (const HollowBallBound< TMetricType, ElemType > & other) const
Computes maximum distance.
Metric() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> const MetricType& mlpack::bound::HollowBallBound< TMetricType, ElemType >::Metric () const inline
Returns the distance metric used in this bound.
Definition at line 212 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::metric.
Metric() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> MetricType& mlpack::bound::HollowBallBound< TMetricType, ElemType >::Metric () inline
Modify the distance metric used in this bound.
Definition at line 214 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::metric, and mlpack::bound::HollowBallBound< TMetricType, ElemType >::Serialize().
MinDistance() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinDistance (const VecType & point, typename boost::enable_if< IsVector< VecType >> * = 0) const
Calculates minimum bound-to-point squared distance.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center().
MinDistance() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinDistance (const HollowBallBound< TMetricType, ElemType > & other) const
Calculates minimum bound-to-bound squared distance.
MinWidth()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinWidth () const inline
Get the minimum width of the bound (this is same as the diameter).
For ball bounds, width along all dimensions remain same.
Definition at line 120 of file hollow_ball_bound.hpp.
References mlpack::bound::HollowBallBound< TMetricType, ElemType >::Contains(), mlpack::math::RangeType< T >::Hi(), and mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator[]().
operator=()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> HollowBallBound& mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator= (const HollowBallBound< TMetricType, ElemType > & other)
For the same reason as the copy constructor: to prevent memory leaks.
operator[]()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator[] (const size_t i) const
Get the range in a certain dimension.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::MinWidth().
operator|=() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename MatType > const HollowBallBound& mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator|= (const MatType & data)
Expand the bound to include the given point.
The centroid will not be moved.
Template Parameters
MatType Type of matrix; could be arma::mat, arma::spmat, or a vector.
data Data points to add.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center().
operator|=() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> const HollowBallBound& mlpack::bound::HollowBallBound< TMetricType, ElemType >::operator|= (const HollowBallBound< TMetricType, ElemType > & other)
Expand the bound to include the given bound.
The centroid will not be moved.
Template Parameters
MatType Type of matrix; could be arma::mat, arma::spmat, or a vector.
data Data points to add.
OuterRadius() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType mlpack::bound::HollowBallBound< TMetricType, ElemType >::OuterRadius () const inline
Get the outer radius of the ball.
Definition at line 94 of file hollow_ball_bound.hpp.
References mlpack::math::RangeType< T >::Hi().
OuterRadius() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> ElemType& mlpack::bound::HollowBallBound< TMetricType, ElemType >::OuterRadius () inline
Modify the outer radius of the ball.
Definition at line 96 of file hollow_ball_bound.hpp.
References mlpack::math::RangeType< T >::Hi().
RangeDistance() [1/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename VecType > math::RangeType<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::RangeDistance (const VecType & other, typename boost::enable_if< IsVector< VecType >> * = 0) const
Calculates minimum and maximum bound-to-point distance.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center().
RangeDistance() [2/2]
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::RangeDistance (const HollowBallBound< TMetricType, ElemType > & other) const
Calculates minimum and maximum bound-to-bound distance.
Example: bound1.MinDistanceSq(other) for minimum distance.
Serialize()
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> template<typename Archive > void mlpack::bound::HollowBallBound< TMetricType, ElemType >::Serialize (Archive & ar, const unsigned int version)
Serialize the bound.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Metric().
Member Data Documentation
center
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> arma::Col<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::center private
The center of the ball bound.
Definition at line 43 of file hollow_ball_bound.hpp.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Center().
hollowCenter
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> arma::Col<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::hollowCenter private
The center of the hollow.
Definition at line 45 of file hollow_ball_bound.hpp.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::HollowCenter().
metric
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> MetricType* mlpack::bound::HollowBallBound< TMetricType, ElemType >::metric private
The metric used in this bound.
Definition at line 47 of file hollow_ball_bound.hpp.
Referenced by mlpack::bound::HollowBallBound< TMetricType, ElemType >::Metric().
ownsMetric
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> bool mlpack::bound::HollowBallBound< TMetricType, ElemType >::ownsMetric private
To know whether this object allocated memory to the metric member variable.
This will be true except in the copy constructor and the overloaded assignment operator. We need this to know whether we should delete the metric member variable in the destructor.
Definition at line 55 of file hollow_ball_bound.hpp.
radii
template<typename TMetricType = metric::LMetric<2, true>, typename ElemType = double> math::RangeType<ElemType> mlpack::bound::HollowBallBound< TMetricType, ElemType >::radii private
The inner and the outer radii of the bound.
Definition at line 41 of file hollow_ball_bound.hpp.
The documentation for this class was generated from the following file:
src/mlpack/core/tree/hollow_ball_bound.hpp