main
about
docs
get help
github
mlpack Namespace Reference
Linear algebra utility functions, generally performed on matrices or vectors.
Namespaces
adaboost
amf
Alternating Matrix Factorization.
ann
Artificial Neural Network.
bound
cf
Collaborative filtering.
data
Functions to load and save matrices and models.
dbscan
decision_stump
det
Density Estimation Trees.
distribution
Probability distributions.
emst
Euclidean Minimum Spanning Trees.
fastmks
Fast max-kernel search.
gmm
Gaussian Mixture Models.
hmm
Hidden Markov Models.
kernel
Kernel functions.
kmeans
K-Means clustering.
kpca
lcc
math
Miscellaneous math routines.
matrix_completion
meanshift
Mean shift clustering.
metric
naive_bayes
The Naive Bayes Classifier.
nca
Neighborhood Components Analysis.
neighbor
Neighbor-search routines.
nn
optimization
pca
perceptron
radical
range
Range-search routines.
regression
Regression methods.
sparse_coding
svd
tree
Trees and tree-building procedures.
util
Classes
class Backtrace
Provides a backtrace.
class CLI
Parses the command line for parameters and holds user-specified parameters.
class Log
Provides a convenient way to give formatted output.
struct ParamData
Aids in the extensibility of CLI by focusing potential changes into one structure.
class Timer
The timer class provides a way for mlpack methods to be timed.
class Timers
Functions
void CheckMatrices (const arma::mat &x, const arma::mat &xmlX, const arma::mat &textX, const arma::mat &binaryX)
void CheckMatrices (const arma::Mat< size_t > &x, const arma::Mat< size_t > &xmlX, const arma::Mat< size_t > &textX, const arma::Mat< size_t > &binaryX)
template
<
typename
T
,
typename
IArchiveType
,
typename
OArchiveType
>
void SerializeObject (T &t, T &newT)
template
<
typename
T
>
void SerializeObjectAll (T &t, T &xmlT, T &textT, T &binaryT)
template
<
typename
T
,
typename
IArchiveType
,
typename
OArchiveType
>
void SerializePointerObject (T *t, T *&newT)
template
<
typename
T
>
void SerializePointerObjectAll (T *t, T *&xmlT, T *&textT, T *&binaryT)
template
<
typename
CubeType
>
void TestAllArmadilloSerialization (arma::Cube< CubeType > &x)
template
<
typename
MatType
>
void TestAllArmadilloSerialization (MatType &x)
template
<
typename
CubeType
,
typename
IArchiveType
,
typename
OArchiveType
>
void TestArmadilloSerialization (arma::Cube< CubeType > &x)
template
<
typename
MatType
,
typename
IArchiveType
,
typename
OArchiveType
>
void TestArmadilloSerialization (MatType &x)
Detailed Description
Linear algebra utility functions, generally performed on matrices or vectors.
This class is used to update the weightVectors matrix according to the simple update rule as discussed by Rosenblatt:
if a vector x has been incorrectly classified by a weight w, then w = w - x and w'= w'+ x
where w' is the weight vector which correctly classifies x.
Function Documentation
CheckMatrices() [1/2]
void mlpack::CheckMatrices (const arma::mat & x, const arma::mat & xmlX, const arma::mat & textX, const arma::mat & binaryX)
Referenced by SerializePointerObjectAll().
CheckMatrices() [2/2]
void mlpack::CheckMatrices (const arma::Mat< size_t > & x, const arma::Mat< size_t > & xmlX, const arma::Mat< size_t > & textX, const arma::Mat< size_t > & binaryX)
SerializeObject()
template<typenameT,typenameIArchiveType,typenameOArchiveType> void mlpack::SerializeObject (T & t, T & newT)
Definition at line 172 of file serialization.hpp.
References mlpack::data::binary, and mlpack::data::CreateNVP().
Referenced by SerializeObjectAll().
SerializeObjectAll()
template<typenameT> void mlpack::SerializeObjectAll (T & t, T & xmlT, T & textT, T & binaryT)
Definition at line 208 of file serialization.hpp.
References SerializeObject().
SerializePointerObject()
template<typenameT,typenameIArchiveType,typenameOArchiveType> void mlpack::SerializePointerObject (T * t, T *& newT)
Definition at line 220 of file serialization.hpp.
References mlpack::data::binary, and mlpack::data::CreateNVP().
Referenced by SerializePointerObjectAll().
SerializePointerObjectAll()
template<typenameT> void mlpack::SerializePointerObjectAll (T * t, T *& xmlT, T *& textT, T *& binaryT)
Definition at line 255 of file serialization.hpp.
References CheckMatrices(), and SerializePointerObject().
TestAllArmadilloSerialization() [1/2]
template<typenameCubeType> void mlpack::TestAllArmadilloSerialization (arma::Cube< CubeType > & x)
Definition at line 93 of file serialization.hpp.
References TestArmadilloSerialization().
TestAllArmadilloSerialization() [2/2]
template<typenameMatType> void mlpack::TestAllArmadilloSerialization (MatType & x)
Definition at line 159 of file serialization.hpp.
References TestArmadilloSerialization().
TestArmadilloSerialization() [1/2]
template<typenameCubeType,typenameIArchiveType,typenameOArchiveType> void mlpack::TestArmadilloSerialization (arma::Cube< CubeType > & x)
Definition at line 33 of file serialization.hpp.
References mlpack::data::binary.
Referenced by TestAllArmadilloSerialization().
TestArmadilloSerialization() [2/2]
template<typenameMatType,typenameIArchiveType,typenameOArchiveType> void mlpack::TestArmadilloSerialization (MatType & x)
Definition at line 107 of file serialization.hpp.
References mlpack::data::binary.