mlpack: mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct Struct Reference
mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct Struct Reference
The X tree requires that the tree records it's "split history".
Public Member Functions
SplitHistoryStruct (int dim)
SplitHistoryStruct (const SplitHistoryStruct &other)
SplitHistoryStruct (SplitHistoryStruct &&other)
SplitHistoryStruct & operator= (const SplitHistoryStruct &other)
template<typename Archive >
void Serialize (Archive &ar, const unsigned int)
Public Attributes
std::vector< bool > history
int lastDimension
Detailed Description
template<typename TreeType>
struct mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct
The X tree requires that the tree records it's "split history".
To make this easy, we use the following structure.
Definition at line 169 of file x_tree_auxiliary_information.hpp.
Constructor & Destructor Documentation
SplitHistoryStruct() [1/3]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::SplitHistoryStruct (int dim) inline
Definition at line 174 of file x_tree_auxiliary_information.hpp.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::Serialize().
SplitHistoryStruct() [2/3]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::SplitHistoryStruct (const SplitHistoryStruct & other) inline
Definition at line 180 of file x_tree_auxiliary_information.hpp.
SplitHistoryStruct() [3/3]
template<typename TreeType > mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::SplitHistoryStruct (SplitHistoryStruct && other) inline
Definition at line 192 of file x_tree_auxiliary_information.hpp.
Member Function Documentation
operator=()
template<typename TreeType > SplitHistoryStruct& mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::operator= (const SplitHistoryStruct & other) inline
Definition at line 185 of file x_tree_auxiliary_information.hpp.
References mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::history, and mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::lastDimension.
Serialize()
template<typename TreeType > template<typename Archive > void mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::Serialize (Archive & ar, const unsigned int) inline
Definition at line 200 of file x_tree_auxiliary_information.hpp.
References mlpack::data::CreateNVP(), and mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::SplitHistoryStruct().
Member Data Documentation
history
template<typename TreeType > std::vector<bool> mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::history
Definition at line 172 of file x_tree_auxiliary_information.hpp.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::operator=().
lastDimension
template<typename TreeType > int mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::lastDimension
Definition at line 171 of file x_tree_auxiliary_information.hpp.
Referenced by mlpack::tree::XTreeAuxiliaryInformation< TreeType >::SplitHistoryStruct::operator=().
The documentation for this struct was generated from the following file:
src/mlpack/core/tree/rectangle_tree/x_tree_auxiliary_information.hpp