main
about
docs
get help
github
mlpack::optimization::AugLagrangianTestFunction Class Reference
This function is taken from "Practical Mathematical Optimization" (Snyman), section 5.3.8 ("Application of the Augmented Lagrangian Method").
Public Member Functions
AugLagrangianTestFunction ()
AugLagrangianTestFunction (const arma::mat &initial_point)
double Evaluate (const arma::mat &coordinates)
double EvaluateConstraint (const size_t index, const arma::mat &coordinates)
const arma::mat & GetInitialPoint () const
void Gradient (const arma::mat &coordinates, arma::mat &gradient)
void GradientConstraint (const size_t index, const arma::mat &coordinates, arma::mat &gradient)
size_t NumConstraints () const
Private Attributes
arma::mat initialPoint
Detailed Description
This function is taken from "Practical Mathematical Optimization" (Snyman), section 5.3.8 ("Application of the Augmented Lagrangian Method").
It has only one constraint.
The minimum that satisfies the constraint is x = [1, 4], with an objective value of 70.
Definition at line 38 of file aug_lagrangian_test_functions.hpp.
Constructor & Destructor Documentation
AugLagrangianTestFunction() [1/2]
mlpack::optimization::AugLagrangianTestFunction::AugLagrangianTestFunction ()
AugLagrangianTestFunction() [2/2]
mlpack::optimization::AugLagrangianTestFunction::AugLagrangianTestFunction (const arma::mat & initial_point)
Member Function Documentation
Evaluate()
double mlpack::optimization::AugLagrangianTestFunction::Evaluate (const arma::mat & coordinates)
EvaluateConstraint()
double mlpack::optimization::AugLagrangianTestFunction::EvaluateConstraint (const size_t index, const arma::mat & coordinates)
Referenced by NumConstraints(), and mlpack::optimization::GockenbachFunction::NumConstraints().
GetInitialPoint()
const arma::mat& mlpack::optimization::AugLagrangianTestFunction::GetInitialPoint () const inline
Definition at line 54 of file aug_lagrangian_test_functions.hpp.
References initialPoint.
Gradient()
void mlpack::optimization::AugLagrangianTestFunction::Gradient (const arma::mat & coordinates, arma::mat & gradient)
GradientConstraint()
void mlpack::optimization::AugLagrangianTestFunction::GradientConstraint (const size_t index, const arma::mat & coordinates, arma::mat & gradient)
Referenced by NumConstraints(), and mlpack::optimization::GockenbachFunction::NumConstraints().
NumConstraints()
size_t mlpack::optimization::AugLagrangianTestFunction::NumConstraints () const inline
Definition at line 47 of file aug_lagrangian_test_functions.hpp.
References EvaluateConstraint(), and GradientConstraint().
Member Data Documentation
initialPoint
arma::mat mlpack::optimization::AugLagrangianTestFunction::initialPoint private
Definition at line 57 of file aug_lagrangian_test_functions.hpp.
Referenced by GetInitialPoint(), and mlpack::optimization::GockenbachFunction::GetInitialPoint().
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/aug_lagrangian/aug_lagrangian_test_functions.hpp