main
about
docs
get help
github
mlpack::distribution::GaussianDistribution Class Reference
A single multivariate Gaussian distribution.
Public Member Functions
GaussianDistribution ()
Default constructor, which creates a Gaussian with zero dimension.
GaussianDistribution (const size_t dimension)
Create a Gaussian distribution with zero mean and identity covariance with the given dimensionality.
GaussianDistribution (const arma::vec &mean, const arma::mat &covariance)
Create a Gaussian distribution with the given mean and covariance.
const arma::mat & Covariance () const
Return the covariance matrix.
void Covariance (const arma::mat &covariance)
Set the covariance.
void Covariance (arma::mat &&covariance)
size_t Dimensionality () const
Return the dimensionality of this distribution.
double LogProbability (const arma::vec &observation) const
Return the log probability of the given observation.
void LogProbability (const arma::mat &x, arma::vec &logProbabilities) const
Calculates the multivariate Gaussian log probability density function for each data point (column) in the given matrix.
const arma::vec & Mean () const
Return the mean.
arma::vec & Mean ()
Return a modifiable copy of the mean.
double Probability (const arma::vec &observation) const
Return the probability of the given observation.
void Probability (const arma::mat &x, arma::vec &probabilities) const
Calculates the multivariate Gaussian probability density function for each data point (column) in the given matrix.
arma::vec Random () const
Return a randomly generated observation according to the probability distribution defined by this object.
template
<
typename
Archive
>
void Serialize (Archive &ar, const unsigned int)
Serialize the distribution.
void Train (const arma::mat &observations)
Estimate the Gaussian distribution directly from the given observations.
void Train (const arma::mat &observations, const arma::vec &probabilities)
Estimate the Gaussian distribution from the given observations, taking into account the probability of each observation actually being from this distribution.
Private Member Functions
void FactorCovariance ()
This factors the covariance using arma::chol().
Private Attributes
arma::mat covariance
Positive definite covariance of the distribution.
arma::mat covLower
Lower triangular factor of cov (e.g. cov = LL^T).
arma::mat invCov
Cached inverse of covariance.
double logDetCov
Cached logdet(cov).
arma::vec mean
Mean of the distribution.
Static Private Attributes
static const constexpr double log2pi = 1.83787706640934533908193770912475883
log(2pi)
Detailed Description
A single multivariate Gaussian distribution.
Definition at line 34 of file gaussian_distribution.hpp.
Constructor & Destructor Documentation
GaussianDistribution() [1/3]
mlpack::distribution::GaussianDistribution::GaussianDistribution () inline
Default constructor, which creates a Gaussian with zero dimension.
Definition at line 55 of file gaussian_distribution.hpp.
Referenced by GaussianDistribution().
GaussianDistribution() [2/3]
mlpack::distribution::GaussianDistribution::GaussianDistribution (const size_t dimension) inline
Create a Gaussian distribution with zero mean and identity covariance with the given dimensionality.
Definition at line 61 of file gaussian_distribution.hpp.
References GaussianDistribution().
GaussianDistribution() [3/3]
mlpack::distribution::GaussianDistribution::GaussianDistribution (const arma::vec & mean, const arma::mat & covariance)
Create a Gaussian distribution with the given mean and covariance.
covariance is expected to be positive definite.
Member Function Documentation
Covariance() [1/3]
const arma::mat& mlpack::distribution::GaussianDistribution::Covariance () const inline
Return the covariance matrix.
Definition at line 146 of file gaussian_distribution.hpp.
References covariance.
Referenced by mlpack::distribution::RegressionDistribution::RegressionDistribution().
Covariance() [2/3]
void mlpack::distribution::GaussianDistribution::Covariance (const arma::mat & covariance)
Set the covariance.
Covariance() [3/3]
void mlpack::distribution::GaussianDistribution::Covariance (arma::mat && covariance)
Dimensionality()
size_t mlpack::distribution::GaussianDistribution::Dimensionality () const inline
Return the dimensionality of this distribution.
Definition at line 79 of file gaussian_distribution.hpp.
FactorCovariance()
void mlpack::distribution::GaussianDistribution::FactorCovariance () private
This factors the covariance using arma::chol().
The function assumes that the given matrix is factorizable via the Cholesky decomposition. If not, a std::runtime_error will be thrown.
Referenced by Serialize().
LogProbability() [1/2]
double mlpack::distribution::GaussianDistribution::LogProbability (const arma::vec & observation) const
Return the log probability of the given observation.
Referenced by Probability().
LogProbability() [2/2]
void mlpack::distribution::GaussianDistribution::LogProbability (const arma::mat & x, arma::vec & logProbabilities) const inline
Calculates the multivariate Gaussian log probability density function for each data point (column) in the given matrix.
Parameters
x List of observations.
probabilities Output log probabilities for each input observation.
Definition at line 187 of file gaussian_distribution.hpp.
References invCov, log2pi, logDetCov, and mean.
Mean() [1/2]
const arma::vec& mlpack::distribution::GaussianDistribution::Mean () const inline
Return the mean.
Definition at line 136 of file gaussian_distribution.hpp.
References mean.
Mean() [2/2]
arma::vec& mlpack::distribution::GaussianDistribution::Mean () inline
Return a modifiable copy of the mean.
Definition at line 141 of file gaussian_distribution.hpp.
References mean.
Probability() [1/2]
double mlpack::distribution::GaussianDistribution::Probability (const arma::vec & observation) const inline
Return the probability of the given observation.
Definition at line 84 of file gaussian_distribution.hpp.
References LogProbability().
Probability() [2/2]
void mlpack::distribution::GaussianDistribution::Probability (const arma::mat & x, arma::vec & probabilities) const inline
Calculates the multivariate Gaussian probability density function for each data point (column) in the given matrix.
Parameters
x List of observations.
probabilities Output probabilities for each input observation.
Definition at line 101 of file gaussian_distribution.hpp.
References LogProbability(), Random(), and Train().
Random()
arma::vec mlpack::distribution::GaussianDistribution::Random () const
Return a randomly generated observation according to the probability distribution defined by this object.
Returns
Random observation from this Gaussian distribution.
Referenced by Probability().
Serialize()
template<typenameArchive> void mlpack::distribution::GaussianDistribution::Serialize (Archive & ar, const unsigned int) inline
Serialize the distribution.
Definition at line 159 of file gaussian_distribution.hpp.
References mlpack::data::CreateNVP(), and FactorCovariance().
Train() [1/2]
void mlpack::distribution::GaussianDistribution::Train (const arma::mat & observations)
Estimate the Gaussian distribution directly from the given observations.
Parameters
observations List of observations.
Referenced by Probability().
Train() [2/2]
void mlpack::distribution::GaussianDistribution::Train (const arma::mat & observations, const arma::vec & probabilities)
Estimate the Gaussian distribution from the given observations, taking into account the probability of each observation actually being from this distribution.
Member Data Documentation
covariance
arma::mat mlpack::distribution::GaussianDistribution::covariance private
Positive definite covariance of the distribution.
Definition at line 40 of file gaussian_distribution.hpp.
Referenced by Covariance().
covLower
arma::mat mlpack::distribution::GaussianDistribution::covLower private
Lower triangular factor of cov (e.g. cov = LL^T).
Definition at line 42 of file gaussian_distribution.hpp.
invCov
arma::mat mlpack::distribution::GaussianDistribution::invCov private
Cached inverse of covariance.
Definition at line 44 of file gaussian_distribution.hpp.
Referenced by LogProbability().
log2pi
const constexpr double mlpack::distribution::GaussianDistribution::log2pi = 1.83787706640934533908193770912475883 static private
log(2pi)
Definition at line 49 of file gaussian_distribution.hpp.
Referenced by LogProbability().
logDetCov
double mlpack::distribution::GaussianDistribution::logDetCov private
Cached logdet(cov).
Definition at line 46 of file gaussian_distribution.hpp.
Referenced by LogProbability().
mean
arma::vec mlpack::distribution::GaussianDistribution::mean private
Mean of the distribution.
Definition at line 38 of file gaussian_distribution.hpp.
Referenced by LogProbability(), and Mean().
The documentation for this class was generated from the following file:
src/mlpack/core/dists/gaussian_distribution.hpp