main
about
docs
get help
github
mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::SortEdgesHelper Struct Reference
For sorting the edge list after the computation.
Public Member Functions
bool operator() (const EdgePair &pairA, const EdgePair &pairB)
Detailed Description
template
<
typename
MetricType
=
metric::EuclideanDistance
,
typename
MatType
=
arma::mat
,
template
<
typename
TreeMetricType
,
typename
TreeStatType
,
typename
TreeMatType
>
class
TreeType
=
tree::KDTree
>
struct mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::SortEdgesHelper
For sorting the edge list after the computation.
Definition at line 132 of file dtb.hpp.
Member Function Documentation
operator()()
template<typenameMetricType=metric::EuclideanDistance,typenameMatType=arma::mat,template<typenameTreeMetricType,typenameTreeStatType,typenameTreeMatType>classTreeType=tree::KDTree> bool mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::SortEdgesHelper::operator() (const EdgePair & pairA, const EdgePair & pairB) inline
Definition at line 134 of file dtb.hpp.
References mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::AddAllEdges(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::AddEdge(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::Cleanup(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::CleanupHelper(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::ComputeMST(), mlpack::emst::EdgePair::Distance(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::DualTreeBoruvka(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::EmitResults(), mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::SortFun, and mlpack::emst::DualTreeBoruvka< MetricType, MatType, TreeType >::~DualTreeBoruvka().
The documentation for this struct was generated from the following file:
src/mlpack/methods/emst/dtb.hpp