main
about
docs
get help
github
mlpack::regression::LARS Class Reference
An implementation of LARS, a stage-wise homotopy-based algorithm for l1 regularized linear regression (LASSO) and l1+l2 regularized linear regression (Elastic Net).
Public Member Functions
LARS (const bool useCholesky)
Set the parameters to LARS.
LARS (const bool useCholesky, const double lambda1)
Set the parameters to LARS.
LARS (const bool useCholesky, const double lambda1, const double lambda2)
Set the parameters to LARS.
~LARS ()
const std::vector< arma::uword > & ActiveSet () const
Accessor for activeSet.
const std::vector< arma::vec > & BetaPath () const
Accessor for betaPath.
void ComputeGram (const arma::mat &matX)
Compute Gram matrix.
void DoLARS (const arma::mat &matX, const arma::vec &y)
Run LARS.
const std::vector< double > & LambdaPath () const
Accessor for lambdaPath.
const arma::mat & MatUtriCholFactor () const
Accessor for matUtriCholFactor.
void SetGram (const arma::mat &matGram)
Set the Gram matrix (done before calling DoLars).
void Solution (arma::vec &beta)
Private Member Functions
void Activate (arma::uword varInd)
void CholeskyDelete (arma::uword colToKill)
void CholeskyInsert (const arma::vec &newX, const arma::mat &X)
void CholeskyInsert (const arma::vec &newX, const arma::vec &newGramCol)
void ComputeYHatDirection (const arma::mat &matX, const arma::vec &betaDirection, arma::vec &yHatDirection)
void Deactivate (arma::uword activeVarInd)
void GivensRotate (const arma::vec &x, arma::vec &rotatedX, arma::mat &G)
void InterpolateBeta ()
Private Attributes
std::vector< arma::uword > activeSet
std::vector< arma::vec > betaPath
bool elasticNet
std::vector< bool > isActive
double lambda1
double lambda2
std::vector< double > lambdaPath
bool lasso
arma::mat matGram
arma::mat matUtriCholFactor
arma::uword nActive
bool useCholesky
Detailed Description
An implementation of LARS, a stage-wise homotopy-based algorithm for l1 regularized linear regression (LASSO) and l1+l2 regularized linear regression (Elastic Net).
Let X be a matrix where each row is a point and each column is a dimension, and let y be a vector of targets. The Elastic Net problem is to solve min_beta 0.5 ||X beta - y||_2^2 + lambda_1 ||beta||_1 + 0.5 lambda_2 ||beta||_2^2 If lambda_1 > 0, lambda_2 = 0, the problem is the LASSO. If lambda_1 > 0, lambda_2 > 0, the problem is the Elastic Net. If lambda_1 = 0, lambda_2 > 0, the problem is Ridge Regression. If lambda_1 = 0, lambda_2 = 0, the problem is unregularized linear regression.
Note: This algorithm is not recommended for use (in terms of efficiency) when lambda_1 = 0.
Only minor modifications are necessary to handle the constrained version of the problem: min_beta 0.5 ||X beta - y||_2^2 + 0.5 lambda_2 ||beta||_2^2 subject to ||beta||_1 <= tau Although this option currently is not implemented, it will be implemented very soon.
For more details, see the following papers:
@article{efron2004least,
  title={Least angle regression},
  author={Efron, B. and Hastie, T. and Johnstone, I. and Tibshirani, R.},
  journal={The Annals of statistics},
  volume={32},
  number={2},
  pages={407--499},
  year={2004},
  publisher={Institute of Mathematical Statistics}
}
@article{zou2005regularization,
  title={Regularization and variable selection via the elastic net},
  author={Zou, H. and Hastie, T.},
  journal={Journal of the Royal Statistical Society Series B},
  volume={67},
  number={2},
  pages={301--320},
  year={2005},
  publisher={Royal Statistical Society}
}
Definition at line 74 of file lars.hpp.
Constructor & Destructor Documentation
LARS() [1/3]
mlpack::regression::LARS::LARS (const bool useCholesky)
Set the parameters to LARS.
Both lambda1 and lambda2 default to 0.
Parameters
useCholesky Whether or not to use Cholesky decomposition when solving linear system. If no, compute full Gram matrix at beginning.
LARS() [2/3]
mlpack::regression::LARS::LARS (const bool useCholesky, const double lambda1)
Set the parameters to LARS.
lambda2 defaults to 0.
Parameters
useCholesky Whether or not to use Cholesky decomposition when solving linear system. If no, compute full Gram matrix at beginning.
lambda1 Regularization parameter for l_1-norm penalty
LARS() [3/3]
mlpack::regression::LARS::LARS (const bool useCholesky, const double lambda1, const double lambda2)
Set the parameters to LARS.
Parameters
useCholesky Whether or not to use Cholesky decomposition when solving linear system. If no, compute full Gram matrix at beginning.
lambda1 Regularization parameter for l_1-norm penalty
lambda2 Regularization parameter for l_2-norm penalty
~LARS()
mlpack::regression::LARS::~LARS () inline
Definition at line 107 of file lars.hpp.
References ComputeGram(), DoLARS(), matGram, SetGram(), and Solution().
Member Function Documentation
Activate()
void mlpack::regression::LARS::Activate (arma::uword varInd) private
ActiveSet()
const std::vector<arma::uword>& mlpack::regression::LARS::ActiveSet () const inline
Accessor for activeSet.
Definition at line 138 of file lars.hpp.
References activeSet.
BetaPath()
const std::vector<arma::vec>& mlpack::regression::LARS::BetaPath () const inline
Accessor for betaPath.
Definition at line 141 of file lars.hpp.
References betaPath.
CholeskyDelete()
void mlpack::regression::LARS::CholeskyDelete (arma::uword colToKill) private
CholeskyInsert() [1/2]
void mlpack::regression::LARS::CholeskyInsert (const arma::vec & newX, const arma::mat & X) private
CholeskyInsert() [2/2]
void mlpack::regression::LARS::CholeskyInsert (const arma::vec & newX, const arma::vec & newGramCol) private
ComputeGram()
void mlpack::regression::LARS::ComputeGram (const arma::mat & matX)
Compute Gram matrix.
If elastic net, add lambda2 * identity to diagonal.
Parameters
matX Data matrix to use for computing Gram matrix
Referenced by ~LARS().
ComputeYHatDirection()
void mlpack::regression::LARS::ComputeYHatDirection (const arma::mat & matX, const arma::vec & betaDirection, arma::vec & yHatDirection) private
Deactivate()
void mlpack::regression::LARS::Deactivate (arma::uword activeVarInd) private
DoLARS()
void mlpack::regression::LARS::DoLARS (const arma::mat & matX, const arma::vec & y)
Run LARS.
Parameters
matX Input data into the algorithm - a matrix where each row is a point and each column is a dimension
y A vector of targets
Referenced by ~LARS().
GivensRotate()
void mlpack::regression::LARS::GivensRotate (const arma::vec & x, arma::vec & rotatedX, arma::mat & G) private
InterpolateBeta()
void mlpack::regression::LARS::InterpolateBeta () private
LambdaPath()
const std::vector<double>& mlpack::regression::LARS::LambdaPath () const inline
Accessor for lambdaPath.
Definition at line 144 of file lars.hpp.
References lambdaPath.
MatUtriCholFactor()
const arma::mat& mlpack::regression::LARS::MatUtriCholFactor () const inline
Accessor for matUtriCholFactor.
Definition at line 147 of file lars.hpp.
References matUtriCholFactor.
SetGram()
void mlpack::regression::LARS::SetGram (const arma::mat & matGram)
Set the Gram matrix (done before calling DoLars).
Parameters
matGram Matrix to which to set Gram matrix
Referenced by ~LARS().
Solution()
void mlpack::regression::LARS::Solution (arma::vec & beta)
Referenced by ~LARS().
Member Data Documentation
activeSet
std::vector<arma::uword> mlpack::regression::LARS::activeSet private
Definition at line 174 of file lars.hpp.
Referenced by ActiveSet().
betaPath
std::vector<arma::vec> mlpack::regression::LARS::betaPath private
Definition at line 165 of file lars.hpp.
Referenced by BetaPath().
elasticNet
bool mlpack::regression::LARS::elasticNet private
Definition at line 161 of file lars.hpp.
isActive
std::vector<bool> mlpack::regression::LARS::isActive private
Definition at line 177 of file lars.hpp.
lambda1
double mlpack::regression::LARS::lambda1 private
Definition at line 159 of file lars.hpp.
lambda2
double mlpack::regression::LARS::lambda2 private
Definition at line 162 of file lars.hpp.
lambdaPath
std::vector<double> mlpack::regression::LARS::lambdaPath private
Definition at line 168 of file lars.hpp.
Referenced by LambdaPath().
lasso
bool mlpack::regression::LARS::lasso private
Definition at line 158 of file lars.hpp.
matGram
arma::mat mlpack::regression::LARS::matGram private
Definition at line 151 of file lars.hpp.
Referenced by ~LARS().
matUtriCholFactor
arma::mat mlpack::regression::LARS::matUtriCholFactor private
Definition at line 154 of file lars.hpp.
Referenced by MatUtriCholFactor().
nActive
arma::uword mlpack::regression::LARS::nActive private
Definition at line 171 of file lars.hpp.
useCholesky
bool mlpack::regression::LARS::useCholesky private
Definition at line 156 of file lars.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/lars/lars.hpp