main
about
docs
get help
github
mlpack::lcc::LocalCoordinateCoding Class Reference
An implementation of Local Coordinate Coding (LCC) that codes data which approximately lives on a manifold using a variation of l1-norm regularized sparse coding; in LCC, the penalty on the absolute value of each point's coefficient for each atom is weighted by the squared distance of that point to that atom.
Public Member Functions
LocalCoordinateCoding (const arma::mat &matX, arma::uword nAtoms, double lambda)
Set the parameters to LocalCoordinateCoding.
void DataDependentRandomInitDictionary ()
Initialize dictionary by initializing each atom to a normalized mixture of a small number of randomly selected points in X.
void DoLCC (arma::uword nIterations)
Run LCC.
void InitDictionary ()
Initialize dictionary somehow.
void LoadDictionary (const char *dictionaryFilename)
Load dictionary from a file.
const arma::mat & MatD ()
Accessor for matD.
const arma::mat & MatZ ()
Accessor for matZ.
double Objective (arma::uvec adjacencies)
Compute objective function.
void OptimizeCode ()
Sparse code each point via distance-weighted LARS.
void OptimizeDictionary (arma::uvec adjacencies)
Learn dictionary by solving linear systemx.
void PrintCoding ()
void PrintDictionary ()
void RandomAtom (arma::vec &atom)
Initialize an atom to a normalized mixture of a small number of randomly selected points in X.
void RandomInitDictionary ()
Initialize dictionary by drawing k vectors uniformly at random from the unit sphere.
void SetDictionary (const arma::mat &matD)
Modifier for matD.
Private Attributes
double lambda
arma::mat matD
arma::mat matX
arma::mat matZ
arma::uword nAtoms
arma::uword nDims
arma::uword nPoints
Detailed Description
An implementation of Local Coordinate Coding (LCC) that codes data which approximately lives on a manifold using a variation of l1-norm regularized sparse coding; in LCC, the penalty on the absolute value of each point's coefficient for each atom is weighted by the squared distance of that point to that atom.
The paper is below. Let d be the number of dimensions in the original space, m the number of training points, and k the number of atoms in the dictionary (the dimension of the learned feature space). The training data X is a d-by-m matrix where each column is a point and each row is a dimension. The dictionary D is a d-by-k matrix, and the sparse codes matrix Z is a k-by-m matrix. This program seeks to minimize the objective: min_{D,Z} ||X - D Z||_{Fro}^2
lambda sum_{i=1}^m sum_{j=1}^k dist(X_i,D_j)^2 Z_i^j where lambda > 0.
This problem is solved by an algorithm that alternates between a dictionary learning step and a sparse coding step. The dictionary learning step updates the dictionary D by solving a linear system (note that the objective is a positive definite quadratic program). The sparse coding step involves solving a large number of weighted l1-norm regularized linear regression problems problems; this can be done efficiently using LARS, an algorithm that can solve the LASSO (paper below).
The papers:
{NIPS2009_0719, title = {Nonlinear Learning using Local Coordinate Coding}, author = {Kai Yu and Tong Zhang and Yihong Gong}, booktitle = {Advances in Neural Information Processing Systems 22}, editor = {Y. Bengio and D. Schuurmans and J. Lafferty and C. K. I. Williams and A. Culotta}, pages = {2223–2231}, year = {2009} }
@article{efron2004least,
  title={Least angle regression},
  author={Efron, B. and Hastie, T. and Johnstone, I. and Tibshirani, R.},
  journal={The Annals of statistics},
  volume={32},
  number={2},
  pages={407--499},
  year={2004},
  publisher={Institute of Mathematical Statistics}
}
Definition at line 68 of file lcc.hpp.
Constructor & Destructor Documentation
LocalCoordinateCoding()
mlpack::lcc::LocalCoordinateCoding::LocalCoordinateCoding (const arma::mat & matX, arma::uword nAtoms, double lambda)
Set the parameters to LocalCoordinateCoding.
Parameters
matX Data matrix
nAtoms Number of atoms in dictionary
lambda Regularization parameter for weighted l1-norm penalty
Member Function Documentation
DataDependentRandomInitDictionary()
void mlpack::lcc::LocalCoordinateCoding::DataDependentRandomInitDictionary ()
Initialize dictionary by initializing each atom to a normalized mixture of a small number of randomly selected points in X.
DoLCC()
void mlpack::lcc::LocalCoordinateCoding::DoLCC (arma::uword nIterations)
Run LCC.
Parameters
nIterations Maximum number of iterations to run algorithm
InitDictionary()
void mlpack::lcc::LocalCoordinateCoding::InitDictionary ()
Initialize dictionary somehow.
LoadDictionary()
void mlpack::lcc::LocalCoordinateCoding::LoadDictionary (const char * dictionaryFilename)
Load dictionary from a file.
Parameters
dictionaryFilename Filename containing dictionary
MatD()
const arma::mat& mlpack::lcc::LocalCoordinateCoding::MatD () inline
Accessor for matD.
Definition at line 151 of file lcc.hpp.
References matD.
MatZ()
const arma::mat& mlpack::lcc::LocalCoordinateCoding::MatZ () inline
Accessor for matZ.
Definition at line 156 of file lcc.hpp.
References matZ, PrintCoding(), and PrintDictionary().
Objective()
double mlpack::lcc::LocalCoordinateCoding::Objective (arma::uvec adjacencies)
Compute objective function.
OptimizeCode()
void mlpack::lcc::LocalCoordinateCoding::OptimizeCode ()
Sparse code each point via distance-weighted LARS.
OptimizeDictionary()
void mlpack::lcc::LocalCoordinateCoding::OptimizeDictionary (arma::uvec adjacencies)
Learn dictionary by solving linear systemx.
Parameters
adjacencies Indices of entries (unrolled column by column) of the coding matrix Z that are non-zero (the adjacency matrix for the bipartite graph of points and atoms)
PrintCoding()
void mlpack::lcc::LocalCoordinateCoding::PrintCoding ()
Referenced by MatZ().
PrintDictionary()
void mlpack::lcc::LocalCoordinateCoding::PrintDictionary ()
Referenced by MatZ().
RandomAtom()
void mlpack::lcc::LocalCoordinateCoding::RandomAtom (arma::vec & atom)
Initialize an atom to a normalized mixture of a small number of randomly selected points in X.
Parameters
atom The atom to initialize
RandomInitDictionary()
void mlpack::lcc::LocalCoordinateCoding::RandomInitDictionary ()
Initialize dictionary by drawing k vectors uniformly at random from the unit sphere.
SetDictionary()
void mlpack::lcc::LocalCoordinateCoding::SetDictionary (const arma::mat & matD)
Modifier for matD.
Member Data Documentation
lambda
double mlpack::lcc::LocalCoordinateCoding::lambda private
Definition at line 182 of file lcc.hpp.
matD
arma::mat mlpack::lcc::LocalCoordinateCoding::matD private
Definition at line 176 of file lcc.hpp.
Referenced by MatD().
matX
arma::mat mlpack::lcc::LocalCoordinateCoding::matX private
Definition at line 173 of file lcc.hpp.
matZ
arma::mat mlpack::lcc::LocalCoordinateCoding::matZ private
Definition at line 179 of file lcc.hpp.
Referenced by MatZ().
nAtoms
arma::uword mlpack::lcc::LocalCoordinateCoding::nAtoms private
Definition at line 169 of file lcc.hpp.
nDims
arma::uword mlpack::lcc::LocalCoordinateCoding::nDims private
Definition at line 168 of file lcc.hpp.
nPoints
arma::uword mlpack::lcc::LocalCoordinateCoding::nPoints private
Definition at line 170 of file lcc.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/local_coordinate_coding/lcc.hpp