main
about
docs
get help
github
mlpack::sparse_coding::SparseCoding Class Reference
An implementation of Sparse Coding with Dictionary Learning that achieves sparsity via an l1-norm regularizer on the codes (LASSO) or an (l1+l2)-norm regularizer on the codes (the Elastic Net).
Public Member Functions
SparseCoding (const arma::mat &matX, arma::uword nAtoms, double lambda1, double lambda2=0)
Set the parameters to SparseCoding.
void DataDependentRandomInitDictionary ()
Initialize dictionary by initializing each atom to a normalized mixture of a small number of randomly selected points in X.
void DoSparseCoding (arma::uword nIterations)
Run Sparse Coding with Dictionary Learning.
void InitDictionary ()
Initialize dictionary somehow.
void LoadDictionary (const char *dictionaryFilename)
Load dictionary from a file.
const arma::mat & MatD ()
Accessor for matD.
const arma::mat & MatZ ()
Accessor for matZ.
double Objective ()
Compute objective function.
void OptimizeCode ()
Sparse code each point via LARS.
void OptimizeDictionary (arma::uvec adjacencies)
Learn dictionary via Newton method based on Lagrange dual.
void PrintCoding ()
void PrintDictionary ()
void ProjectDictionary ()
Project each atom of the dictionary onto the unit ball.
void RandomAtom (arma::vec &atom)
Initialize an atom to a normalized mixture of a small number of randomly selected points in X.
void RandomInitDictionary ()
Initialize dictionary by drawing k vectors uniformly at random from the unit sphere.
void SetData (const arma::mat &matX)
Modifier for matX.
void SetDictionary (const arma::mat &matD)
Modifier for matD.
Private Attributes
double lambda1
double lambda2
arma::mat matD
arma::mat matX
arma::mat matZ
arma::uword nAtoms
arma::uword nDims
arma::uword nPoints
Detailed Description
An implementation of Sparse Coding with Dictionary Learning that achieves sparsity via an l1-norm regularizer on the codes (LASSO) or an (l1+l2)-norm regularizer on the codes (the Elastic Net).
Let d be the number of dimensions in the original space, m the number of training points, and k the number of atoms in the dictionary (the dimension of the learned feature space). The training data X is a d-by-m matrix where each column is a point and each row is a dimension. The dictionary D is a d-by-k matrix, and the sparse codes matrix Z is a k-by-m matrix. This program seeks to minimize the objective: min_{D,Z} 0.5 ||X - D Z||_{Fro}^2\ + lambda_1 sum_{i=1}^m ||Z_i||_1
0.5 lambda_2 sum_{i=1}^m ||Z_i||_2^2 subject to ||D_j||_2 <= 1 for 1 <= j <= k where typically lambda_1 > 0 and lambda_2 = 0.
This problem is solved by an algorithm that alternates between a dictionary learning step and a sparse coding step. The dictionary learning step updates the dictionary D using a Newton method based on the Lagrange dual (see the paper below for details). The sparse coding step involves solving a large number of sparse linear regression problems; this can be done efficiently using LARS, an algorithm that can solve the LASSO or the Elastic Net (papers below).
Here are those papers:
@incollection{lee2007efficient,
  title = {Efficient sparse coding algorithms},
  author = {Honglak Lee and Alexis Battle and Rajat Raina and Andrew Y. Ng},
  booktitle = {Advances in Neural Information Processing Systems 19},
  editor = {B. Sch\"{o}lkopf and J. Platt and T. Hoffman},
  publisher = {MIT Press},
  address = {Cambridge, MA},
  pages = {801--808},
  year = {2007}
}
@article{efron2004least,
  title={Least angle regression},
  author={Efron, B. and Hastie, T. and Johnstone, I. and Tibshirani, R.},
  journal={The Annals of statistics},
  volume={32},
  number={2},
  pages={407--499},
  year={2004},
  publisher={Institute of Mathematical Statistics}
}
@article{zou2005regularization,
  title={Regularization and variable selection via the elastic net},
  author={Zou, H. and Hastie, T.},
  journal={Journal of the Royal Statistical Society Series B},
  volume={67},
  number={2},
  pages={301--320},
  year={2005},
  publisher={Royal Statistical Society}
}
Definition at line 82 of file sparse_coding.hpp.
Constructor & Destructor Documentation
SparseCoding()
mlpack::sparse_coding::SparseCoding::SparseCoding (const arma::mat & matX, arma::uword nAtoms, double lambda1, double lambda2 = 0)
Set the parameters to SparseCoding.
lambda2 defaults to 0.
Parameters
matX Data matrix
nAtoms Number of atoms in dictionary
lambda1 Regularization parameter for l1-norm penalty
lambda2 Regularization parameter for l2-norm penalty
Member Function Documentation
DataDependentRandomInitDictionary()
void mlpack::sparse_coding::SparseCoding::DataDependentRandomInitDictionary ()
Initialize dictionary by initializing each atom to a normalized mixture of a small number of randomly selected points in X.
DoSparseCoding()
void mlpack::sparse_coding::SparseCoding::DoSparseCoding (arma::uword nIterations)
Run Sparse Coding with Dictionary Learning.
Parameters
nIterations Maximum number of iterations to run algorithm
InitDictionary()
void mlpack::sparse_coding::SparseCoding::InitDictionary ()
Initialize dictionary somehow.
LoadDictionary()
void mlpack::sparse_coding::SparseCoding::LoadDictionary (const char * dictionaryFilename)
Load dictionary from a file.
Parameters
dictionaryFilename Filename containing dictionary
MatD()
const arma::mat& mlpack::sparse_coding::SparseCoding::MatD () inline
Accessor for matD.
Definition at line 178 of file sparse_coding.hpp.
References matD.
MatZ()
const arma::mat& mlpack::sparse_coding::SparseCoding::MatZ () inline
Accessor for matZ.
Definition at line 183 of file sparse_coding.hpp.
References matZ, PrintCoding(), and PrintDictionary().
Objective()
double mlpack::sparse_coding::SparseCoding::Objective ()
Compute objective function.
OptimizeCode()
void mlpack::sparse_coding::SparseCoding::OptimizeCode ()
Sparse code each point via LARS.
OptimizeDictionary()
void mlpack::sparse_coding::SparseCoding::OptimizeDictionary (arma::uvec adjacencies)
Learn dictionary via Newton method based on Lagrange dual.
Parameters
adjacencies Indices of entries (unrolled column by column) of the coding matrix Z that are non-zero (the adjacency matrix for the bipartite graph of points and atoms)
PrintCoding()
void mlpack::sparse_coding::SparseCoding::PrintCoding ()
Referenced by MatZ().
PrintDictionary()
void mlpack::sparse_coding::SparseCoding::PrintDictionary ()
Referenced by MatZ().
ProjectDictionary()
void mlpack::sparse_coding::SparseCoding::ProjectDictionary ()
Project each atom of the dictionary onto the unit ball.
RandomAtom()
void mlpack::sparse_coding::SparseCoding::RandomAtom (arma::vec & atom)
Initialize an atom to a normalized mixture of a small number of randomly selected points in X.
Parameters
atom The atom to initialize
RandomInitDictionary()
void mlpack::sparse_coding::SparseCoding::RandomInitDictionary ()
Initialize dictionary by drawing k vectors uniformly at random from the unit sphere.
SetData()
void mlpack::sparse_coding::SparseCoding::SetData (const arma::mat & matX)
Modifier for matX.
SetDictionary()
void mlpack::sparse_coding::SparseCoding::SetDictionary (const arma::mat & matD)
Modifier for matD.
Member Data Documentation
lambda1
double mlpack::sparse_coding::SparseCoding::lambda1 private
Definition at line 208 of file sparse_coding.hpp.
lambda2
double mlpack::sparse_coding::SparseCoding::lambda2 private
Definition at line 211 of file sparse_coding.hpp.
matD
arma::mat mlpack::sparse_coding::SparseCoding::matD private
Definition at line 202 of file sparse_coding.hpp.
Referenced by MatD().
matX
arma::mat mlpack::sparse_coding::SparseCoding::matX private
Definition at line 199 of file sparse_coding.hpp.
matZ
arma::mat mlpack::sparse_coding::SparseCoding::matZ private
Definition at line 205 of file sparse_coding.hpp.
Referenced by MatZ().
nAtoms
arma::uword mlpack::sparse_coding::SparseCoding::nAtoms private
Definition at line 195 of file sparse_coding.hpp.
nDims
arma::uword mlpack::sparse_coding::SparseCoding::nDims private
Definition at line 194 of file sparse_coding.hpp.
nPoints
arma::uword mlpack::sparse_coding::SparseCoding::nPoints private
Definition at line 196 of file sparse_coding.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/sparse_coding/sparse_coding.hpp