main
about
docs
get help
github
mlpack::mvu::MVUObjectiveFunction Class Reference
The MVU objective function.
Public Member Functions
MVUObjectiveFunction ()
MVUObjectiveFunction (const arma::mat &initial_point, const size_t newDim, const size_t numNeighbors)
double Evaluate (const arma::mat &coordinates)
double EvaluateConstraint (const size_t index, const arma::mat &coordinates)
const arma::mat & GetInitialPoint () const
void Gradient (const arma::mat &coordinates, arma::mat &gradient)
void GradientConstraint (const size_t index, const arma::mat &coordinates, arma::mat &gradient)
size_t NumConstraints () const
Private Attributes
arma::mat initialPoint
arma::mat neighborDistances
arma::Mat< size_t > neighborIndices
size_t numNeighbors
Detailed Description
The MVU objective function.
This is a reformulation of the SDP proposed originally by Weinberger and Saul. Their original formulation was:
max (trace(K)) subject to: (1) sum K_ij = 0 (2) K_ii - 2 K_ij + K_jj = || x_i - x_j ||^2 ; for all (i, j) nearest neighbors (3) K >= 0 (K is positive semidefinite)
We reformulate, taking K = R R^T. This gives:
max (R * R^T) subject to (1) sum (R * R^T) = 0 (2) (R R^T)_ii - 2 (R R^T)_ij + (R R^T)_jj = || x_i - x_j ||^2 ; for all (i, j) nearest neighbors
Now, our optimization problem is easier. The total number of constraints is equal to the number of points multiplied by the number of nearest neighbors.
Definition at line 49 of file mvu_objective_function.hpp.
Constructor & Destructor Documentation
MVUObjectiveFunction() [1/2]
mlpack::mvu::MVUObjectiveFunction::MVUObjectiveFunction ()
MVUObjectiveFunction() [2/2]
mlpack::mvu::MVUObjectiveFunction::MVUObjectiveFunction (const arma::mat & initial_point, const size_t newDim, const size_t numNeighbors)
Member Function Documentation
Evaluate()
double mlpack::mvu::MVUObjectiveFunction::Evaluate (const arma::mat & coordinates)
EvaluateConstraint()
double mlpack::mvu::MVUObjectiveFunction::EvaluateConstraint (const size_t index, const arma::mat & coordinates)
Referenced by NumConstraints().
GetInitialPoint()
const arma::mat& mlpack::mvu::MVUObjectiveFunction::GetInitialPoint () const inline
Definition at line 67 of file mvu_objective_function.hpp.
References initialPoint.
Gradient()
void mlpack::mvu::MVUObjectiveFunction::Gradient (const arma::mat & coordinates, arma::mat & gradient)
GradientConstraint()
void mlpack::mvu::MVUObjectiveFunction::GradientConstraint (const size_t index, const arma::mat & coordinates, arma::mat & gradient)
Referenced by NumConstraints().
NumConstraints()
size_t mlpack::mvu::MVUObjectiveFunction::NumConstraints () const inline
Definition at line 60 of file mvu_objective_function.hpp.
References EvaluateConstraint(), GradientConstraint(), and initialPoint.
Member Data Documentation
initialPoint
arma::mat mlpack::mvu::MVUObjectiveFunction::initialPoint private
Definition at line 70 of file mvu_objective_function.hpp.
Referenced by GetInitialPoint(), and NumConstraints().
neighborDistances
arma::mat mlpack::mvu::MVUObjectiveFunction::neighborDistances private
Definition at line 76 of file mvu_objective_function.hpp.
neighborIndices
arma::Mat<size_t> mlpack::mvu::MVUObjectiveFunction::neighborIndices private
Definition at line 75 of file mvu_objective_function.hpp.
numNeighbors
size_t mlpack::mvu::MVUObjectiveFunction::numNeighbors private
Definition at line 71 of file mvu_objective_function.hpp.
The documentation for this class was generated from the following file:
src/mlpack/methods/mvu/mvu_objective_function.hpp