mlpack: mlpack::optimization::LRSDP Class Reference
mlpack::optimization::LRSDP Class Reference
LRSDP is the implementation of Monteiro and Burer's formulation of low-rank semidefinite programs (LR-SDP).
Public Member Functions
LRSDP (const size_t numConstraints, const arma::mat &initialPoint)
Create an LRSDP to be optimized.
LRSDP (const size_t numConstraints, const arma::mat &initialPoint, AugLagrangian< LRSDPFunction > &augLagrangian)
Create an LRSDP to be optimized, passing in an already-created AugLagrangian object.
const std::vector< arma::mat > & A () const
Return the vector of A matrices (which correspond to the constraints).
std::vector< arma::mat > & A ()
Modify the veector of A matrices (which correspond to the constraints).
const arma::uvec & AModes () const
Return the vector of modes for the A matrices.
arma::uvec & AModes ()
Modify the vector of modes for the A matrices.
const AugLagrangian
< LRSDPFunction > & AugLag () const
Return the augmented Lagrangian object.
AugLagrangian< LRSDPFunction > & AugLag ()
Modify the augmented Lagrangian object.
const arma::vec & B () const
Return the vector of B values.
arma::vec & B ()
Modify the vector of B values.
const arma::mat & C () const
Return the objective function matrix (C).
arma::mat & C ()
Modify the objective function matrix (C).
LRSDPFunction & Function ()
Modify the function to be optimized.
const LRSDPFunction & Function () const
Return the function to be optimized.
double Optimize (arma::mat &coordinates)
Optimize the LRSDP and return the final objective value.
std::string ToString () const
Return a string representation of the object.
Private Attributes
AugLagrangian< LRSDPFunction > augLag
The AugLagrangian object which will be used for optimization.
LRSDPFunction function
Function to optimize, which the AugLagrangian object holds.
Detailed Description
LRSDP is the implementation of Monteiro and Burer's formulation of low-rank semidefinite programs (LR-SDP).
This solver uses the augmented Lagrangian optimizer to solve low-rank semidefinite programs.
Definition at line 29 of file lrsdp.hpp.
Constructor & Destructor Documentation
mlpack::optimization::LRSDP::LRSDP (const size_t numConstraints, const arma::mat & initialPoint)
Create an LRSDP to be optimized.
The solution will end up being a matrix of size (rank) x (rows). To construct each constraint and the objective function, use the functions A(), B(), and C() to set them correctly.
Parameters:
numConstraints Number of constraints in the problem.
rank Rank of the solution (<= rows).
rows Number of rows in the solution.
mlpack::optimization::LRSDP::LRSDP (const size_t numConstraints, const arma::mat & initialPoint, AugLagrangian< LRSDPFunction > & augLagrangian)
Create an LRSDP to be optimized, passing in an already-created AugLagrangian object.
The given initial point should be set to the size (rows) x (rank), where (rank) is the reduced rank of the problem.
Parameters:
numConstraints Number of constraints in the problem.
initialPoint Initial point of the optimization.
auglag Pre-initialized AugLagrangian<LRSDP> object.
Member Function Documentation
const std::vector<arma::mat>& mlpack::optimization::LRSDP::A () const [inline]
Return the vector of A matrices (which correspond to the constraints).
Definition at line 63 of file lrsdp.hpp.
std::vector<arma::mat>& mlpack::optimization::LRSDP::A () [inline]
Modify the veector of A matrices (which correspond to the constraints).
Definition at line 65 of file lrsdp.hpp.
const arma::uvec& mlpack::optimization::LRSDP::AModes () const [inline]
Return the vector of modes for the A matrices.
Definition at line 68 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::C(), and function.
arma::uvec& mlpack::optimization::LRSDP::AModes () [inline]
Modify the vector of modes for the A matrices.
Definition at line 70 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::C(), and function.
const AugLagrangian<LRSDPFunction>& mlpack::optimization::LRSDP::AugLag () const [inline]
Return the augmented Lagrangian object.
Definition at line 83 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::B(), and function.
AugLagrangian<LRSDPFunction>& mlpack::optimization::LRSDP::AugLag () [inline]
Modify the augmented Lagrangian object.
Definition at line 85 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::B(), and function.
const arma::vec& mlpack::optimization::LRSDP::B () const [inline]
Return the vector of B values.
Definition at line 73 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::A(), and function.
arma::vec& mlpack::optimization::LRSDP::B () [inline]
Modify the vector of B values.
Definition at line 75 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::A(), and function.
const arma::mat& mlpack::optimization::LRSDP::C () const [inline]
Return the objective function matrix (C).
Definition at line 58 of file lrsdp.hpp.
arma::mat& mlpack::optimization::LRSDP::C () [inline]
Modify the objective function matrix (C).
Definition at line 60 of file lrsdp.hpp.
LRSDPFunction& mlpack::optimization::LRSDP::Function () [inline]
Modify the function to be optimized.
Definition at line 80 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::AModes(), and function.
const LRSDPFunction& mlpack::optimization::LRSDP::Function () const [inline]
Return the function to be optimized.
Definition at line 78 of file lrsdp.hpp.
References mlpack::optimization::LRSDPFunction::AModes(), and function.
double mlpack::optimization::LRSDP::Optimize (arma::mat & coordinates)
Optimize the LRSDP and return the final objective value.
The given coordinates will be modified to contain the final solution.
Parameters:
coordinates Starting coordinates for the optimization.
std::string mlpack::optimization::LRSDP::ToString () const
Return a string representation of the object.
Member Data Documentation
AugLagrangian<LRSDPFunction> mlpack::optimization::LRSDP::augLag [private]
The AugLagrangian object which will be used for optimization.
Definition at line 95 of file lrsdp.hpp.
LRSDPFunction mlpack::optimization::LRSDP::function [private]
Function to optimize, which the AugLagrangian object holds.
Definition at line 92 of file lrsdp.hpp.
Referenced by AModes(), AugLag(), B(), and Function().
The documentation for this class was generated from the following file:
src/mlpack/core/optimizers/lrsdp/lrsdp.hpp